### ISSUE TITLE
update check가 안되네요..

### ISSUE THREAD

**Issue by bokdol** [yona-projects/yona#1]
새로 설치한 yona에 대하여 readme.md에 있는대로 application.conf를 설정한 후 수행하니
다음과 같이 update check가 되고 있지 않습니다.. 
경로가 잘못된건지.. 뭔지 모르겠네요..

[warn] application - Failed to fetch the latest Yobi version to update
org.eclipse.jgit.api.errors.TransportException: http://repo.yona.io/yona/yona: http://repo.yona.io/yona/yona/info/refs?service=git-upload-pack not found
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:223) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:98) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at models.YobiUpdate.refreshVersionToUpdate(YobiUpdate.java:82) ~[yobi.yobi-0.8.2.jar:0.8.2]
	at models.YobiUpdate$1.run(YobiUpdate.java:63) ~[yobi.yobi-0.8.2.jar:0.8.2]
Caused by: org.eclipse.jgit.errors.NoRemoteRepositoryException: http://repo.yona.io/yona/yona: http://repo.yona.io/yona/yona/info/refs?service=git-upload-pack not found
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:488) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:309) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:202) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) ~[org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar:3.5.3.201412180710-r]
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:98) ~[yobi.yobi-0.8.2.jar:0.8.2]

**Comment by doortts** [comment]
안녕하세요? 아직 update 서버 세팅이 변경되어 그런 현상이 나오게 되었습니다. 우선 저장소 url을 https://github.com/yona-projects/yona 로 변경해 주시면 해당 에러는 해결되실겁니다.
README는 수정해 놓았습니다.
https://github.com/yona-projects/yona/blob/next/README.md#applicationconf
