### ISSUE TITLE
yona 설치 후 실행 시 에러 문의입니다.

### ISSUE THREAD

**Issue by godongsori** [yona-projects/yona#11]
운영환경
CentOS 5.11
MariaDB 10.1.11

yobi를 사용하다가 yona로 마이그레이션을 하고자 했습니다.
MariaDB를 설치했고, yona를 실행하니 아래와 같이 메시지가 출력됩니다.
​
Play server process ID is 3584
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - Specified key was too long; max key length is 767 bytes [ERROR:1071, SQLSTATE:42000]
Oops, cannot start the server.
@6p65l4e1a: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

MariaDB에는 연결이 되었지만 이후 작업에서 진행을 하지 못하는 것 같습니다.

set global innodb_file_format = BARRACUDA;
set global innodb_large_prefix = ON;

위 두 줄도 옵션을 설정했고, MariaDB를 재시작하니 초기화 되길래, my.cnf에도 옵션을 지정해 놓았습니다.
그래도 같은 에러가 나오고 있어서 더 이상 진행을 하지 못하고 있네요. 혹시 도움을 받을 수 있을까요?

**Comment by godongsori** [comment]
클로즈 되었던 이슈를 보지 못했네요. ^^;;
yona database를 드롭 후 다시 생성해, 실행하니 정상적으로 실행되었습니다.
