### ISSUE TITLE
Oops, cannot start the serve. / ERROR executing DML bindLog[] error[CONSTRAINT...

### ISSUE THREAD

**Issue by enchantor** [yona-projects/yona#121]
설치 환경
Windows 10, MariaDB 10.2.3

에러 코드
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
Oops, cannot start the server.
javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[CONSTRAINT 'ck_n4user_state' failed for 'yona'.'n4user']
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57)
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:66)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:448)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:331)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:306)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:276)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:244)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1801)
        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1779)
        at com.avaje.ebean.Ebean.save(Ebean.java:526)
        at com.avaje.ebean.Ebean.save(Ebean.java:533)
        at utils.YamlUtil.insertDataFromYaml(YamlUtil.java:45)
        at Global.insertInitialData(Global.java:161)
        at Global.onStart(Global.java:139)
        at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22)
        at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.sql.BatchUpdateException: CONSTRAINT 'ck_n4user_state' failed for 'yona'.'n4user'
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:374)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:347)
        at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
        at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:55)
        at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:134)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86)
        ... 32 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: CONSTRAINT 'ck_n4user_state' failed for 'yona'.'n4user'
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:119)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQueryEpilog(MariaDbServerPreparedStatement.java:336)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:291)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:369)
        ... 37 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: CONSTRAINT 'ck_n4user_state' failed for 'yona'.'n4user'
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:479)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:592)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:279)
        ... 38 more

**Comment by sjstyle** [comment]
n4user 테이블에 state가 null인 데이터가 있는 것은 아닌가요?

다음 쿼리로 데이터가 나오는지 확인해보시면 될 것 같습니다.

``` sql
select *
from n4user
where state is null
```

**Comment by doortts** [comment]
@enchantor 어떤 상황에서 발생하신건지 조금 더 설명을 곁들여 주시면 좋겠습니다. 최초 설치시에 발생한 오류인가요?

**Comment by enchantor** [comment]
급하게 집나오기전에 올리다보니, 너무 오류자체만 올려놔버렸네요 죄송해요! @sjstyle @doortts 최초 설치 직후 실행 상황이고, DB 또한 매뉴얼대로 yona라고 만들어진 상태에서 실행하니 테이블들이 생성되어지고 있는 중 같았는데, 저런 에러와 함께 더 진행이 되지 않았습니다.
매뉴얼에서 window의 경우 설명에 따라서 run.bat 파일을 만들어서 실행을 하였구요!

**Comment by sjstyle** [comment]
@enchantor 
음.. ck_n4user_state constraint는 아래에 정의되어 있습니다. 
https://github.com/yona-projects/yona/blob/next/conf/evolutions/default/1.sql#L451

해당 DB를 제가 접속할 수 없기 때문에 정확한 상황을 말씀드리기는 어렵지만, 로그 내용으로 봤을 때에는 이 전에 yona가 초기화 중에 종료된적이 있는 것 같아보입니다. 

처음 실행하시는 것이라면 해당 DB의 모든 yona 테이블들을 지우고 다시 한번 실행해보시겠어요?

**Comment by enchantor** [comment]
@sjstyle 테이블을 다 지우고 다시 해도 javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[CONSTRAINT `ck_n4user_state` failed for `yona`.`n4user`] 에러가 동이라게 나타나네요.. yona db를 밀고 다시 만들어도 동일한 에러가 나고있어요.

**Comment by doortts** [comment]
@enchantor 제 생각엔 특별히 문제가 발생할만한 부분이 아니고 DB를 지우고 다시 실행해도 마찬가지라면 마리아DB를 베타버전을 사용하신것이 문제가 아닐까 조심스레 유추해(떠넘겨)봅니다.

한번 [이곳 wiki의 설치 방법](https://github.com/yona-projects/yona/wiki/Yona-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)과 해당 설치 방법내의 DB 링크(MariaDB 최신 Stable)를 이용해 설치를 다시 한번 해봐주실수 있을까요?

**Comment by enchantor** [comment]
@sjstyle 헐.. 정말 마리아디비 버전문제 였던것 같네요. 마리아디비 안정화버전 10.1.20버전으로 교체 후 정상적으로 첫 실행이 완료되었습니다.
