### ISSUE TITLE
mention 기능 이용할때 오류납니다.

### ISSUE THREAD

**Issue by leesunghee1229** [yona-projects/yona#135]
@ 를 누르는 순간에 오류가 납니다.

/mentionList?number=3&resourceType=issue_post 500 (Internal Server Error)

위와 같이 오류가 나서 application.log 를 살펴 봤더니
아래와 같습니다.

issue 테이블이 없다고 하는거 같은데 분명 있거든요.

원인이 뭘까요~?

```sh
2017-02-01 09:14:14,918 - [DEBUG] - from play in play-akka.actor.default-dispatcher-797 
Unable to parse part of media range header 'application/json, text/javascript, */*; q=0.01'

2017-02-01 09:14:14,923 - [ERROR] - from play in play-akka.actor.default-dispatcher-797 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Table 'yona.ISSUE' doesn't exist 
Bind values:[] 
Query was:
select distinct author_id id FROM ISSUE where project_id=3 



2017-02-01 09:14:14,924 - [ERROR] - from application in play-akka.actor.default-dispatcher-797 


! @7301oiagk - Internal server error, for (GET) [/tomatopay/mobiletong/mentionList?number=3&resourceType=issue_post] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Table 'yona.ISSUE' doesn't exist 
Bind values:[] 
Query was:
select distinct author_id id FROM ISSUE where project_id=3 

]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Table 'yona.ISSUE' doesn't exist 
Bind values:[] 
Query was:
select distinct author_id id FROM ISSUE where project_id=3 


	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:834) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:811) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:205) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findMany(DefaultOrmQueryEngine.java:77) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findSet(OrmQueryRequest.java:271) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findSet(DefaultServer.java:1296) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findSet(DefaultOrmQuery.java:894) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at controllers.ProjectApp.getIssueUsers(ProjectApp.java:1231) ~[yona.yona-1.2.0.jar:1.2.0]
	at controllers.ProjectApp.findAuthorsAndWatchers(ProjectApp.java:1216) ~[yona.yona-1.2.0.jar:1.2.0]
	at controllers.ProjectApp.addProjectAuthorsAndWatchersList(ProjectApp.java:813) ~[yona.yona-1.2.0.jar:1.2.0]
	at controllers.ProjectApp.mentionList(ProjectApp.java:380) ~[yona.yona-1.2.0.jar:1.2.0]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$116$$anonfun$apply$116.apply(routes_routing.scala:2646) ~[yona.yona-1.2.0.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$116$$anonfun$apply$116.apply(routes_routing.scala:2646) ~[yona.yona-1.2.0.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at Global$1.call(Global.java:191) ~[yona.yona-1.2.0.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.2.0.jar:1.2.0]
	at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yona.yona-1.2.0.jar:1.2.0]
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:97) ~[yona.yona-1.2.0.jar:1.2.0]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'yona.ISSUE' doesn't exist
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:125) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:259) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:287) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:444) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:119) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:409) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:368) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findMany(CQueryEngine.java:165) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 50 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Table 'yona.ISSUE' doesn't exist
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:479) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.result(AbstractQueryProtocol.java:400) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:381) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:337) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:277) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	... 56 common frames omitted
```

**Comment by leesunghee1229** [comment]
음... 대소문자 구별하는건가 보네요?
디비에 보면 소문자로 issue 라고 되어 있네요...

**Comment by leesunghee1229** [comment]
제 디비 설정을 변경해서 해결했습니다.
대소문자 구별안하도록 설정하니 별문제 없네요 ^^;
