### ISSUE TITLE
윈도우에서 설치시 yona.bat

### ISSUE THREAD

**Issue by haare** [yona-projects/yona#137]
안녕하세요

컴알못이 위키보면서 따라하고 있는데 여기에서 막혔답니다. ㅠㅠㅠㅠ

** application.conf 파일등 생성하기 **
압축이 풀린 곳으로 이동해서 bin/yona 을 실행합니다. (Java 8 이상이 필요합니다) 주의: 아래와 같이 yona 설치 폴더에서 실행하여야 합니다. 또한 윈도우 사용자는 bin/yona 대신 bin/yona.bat을 실행해야 합니다.

![image](https://cloud.githubusercontent.com/assets/25476922/22586018/e78571ac-ea3d-11e6-8407-8b6beffcbe71.png)

자바는 맞게 설치되어있는것 같은데..
![image](https://cloud.githubusercontent.com/assets/25476922/22586050/0d65fbee-ea3e-11e6-8bad-b64c4a04989a.png)

![image](https://cloud.githubusercontent.com/assets/25476922/22586081/36f3ed4a-ea3e-11e6-9c9c-de2a03ead1e8.png)

요나 도입을 당당히 상반기 KPI로 제출했는데 울고 있어요

도움 요청드립니다.

**Comment by sjstyle** [comment]
#130 에 마지막 부분을 참고해 주세요~

**Comment by sjstyle** [comment]
그리고 가급적 MariaDB 밑에 yona를 두는 것은 좋지 않을 것 같습니다. 
Program Files 밑에 두시거나 가급적 드라이브 루트에 두시기를 권장합니다.

**Comment by haare** [comment]
네 감사합니다.!! 
지금 빵씹으면서 읽고 있어영 :)

**Comment by doortts** [comment]
@haare 굉장히 현장감이 있네요...;;

**Comment by junho103** [comment]
지금 1.3 버전으로 하고 계신가요?
@haare 

입력줄이 너무 깁니다는. 1.2때 bat 파일에서 나왔고, 1.3 bat서는 수정된걸로 보여지는데요~

**입력줄이 너무 깁니다**를 해결 하고 났는데  아래처럼 오류가 발생한다면 
*오류: 기본 클래스 Files\yona\yona-1.3.0\bin\\\..을(를) 찾거나 로드할 수 없습니다*

아래 굵은줄을 환경에 맞게 조정해보시겠어요? 

>**SET YONA_HOME="F:\Progra~1\yona\yona-1.3.0"**
>if "%YONA_HOME%"=="" set "YONA_HOME=%~dp0\\.." 

>**SET YONA_DATA="F:\Progra~1\yona\data"**
> if "%YONA_DATA%"=="" set "YONA_DATA=%~dp0\\.." 

제가... 

SET YONA_DATA=F:\Program^ Files\yona\data
SET YONA_DATA="F:\Program Files\yona\data"

다해봤는데..."F:\Progra~1 이걸로 해주니 되더라구요...

**Comment by haare** [comment]
@junho103 @doortts 다시 처음부터 하고 있는데 그 앞에서 막혀서 아직 해보지를 못했어요 ㅎㅎ 감사합니다.

**Comment by junho103** [comment]
@haare 저랑 비슷하게 구성하신거 같은데 하시다 안되는거 있으면 올려주셔요~~ 제가 도움드릴수 있을지도 모르겠네요

**Comment by haare** [comment]
@junho103 감사합니다. 지금 앞부분 막혔던걸 막 해결 (windows7+nginx+php+mariaDB / maria db 에 yona로 로그인이 안되서 HeidiSQL로 비번을 따로 쳐 넣었;;;;;)하고 1.3 bat를 실행했더니 아래와 같이 뙇

일단 업무 끝나고 봐야할것 같아용 홓홓홓

C:\Windows\system32>cd C:\yona-1.3.0\bin

C:\yona-1.3.0\bin>yona.bat
Play server process ID is 9108
Oops, cannot start the server.
Configuration error: Configuration error[C:\yona-1.3.0\bin\..\conf\application.c
onf: java.io.FileNotFoundException: C:\yona-1.3.0\bin\..\conf\application.conf (
지정된 경로를 찾을 수 없습니다)]
        at play.api.Configuration$.play$api$Configuration$$configError(Configura
tion.scala:94)
        at play.api.Configuration$.load(Configuration.scala:66)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.app
ly(Application.scala:76)
        at play.api.WithDefaultConfiguration$$anonfun$initialConfiguration$1.app
ly(Application.scala:76)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.WithDefaultConfiguration$class.initialConfiguration(Applicat
ion.scala:75)
        at play.api.DefaultApplication.initialConfiguration$lzycompute(Applicati
on.scala:402)
        at play.api.DefaultApplication.initialConfiguration(Application.scala:40
2)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalCl
ass(Application.scala:25)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass$l
zycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalClass(A
pplication.scala:402)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlob
al(Application.scala:31)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lz
ycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Ap
plication.scala:402)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globa
lInstance$1.apply(Application.scala:54)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globa
lInstance$1.apply(Application.scala:53)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalIn
stance(Application.scala:52)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstanc
e$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstanc
e(Application.scala:402)
        at play.api.WithDefaultGlobal$class.global(Application.scala:68)
        at play.api.DefaultApplication.global(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfigura
tion$$fullConfiguration(Application.scala:82)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullCo
nfiguration$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullCo
nfiguration(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.configuration(Application.sca
la:84)
        at play.api.DefaultApplication.configuration(Application.scala:402)
        at play.api.Application$class.$init$(Application.scala:274)
        at play.api.DefaultApplication.<init>(Application.scala:402)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:
289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:
284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: com.typesafe.config.ConfigException$IO: C:\yona-1.3.0\bin\..\conf\app
lication.conf: java.io.FileNotFoundException: C:\yona-1.3.0\bin\..\conf\applicat
ion.conf (지정된 경로를 찾을 수 없습니다)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:183)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:595)
        at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.jav
a:244)
        at com.typesafe.config.ConfigFactory.access$000(ConfigFactory.java:38)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:378)
        at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:375)
        at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(Confi
gImpl.java:58)
        at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.ja
va:86)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:375)
        at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:299)
        at play.api.Configuration$.dontAllowMissingConfig$lzycompute(Configurati
on.scala:29)
        at play.api.Configuration$.dontAllowMissingConfig(Configuration.scala:29
)
        at play.api.Configuration$.load(Configuration.scala:64)
        ... 34 more
Caused by: java.io.FileNotFoundException: C:\yona-1.3.0\bin\..\conf\application.
conf (지정된 경로를 찾을 수 없습니다)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.typesafe.config.impl.Parseable$ParseableFile.reader(Parseable.jav
a:512)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:193)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
        ... 48 more

C:\yona-1.3.0\bin>

**Comment by haare** [comment]
홈/데이터 설정문서를 읽고 있어여

**Comment by sjstyle** [comment]
@haare 
C:\yona-1.3.0\bin 이 아닌 C:\yona-1.3.0 에서 bin/yona.bat 으로 실행해보시겠어요?

**Comment by haare** [comment]
@sjstyle 감사합니다!! 제가 아직 뭐가 덜 되었나봐요 
![image](https://cloud.githubusercontent.com/assets/25476922/22683020/4edcbbd0-ed59-11e6-8c79-4f8cd76b7fea.png)

제가 오른쪽에 보이는 설치 메뉴만 바로 보고 했더니 아래 2가지 항목을 진행을 안했었어요
아마 하고나면 되지 않을까 싶어요
![image](https://cloud.githubusercontent.com/assets/25476922/22683094/a9e630a6-ed59-11e6-8d57-9ca26e20594b.png)

**Comment by junho103** [comment]
@haare 윈도우 환경 이시라 **bin\yona.bat** 로 실행하셔야 해요

**Comment by sjstyle** [comment]
아 죄송합니다;; 개발할때 윈도우를 안쓴지 1년이 넘어가니 슬슬 헷갈리는군요

**Comment by junho103** [comment]
혹 안되신다면 저는 경로구성을 아래처럼 했는데요 시작스크립트 올려드릴께요 참고해보세요.
![image](https://cloud.githubusercontent.com/assets/12494817/22683332/d0482276-ed5a-11e6-97fd-5b112fdbb374.png) 
 
```
@title YONA Server

SET YONA_HOME=F:\Progra~1\yona\yona-1.3.0
SET YONA_DATA=F:\Progra~1\yona\data
SET JAVA_OPTS=-Xmx2048m -Xms2048m

yona-1.3.0\bin\yona.bat
```

**Comment by haare** [comment]
@junho103 천사 준호님이 주신 스크립트를 참고하여 했으나 
![image](https://cloud.githubusercontent.com/assets/25476922/22684994/f3dca2b4-ed61-11e6-9eef-e8f9aea3aaa1.png)
![image](https://cloud.githubusercontent.com/assets/25476922/22685003/fbb77054-ed61-11e6-91bd-61079c783536.png)


위키를 읽어보고 있지만 잘 이해가 안가서 계속 읽어보고 있습니다.

감사합니다.

**Comment by sjstyle** [comment]
yona-data\conf에 application.conf가 없으셔서 발생하는 문제입니다.
최초 설치시에 application-default.conf 파일을 복사하셔서 application.conf 로 이름을 적어두신 다음 디비설정과 같은 여러 설정들을 진행하셔야 사용할 수 있습니다.

**Comment by minishanell** [comment]
아래 설명을 참고하세요..  (요나 공식 문서)
https://github.com/yona-projects/yona/blob/master/docs/application-conf-desc.md

아래에 있는 디폴트 applicaton.conf를 복사해다가.. 메모장에 붙여넣고.. 아래 부분을 수정하시면 됩니다.
사용하시는 DB에 맞춰 설정하시면 되는데... 쭉 내려보시면.. DB설정란이 있어요. (MariaDB만 붙여봅니다)
````
# MariaDB
db.default.driver=org.mariadb.jdbc.Driver
db.default.url="jdbc:mariadb://127.0.0.1:3306/yona?useServerPrepStmts=true"
db.default.user=yona
db.default.password="password"
```
여기서.. password 만 수정하시면 됩니다.
DB가 해당 머신에 설치되어 있고.. DB명과 유저명이 yona라면요.. ^^

**Comment by haare** [comment]
안녕하세요. 제 삽질기가 계속되네요

* 윈도우용 파일들을 다운 받아서 압축을 풀었을 때 application-default.conf 을 찾을 수 없어서  @minishanell 님이 알려주신 것 처럼 
![image](https://cloud.githubusercontent.com/assets/25476922/22688051/ead425a0-ed6d-11e6-91ae-29b1d29ee90c.png)을 우클릭 다운로드 해서 default를 지우고 application.conf으로 맹글었습니다.

> 그랬더니 이상한게 많아서 ㅋㅋ application.conf 기본 설정내용을 싹 복사하고 MariaDB 부분을 변경했습니다. 다른 부분들은 손 한게도 안댔어요
![image](https://cloud.githubusercontent.com/assets/25476922/22688202/8679f9c6-ed6e-11e6-9023-d4d38813c136.png)

MariaDB는 지금 요나와 같은 PC에 설치를 해놨습니다.

그리고 나서 앞서 삽질해놨던 배치파일을 실행했습니다.
![image](https://cloud.githubusercontent.com/assets/25476922/22688267/ce7af87e-ed6e-11e6-8db3-b7d503cc9862.png)


역시 안되네용

혹시나 nginx를 설정할때 포트를 88로 변경하고 Php 관련 포트는 9123으로 변경했었거든요 그래서 %prod.http.port=80을 88로 변경했는데 안되네용 - https://brendaniel.github.io/2017/02/01/Nginx-for-Windows/ 여기 링크를 참고해서 Nginx와 Php를 설치하긴해습니다.

많은 분들이 도와주셨는데 그냥 포기하고 새로운 윈도우 PC나 리눅스를 설치하여 도전해볼까 생각하고 있습니다..

**Comment by minishanell** [comment]
저거.... PID 파일이 생성되어 있어서.. 그런거에요.
c:\yona\yona-1.3.0\Running_pid 파일을 지우시고요....
다시 실행해보세요 ^^

PHP포트랑... http 포트는 신경안쓰셔도.. 요나 돕니다. ^^:;
엔진엑스가 아니라.. 별도의 PLAY 웹서버거든요...
저도 아파치랑 요나 각자 돌아요..

**Comment by haare** [comment]
@minishanell 
일단 러닝PID 파일을 지웠어요
그랬더니 뭔가 막 돌아가고 지정된 파일도 못찾고 그래서 아 이생망 이러고 있었어요
![image](https://cloud.githubusercontent.com/assets/25476922/22688774/16f0840a-ed71-11e6-8059-50e6db1ad5e9.png)




그리고 나서 그래도 혹시 돌아가나 해서 http://127.0.0.1:9000/ 를 들어갔더니
![image](https://cloud.githubusercontent.com/assets/25476922/22688733/eb2e9046-ed70-11e6-9ceb-617d05bcfe0a.png)

뙇

**Comment by minishanell** [comment]
아.. 원인이 뭔지 알 것 같아요 ㅇ_ㅇ;;;
/yona_data/conf 의 전 파일이 다 없으신 듯 한데요..??
기본 파일은 받으셨으니 나머지 받아가지고.. 메꾸시면 됩니다..

필요한 파일이....
application.conf      
application-logger.xml
social-login.conf

이거 3개 있으시면 됩니다. 받는 장소는 찾아서 올려드리지요 ^^:

**Comment by haare** [comment]
@sjstyle @minishanell @junho103  감사합니다 ^_^

**Comment by minishanell** [comment]
https://github.com/yona-projects/yona/tree/master/conf

여기서.. 위 3파일의 디폴트 파일 받으셔서.. 이름 바꾼다음 넣으시면 됩니다.
application.conf     <- 이건 이미 수정하셨고...
application-logger.xml <- 이런 로컬 함수라서.. 그대로 넣으시면 되구요..
social-login.conf <- 이건 소셜 로그인 용인데.. 디폴트값으로 넣으셨다가 쇼설 세팅하시면서 바꾸시면 됩니다.

**Comment by haare** [comment]
@minishanell 어머 무슨 말씀인지 하나도 모르겠어요 ㅎㅎ

설치 설정 순서가 뒤죽박죽이어서 그랬나봐요 자바라서 사실 없어도 잘 돌아요라고 하시니 왠 삽질을 이리 했나 싶어요

너무 감사합니다.

**Comment by minishanell** [comment]
/yona_data/conf/ 폴더 아래에요..

아래 내용을 application-logger.xml 로 저장하세요.
https://raw.githubusercontent.com/yona-projects/yona/master/conf/application-logger.xml.default

그리고 아래 내용을 그대로 social-login.conf 로 저장하세요.
https://raw.githubusercontent.com/yona-projects/yona/master/conf/social-login.conf.default

그리고.. 재실행하시면 됩니다. ^^;; 이제 파일 없다는 소리 안나올꺼에요.

**Comment by minishanell** [comment]
공식문서에도.. 설치 자체는 위키랑 동일하게 간결하게 나와있는데요.. ㅇ_ㅇ;;

https://github.com/yona-projects/yona/blob/master/docs/ko/install-yona-server.md

사실 요나만 쓰시면 PHP랑 웹서버는 안쓰셔도 되어요... 어디서 설치하라고 했을까요??

**Comment by haare** [comment]
@minishanell 아 저의 설치 설정 순서가 뒤죽박죽이었다는;; 사실 PHP랑 웹서버도 다른 툴에선 깔길래 왜 까는지도 모르면서 당연히 깔아야하나 하면서 깔았어요 ㅋ_ㅋ 정리 차원에서 한번 정리해볼까 해요

**Comment by haare** [comment]
보관용

![1](https://user-images.githubusercontent.com/25476922/37266357-fa865d10-25fc-11e8-962c-6f145f91b94c.JPG)
![image](https://user-images.githubusercontent.com/25476922/37266365-047a0d26-25fd-11e8-8d90-bb492d2f3788.png)
