### ISSUE TITLE
1.3 업그레이드 이후 실행시 오류가 발생합니다. 어디를 수정해야하는지요.

### ISSUE THREAD

**Issue by tabago** [yona-projects/yona#139]
Play server process ID is 3459
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
안녕하세요 1.3으로 업그레이드 이후 실행하면 이런 오류가 발생하고 있습니다..

어디부분은 수정해야하는지요 

소셜 로그인은 필요가 없는데..

오류 확인좀 부탁드립니다.

[info] play - Starting application default Akka system.
Oops, cannot start the server.
java.lang.RuntimeException: Provider 'google' missing needed setting 'clientId'
	at com.feth.play.module.pa.providers.AuthProvider.onStart(AuthProvider.java:74)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
yona@localhost ~/play/yona>

**Comment by doortts** [comment]
안녕하세요? 이번에는 업그레이드 후 조금 더 설정을 해주셔야 하는 부분이 생겼습니다.

위키의 [Yona 1.3으로 업그레이드 하기](https://github.com/yona-projects/yona/wiki/Yona-1.3%EC%9C%BC%EB%A1%9C-%EC%97%85%EA%B7%B8%EB%A0%88%EC%9D%B4%EB%93%9C-%ED%95%98%EA%B8%B0) 3번 항목 혹은 
관련해서는 [발생 가능한 문제상황들과 해결방법](https://github.com/yona-projects/yona/blob/master/docs/ko/trouble-shootings.md#runtimeexception-provider-google-missing-needed-setting-clientid) 문서를 참고해주세요.

그리고 소셜로그인을 사용하지 않도록 설정하시려면 설정내용 중 
```
application.social.login.support = "github, google"
```
이 부분을 지우시거나  아래처럼 변경해주시면 됩니다.

```
application.social.login.support = ""
```

**Comment by minishanell** [comment]
혹시.. 실행전에 환경변수 넣고.. 하셨을까요??

1.3 이전에는 필요가 없었던 거 같은데.. 예전과는 달리.. 
```
YONA_DATA=요나데이터 절대경로;export YONA_DATA
bin/yona
```
이런 식으로 실행해야 되더라구요 ^^ㅋ

**Comment by tabago** [comment]
네네 확인했습니다..
감사합니다.
