### ISSUE TITLE
이 문제는 뭔가요?

### ISSUE THREAD

**Issue by Gojhon** [yona-projects/yona#162]
[error] akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]]
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?

**Comment by doortts** [comment]
현재 애플리케이션의 상태와 로그를 좀 더 보여주실수 있을까요?

**Comment by Gojhon** [comment]
akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:114)
	at akka.event.LoggingBus$$anonfun$4$$anonfun$apply$1.applyOrElse(Logging.scala:113)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Failure.recover(Try.scala:185)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:113)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:108)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:722)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:721)
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:108)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:615)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:615)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:632)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:108)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1$$anonfun$43.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1$$anonfun$43.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$withActorClassloader(SbtWeb.scala:451)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1.apply(SbtWeb.scala:416)
	at scala.Option.fold(Option.scala:157)
	at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$load(SbtWeb.scala:419)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$globalSettings$1$$anonfun$apply$1.apply(SbtWeb.scala:131)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$globalSettings$1$$anonfun$apply$1.apply(SbtWeb.scala:131)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at sbt.Project$.setProject(Project.scala:290)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:476)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$.process(Command.scala:95)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.State$$anon$1.process(State.scala:179)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.MainLoop$.next(MainLoop.scala:100)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
	at scala.util.Try$.apply(Try.scala:161)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
	at akka.event.LoggingBus$$anonfun$4.apply(Logging.scala:111)
	... 62 more
akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]]
	at akka.event.LoggingBus$class.startDefaultLoggers(Logging.scala:142)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:26)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:622)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:617)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:615)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:615)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:632)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:108)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1$$anonfun$43.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1$$anonfun$43.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$withActorClassloader(SbtWeb.scala:451)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1.apply(SbtWeb.scala:417)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$load$1.apply(SbtWeb.scala:416)
	at scala.Option.fold(Option.scala:157)
	at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$load(SbtWeb.scala:419)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$globalSettings$1$$anonfun$apply$1.apply(SbtWeb.scala:131)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$globalSettings$1$$anonfun$apply$1.apply(SbtWeb.scala:131)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at sbt.Project$.setProject(Project.scala:290)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:476)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.BuiltinCommands$$anonfun$loadProjectImpl$2.apply(Main.scala:467)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:62)
	at sbt.Command$.process(Command.scala:95)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.State$$anon$1.process(State.scala:179)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.MainLoop$.next(MainLoop.scala:100)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
[error] akka.ConfigurationException: Could not start logger due to [akka.ConfigurationException: Logger specified in config can't be loaded [akka.event.slf4j.Slf4jLogger] due to [java.lang.ClassNotFoundException: akka.event.slf4j.Slf4jLogger]]
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [root@localhost yona]#

**Comment by Gojhon** [comment]
./restart.sh port=9000
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

No java installations was detected.
Please go to http://www.java.com/getjava/ and download

**Comment by Gojhon** [comment]
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000eab00000, 357564416, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 357564416 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/yona/hs_err_pid7760.log

**Comment by doortts** [comment]
언듯 보면 메모리 문제처럼 보이긴 하지만 그 보다는 OpenJDK를 사용해서가 아닐까 라는 생각이 들었습니다. 다소 번거로우시겠지만 Oracle JDK 8 을 설치해서 java -version 으로 확인해 보신 후 다시 실행 테스트 부탁드릴게요.

**Comment by doortts** [comment]
@Gojhon 오래간 응답이 없으셔서 우선 닫음 처리 합니다.
