### ISSUE TITLE
yona 이클립스 프로젝트 설정방법

### ISSUE THREAD

**Issue by jinho1410** [yona-projects/yona#175]
안녕하세요. 반갑습니다.
잠재적인 커밋터가 되기 위해 우선 이클립스 프로젝트로 등록을 하고있는 중입니다.
git 저장소는 클론을 했는데 프로젝트 import가 되지 않습니다.

하는수 없이 general project로 등록을 하였는데
환경설정 잡기가 막막합니다. 

원래 환경설정 정보는 같이 포함이 안되어있는 건가요?
환경설정 안내 가이드는 어디에서 찾을 수 있을까요?.

이곳에 등록해도 되는지 모르겠지만 다른곳은 찾질 못하겠네요.
좋은 오픈소스 운용 감사드립니다.

**Comment by doortts** [comment]
안녕하세요? @jinho1410  님

반갑습니다! :  )

Yona 는 playframework을 사용하고 있어서 해당 프레임워크의 IDE 세팅방법을 따르고 있습니다.
https://www.playframework.com/documentation/2.3.x/IDE#Eclipse
play framework을 세팅했고 git clone 하셨으면 clone 받은 저장소 폴더에서 activator를 실행하셔서 IDE 세팅 명령어를 사용하시면 됩니다. 

자세한 내용은 @rtboss 님의 [yona Source로 빌드하는 방법](https://repo.yona.io/rtboss/Git_Yona_TortoiseGit/post/7)을 참고해주세요.

참고로 저는 개발시에 IntelliJ IDEA를 사용하고 있습니다.

**Comment by csj4032** [comment]
인텔리J도 개발환경 설정이 만만하진 않으네요 :)

**Comment by doortts** [comment]
@csj4032 인텔리J는 위 링크에 추가로 아래 링크도 같이 보시면 도움이 되실거에요
https://www.jetbrains.com/help/idea/2016.3/getting-started-with-play-2-x.html

**Comment by wifiz** [comment]
@doortts 
인텔리제이에서 아래와 같이 에러가 나는데 혹시 해결할 수 있는 방법이 있을까요?...
java.lang.UnsatisfiedLinkError: no jnotify in java.library.path

**Comment by doortts** [comment]
@wifiz OS환경과 자바 버전이 어떻게 되세요?

**Comment by wifiz** [comment]
@doortts 
환경은 아래와 같습니다.
macOS Sierra 10.12.4
java version "1.8.0_112"

**Comment by sjstyle** [comment]
혹시 SBT auto import 기능은 키셨나요? 
키셨다면 `~/.ivy2/cache/net.contentobjects.jnotify` 디렉토리가 있어야 할 것 같습니다.

**Comment by wifiz** [comment]
@doortts 
해당 폴더가 있는데도 같은 에러가 발생하네요.
요나 소스받고 typesafe-activator-1.2.10-minimal 받아서 요나 폴더에서 실행하고
인텔리제이에 스칼라 플러그인 설치후에 요나 프로젝트를 임포트 하니 이것저것 막 설치되고나서...
play2 run 시켰습니다..그런데 왜 안될까요..ㅠ

추가로 Global.java 파일에..364라인.. 아래 코드중에 service() 이부분을 못찾는다고 나오는데..
이건 문제가 안되는건지요?..

    @Override
    public Handler onRouteRequest(RequestHeader request) {
        // If request method is webdav method, SvnApp serves this request
        // because Play2 cannot route them.
        if (SvnApp.isWebDavMethod(request.method())) {
            return routes.ref.SvnApp.**service()**.handler();
        } else {
            return super.onRouteRequest(request);
        }
    }


exception
[warn] Error loading JNotify watch service: no jnotify in java.library.path
--- (Running the application, auto-reloading is enabled) ---

java.lang.UnsatisfiedLinkError: no jnotify in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.contentobjects.jnotify.macosx.JNotify_macosx.<clinit>(Unknown Source)
	at net.contentobjects.jnotify.macosx.JNotifyAdapterMacOSX.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.contentobjects.jnotify.JNotify.<clinit>(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.JNotifyPlayWatchService$JNotifyDelegate.ensureLoaded(PlayWatchService.scala:168)
	at play.runsupport.JNotifyPlayWatchService$$anonfun$5.apply(PlayWatchService.scala:223)
	at play.runsupport.JNotifyPlayWatchService$$anonfun$5.apply(PlayWatchService.scala:179)
	at scala.util.control.Exception$Catch$$anonfun$withTry$1.apply(Exception.scala:129)
	at scala.util.control.Exception$Catch$$anonfun$withTry$1.apply(Exception.scala:129)
	at scala.util.control.Exception$Catch.apply(Exception.scala:102)
	at scala.util.control.Exception$Catch.withTry(Exception.scala:129)
	at play.runsupport.JNotifyPlayWatchService$.apply(PlayWatchService.scala:179)
	at play.runsupport.PlayWatchService$$anon$1.delegate$lzycompute(PlayWatchService.scala:65)
	at play.runsupport.PlayWatchService$$anon$1.delegate(PlayWatchService.scala:61)
	at play.runsupport.PlayWatchService$$anon$1.watch(PlayWatchService.scala:74)
	at play.runsupport.Reloader.<init>(Reloader.scala:268)
	at play.runsupport.Reloader$.reloader$lzycompute$1(Reloader.scala:174)
	at play.runsupport.Reloader$.play$runsupport$Reloader$$reloader$1(Reloader.scala:174)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:197)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:75)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:75)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:98)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:54)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:138)
	at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:135)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer.<init>(NettyServer.scala:135)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:320)
	at play.core.server.NettyServer$$anonfun$mainDev$1.apply(NettyServer.scala:318)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.NettyServer$.mainDev(NettyServer.scala:317)
	at play.core.server.NettyServer$.mainDevHttpMode(NettyServer.scala:313)
	at play.core.server.NettyServer.mainDevHttpMode(NettyServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:197)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:75)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$PlayRun$class$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:75)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:98)
	at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:54)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 1 s, completed Mar 29, 2017 3:26:16 PM

**Comment by csj4032** [comment]
@wifiz 

추가로 Global.java 파일에..364라인.. 아래 코드중에 service() 이부분을 못찾는다고 나오는데..
이건 문제가 안되는건지요?
![2017-03-29 5 51 21](https://cloud.githubusercontent.com/assets/951472/24446463/780e167c-14a8-11e7-8c98-46042a95a4c3.png)

이부분은 첨부한 스크린샷 참고 하시면 될듯합니다.

**Comment by doortts** [comment]
개발모드인 run 에서 발생하는 이 문제는 우선 skip 하셔도 될 것 같습니다. 
start에서도 동일한 문제가 발생하는지 확인부탁드릴게요.

추가설명
---
JNotify 는 시스템의 file watch 기능을 구현하는 부분인데요 원래 OS나 Java version 따라 문제 많은 부분이기도 해요. 

도움이 될런지 모르겠습니다만.. 참고: 
- http://stackoverflow.com/a/20422586/1450196
- http://jnotify.sourceforge.net/

**Comment by wifiz** [comment]
@doortts 
알려주신 링크에서 JNotify 다운 받아 압축 풀고 해당 경로를 아래처럼 패쓰를 잡아주니 해결되었습니다.
export DYLD_LIBRARY_PATH=${PATH}:경로

Global.java 파일에..364라인.. 아래 코드중에 service()... 이부분은 그래도 여전히..
cannot resolve method service() 라고 나오네요...
그래도 play run 시키면 정상적으로 요나 페이지가 열립니다.

감사합니다..

**Comment by doortts** [comment]
@wifiz 제 생각에 이 문제는 최초 실행시에 의존 라이브러리들이 download 될 때 모종의 알 수 없는 이유로 몇 몇 라이브러리가 제대로 다운로드가 안되었어서 발생한것으로 보입니다.

 ~/.ivy2/cache 폴더 전체 다 삭제하고 처음부터 다시 설치하시면 앞선 문제까지 다 해결되지 않을까 조심스레 유추해봅니다.
