### ISSUE TITLE
처음 설치 후 실행 시의 문제점

### ISSUE THREAD

**Issue by rkttu** [yona-projects/yona#205]
# 테스트 환경
MariaDB를 데이터베이스로 사용하여 처음 설치 후 실행 시의 문제점 때문에 서버를 시작할 수 없습니다. 테스트 환경은 Windows 10 Anniversary Update 64비트이고, JDK/JRE 1.8 64비트 버전입니다. 데이터베이스는 MariaDB 10.1 64비트 버전입니다.

# 현상
a. yona 초기 설정 파일이 생성된 다음 db 연결 정보를 변경해서 yona를 시작하면 db 연결 시 비밀 번호가 잘못되었다는 메시지가 나오면서 서버가 중단됩니다.
b. 몇 번의 trial and error를 거쳐서 비밀번호가 튜토리얼 문서에 있는 "yonadan"이라는 것을 알아낸 후에 db 연결 정보를 수정하였지만 다음과 같이 오류가 발생하면서 마찬가지로 서버가 중단됩니다.

```
C:\Server\yona-1.4.1\bin>yona
Play server process ID is 1692
<이 시점에서 http://localhost:9000 으로 서버 접속>
[error] c.j.b.h.AbstractConnectionHook - Failed to acquire connection to jdbc:mariadb://localhost:3306/yona?useServerPrepStmts=true Sleeping for 1000ms and trying again. Attempts left: 3. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Too many connections.Message:Could not connect: Too many connections
[error] c.j.b.h.AbstractConnectionHook - Failed to acquire connection to jdbc:mariadb://localhost:3306/yona?useServerPrepStmts=true Sleeping for 1000ms and trying again. Attempts left: 2. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Too many connections.Message:Could not connect: Too many connections
[error] c.j.b.h.AbstractConnectionHook - Failed to acquire connection to jdbc:mariadb://localhost:3306/yona?useServerPrepStmts=true Sleeping for 1000ms and trying again. Attempts left: 1. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Too many connections.Message:Could not connect: Too many connections
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Too many connections
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:566)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:507)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:392)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
        at org.mariadb.jdbc.Driver.connect(Driver.java:104)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
        at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:469)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
        ... 22 more
```

## Case A에 대한 재현 방법
1. yona 표준 패키지 (h2 패키지 아님) 1.4.1 버전을 압축 해제하고 yona 명령을 실행합니다. 압축 해제 전에 "출처를 알 수 없는 파일에 대한 신뢰" 설정을 파일 속성에서 승인하고, Windows 탐색기의 내장 ZIP 압축 해제 기능을 사용하여 압축을 해제하였습니다.
2. 안내하는 서버로 접속을 시도하면 서버가 중단되면서 conf, logs 폴더 및 파일이 bin 디렉터리에 생성됩니다.
3. conf 폴더의 application.conf 파일을 텍스트 편집기로 엽니다.
4. MariaDB 부분의 주석이 해제가 되어있고, 해당 파일의 데이터베이스 연결 정보, 사용자 아이디, 비밀 번호를 수정하고 저장합니다.
5. 다시 yona 명령을 실행하여 서버를 시작하고 접속을 시도하면 콘솔 로그 상에 비밀 번호가 잘못되었다는 오류 메시지가 나타나면서 서버가 중단됩니다.

## Case B에 대한 재현 방법
1. yona 표준 패키지 (h2 패키지 아님) 1.4.1 버전을 압축 해제하고 yona 명령을 실행합니다. 압축 해제 전에 "출처를 알 수 없는 파일에 대한 신뢰" 설정을 파일 속성에서 승인하고, Windows 탐색기의 내장 ZIP 압축 해제 기능을 사용하여 압축을 해제하였습니다.
2. 안내하는 서버로 접속을 시도하면 서버가 중단되면서 conf, logs 폴더 및 파일이 bin 디렉터리에 생성됩니다.
3. Case A를 분석한 결과 설정 파일을 읽지 않는 것으로 파악됩니다. 설정 파일의 내용을 고려하지 않고, 유추한 계정 정보인 ID yona, PW yonadan으로 maria db에 새로운 계정을 생성하고 yona 데이터베이스에 대해 전체 권한을 부여합니다.
4. 다시 yona 명령을 실행하여 서버를 시작하고 접속을 시도하면 콘솔 로그 상에 Too many connections 오류 메시지가 나타나면서 서버가 중단됩니다.

# 현재 시도해보려는 대안
Maria DB 버전을 사용할 수 없는 상황이어서 H2 임베디드 데이터베이스 버전으로 테스트를 시작하려고 합니다.

**Comment by doortts** [comment]
@rkttu 안녕하세요? 접속이 되지 않아 답답하셨으텐데 적어주신 내용만으로 봤을때는 MariaDB 설치 후 DB Schema 생성을 하지 않으신 것은 아닌가 생각됩니다.
에러 자체도 DB 접속이 되지 않는 에러이구요.

MariaDB 설치 후 DB 생성하는 작업을 직접 해주셔야 합니다. (아쉽게도 자동화 시켜 놓진 않았네요)

위키 매뉴얼의 [Yona 설치하기](https://github.com/yona-projects/yona/wiki/Yona-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0) 에서 1. MariaDB 설치 - Windows 항목을 참고해 주시겠어요?

**Comment by rkttu** [comment]
데이터베이스 스키마 생성 후에 발생한 문제라서 직접 아이디와 비번을 넣고 heidisql에서 로그인해보면 잘 됩니다. 혹시 놓친 부분이 있는지 매뉴얼을 다시 검토해보겠습니다.

그리고 연결 문제와 별개로 설정 파일 인식 문제는 무엇이 원인인지 궁금합니다.

**Comment by rkttu** [comment]
설명을 좀 더 하면 케이스 a에서 무슨 값을 넣든 계속 yona@localhost에 yonadan으로 접속을 시도합니다.

**Comment by rkttu** [comment]
그렇게해서 접속이 되게끔 설정을 해도 too many connection 오류가 나는 상황입니다. 이 때는 비번이 틀렸다고 나오진 않습니다.

**Comment by doortts** [comment]
@rkttu 아. 이야기 주신 부분을 보니 YONA_DATA 환경변수가 제대로 인식되지 않아서 발생하는 문제일 수 있겠다는 생각이 들었습니다.

![image](https://cloud.githubusercontent.com/assets/520523/25011044/f1481a7e-20a6-11e7-9296-7228b148975b.png)

상세 링크:
[Windows의 경우](https://github.com/yona-projects/yona/blob/master/docs/ko/yona-run-options.md#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0) 부분을 한 번 봐주세요.

**Comment by rkttu** [comment]
시행착오 끝에 다음과 같이 진행하여 정상 작동하는 것을 확인했습니다. 처음 설치하는 사용자들을 위한 정리된 통합 매뉴얼을 만들어 블로그 포스팅을 하려고 합니다.

a. 접속 후에 오류 메시지가 나타나는 것이 아니라, 일정 시간 후에 오류 메시지가 발생한다는 것을 다시 확인하였습니다. 사양이 낮은 구형 넷북에서의 테스트였습니다.
b. 비밀 번호가 틀렸다는 오류 메시지가 나타난 후 생성되는 conf 디렉터리를 bin 폴더 상위의 data 디렉터리 아래로 옮기고, 아래와 같이 별도의 yona.cmd 스크립트 파일을 생성하였습니다.

```
@echo off
pushd "%~dp0"

set YONA_DATA="%~dp0data"
set JAVA_OPTS=-DapplyEvolutions.default=true -Xmx2048m -Xms2048m
call .\bin\yona.bat

popd
@echo on
```

데이터베이스 스키마 버져닝 동작이 자동으로 일어나는 것이 아니므로 최초 설치시에는 -DapplyEvolutions.default=true가 반드시 포함되어있어야 하는 것 같습니다. 가이드를 만든다면, 처음에는 yona 설치 디렉터리로 와서,

```
set YONA_DATA="%~dp0data"
set JAVA_OPTS=-DapplyEvolutions.default=true
.\bin\yona.bat
```

위의 순서대로 명령어를 실행하여 관리자 비번 설정 후 Ctrl + C를 눌러 서버를 종료한다. 로 설명을 하는 것이 필요할 것 같습니다. (테스트는 해봐야 겠습니다.)

그 외에는 말씀해주신 대로 서버 성능 개선, Windows에 한정적인 주의 사항 들이 모두 맞으며, 제가 일부 놓친 부분도 있었습니다.

친절한 안내 감사드립니다. 많이 사용해보고 커뮤니티에 전파하겠습니다. :-)

**Comment by doortts** [comment]
@rkttu 고생많으셨어요. 
사실 Windows 환경이 사용자가 많음에도 불구하고 서버로 운영하기 위한 구성이나 운영에 대해서는 상대적으로 자료나 경험공유가 적은 것 같습니다. 당장 저만 하더라도 windows 쪽은 경험이 적거든요. 
이야기 주신대로 @rkttu 님께서 시간들여서 작업하신 내용이 다른 분들에게도 도움되고 시간을 줄여주는데 도움이 되면 좋겠습니다. 

참고로 
```
set YONA_DATA="%~dp0data"
```
이 부분은 현재 위치를 YONA_DATA로 지정하는 것으로 알고 있는데요 
용이한 업그레이드를 위해서 파일 데이터와 설정, 로그등이 저장되는 YONA_DATA는 다른 곳에 독립적으로 위치시키는 것을 더 권해드리고 싶습니다.

그럼 편안한 밤 되세요! : )

**Comment by doortts** [comment]
@rkttu 아참! 그리고 yona.bat 파일 154번째 줄을 보시면 YONA_DATA가 환경변수로 지정된 경우 DapplyEvolutions 옵션은 따로 지정하지 않으셔도 설정되게 되어 있습니다.

```
if NOT "%YONA_DATA%" == "" set "YONA_OPTS=-DapplyEvolutions.default=true -Duser.dir=%YONA_HOME% - ... ...
```

**Comment by rkttu** [comment]
@doortts 고맙습니다. 이슈는 closing 해주셔도 될 것 같습니다. :-)

**Comment by doortts** [comment]
![image](https://cloud.githubusercontent.com/assets/520523/25013116/6ef215dc-20ad-11e7-800b-03659d334a48.png)
이야기 주신 두 내용도 상식적인 수준에서 당연히 지원되어야 하는 내용이 맞는것 같습니다.

특히 설정파일이 정확히 지정되지 않아 fallback 일어나는 부분은 사소한 실수로도 발생할 수 있는 부분이고 혼란을 주기 쉬운 부분이라는 생각이 들었습니다. 

혹시 https://github.com/yona-projects/yona-install 프로젝트에 쉘 스크립트나 기타 방법으로 도움을 주실수 있으실까요?
