### ISSUE TITLE
[문의] 1.5.1 업그레이드 문제점

### ISSUE THREAD

**Issue by berryzed** [yona-projects/yona#219]
v1.4.1을 사용중에 1.5.1로 업그레이드 하기 위하여 Wiki에 나와있는 방법대로
중지하고 압축해제 후 윈도우 환경이라 기본적으로 환경변수에 YONA_DATA가 들어가있는 상태입니다.

1.5.1의 bin\yona.bat을 실행하면
```
2017-05-11 15:59:27,709 - [INFO] - from play in main 
database [default] connected at jdbc:mysql://127.0.0.1:3307/yona

2017-05-11 15:59:31,058 - [INFO] - from play in main 
Starting application default Akka system.

2017-05-11 15:59:31,121 - [WARN] - from application in main 
A user service was already registered - replacing the old one (service.YonaUserServicePlugin) with the new one (service.YonaUserServicePlugin), however this might hint to a configuration problem if this is a production environment.

2017-05-11 15:59:31,123 - [DEBUG] - from application in main 
Registered AuthProvider 'google'

2017-05-11 15:59:31,125 - [WARN] - from application in main 
There are multiple AuthProviders registered for key 'google'

2017-05-11 15:59:31,126 - [DEBUG] - from application in main 
Registered AuthProvider 'google'

2017-05-11 15:59:31,129 - [DEBUG] - from application in main 
Registered AuthProvider 'github'

2017-05-11 15:59:31,130 - [WARN] - from application in main 
There are multiple AuthProviders registered for key 'github'

2017-05-11 15:59:31,130 - [DEBUG] - from application in main 
Registered AuthProvider 'github'

2017-05-11 15:59:31,138 - [INFO] - from play in main 
Application started (Prod)

2017-05-11 15:59:31,138 - [INFO] - from application in application-akka.actor.default-dispatcher-3 
User uploaded temporary files are cleaned up...(0 of 0)

2017-05-11 15:59:31,395 - [INFO] - from play in main 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```
위와 같은 내용이 나오고 관리자 계정으로 접속하여 업데이트를 확인하면 계속 1.4.1 버전으로 나타나게 됩니다.
제가 혹시 빠트린 부분이 있는지 알고 싶습니다 ㅠㅠ

**Comment by doortts** [comment]
특별히 문제도 없고 빠뜨린 부분도 없는것 같은데요 혹시 이슈 목록에서 아래 같은 two-column-mode 아이콘이 보이시나요?
![image](https://cloud.githubusercontent.com/assets/520523/25941308/ea316c1c-3673-11e7-9c19-b5b35f80fee4.png)

그리고 실행하신 명령어 로그를  앞뒤로 공유해주시겠어요?
커맨드라인으로 하셨으면 스샷으로 첨부해주셔도 좋을 것 같구요.

**Comment by berryzed** [comment]
@doortts two-column-mode아이콘은 보이지 않습니다.
![image](https://cloud.githubusercontent.com/assets/6817393/25978201/d43185d6-36fb-11e7-9f12-af044793fe62.png)

**Comment by doortts** [comment]
c:\yona 
아래에 있는 폴더 이름들을 볼 수 있을까요?
yona-1.5.1 은 있으신것 같고 그 외 어떤 폴더가 있나요?
그리고 나머지 폴더를 한 번 옮겨놓고 실행해 보시겠어요? 어떤 에러가 나는지 보게요.

**Comment by berryzed** [comment]
```
2017-05-12  오전 10:10    <DIR>          .
2017-05-12  오전 10:10    <DIR>          ..
2017-03-24  오전 11:09    <DIR>          bin
2017-03-09  오후 06:06    <DIR>          data
2017-05-11  오후 03:45    <DIR>          lib
2017-03-15  오후 06:44    <DIR>          MariaDB
2017-03-23  오후 02:32             6,358 README.md
2017-05-12  오전 10:10                 4 RUNNING_PID
2017-03-16  오후 05:15    <DIR>          ServerPC-Yona.hbk
2017-03-24  오전 11:09    <DIR>          share
2017-05-12  오전 10:10               221 start.bat
2017-05-11  오후 04:11    <DIR>          yona-1.5.0
2017-05-11  오후 03:38    <DIR>          yona-1.5.1
               3개 파일               6,583 바이트
              10개 디렉터리  459,811,790,848 바이트 남음
```
현재 위 bin 폴더는 1.4.1버전이고 1.5.1버전의 bin 및 lib폴더를 덮어써도 같은 상황입니다ㅠㅠ

**Comment by doortts** [comment]
아.. 이런 구조시라면 덮어띄우지 마시고 명시적으로 bin, lib 폴더를 지우신다음에 yona-1.5.1 의 bin, lib 폴더를 복사해서 실행해주시겠어요?

**Comment by berryzed** [comment]
@doortts 와...말씀하신대로 하니깐 버전이 바로 변경이 되었네요! 다만...ㅠㅠ
게시판에 있는 특정 1개의 파일에서만 아래와 같은 오류가 나타납니다.
```
[error] play - Cannot invoke the action, eventually got an error: java.io.FileNotFoundException: c:\yona\data\uploads\0de0287c405d25b958fb6138603f87ba024e4148fd7b3ca273929e87e2652a5e (액세스가 거부되었습니다)
[error] application -

! @742p7bd92 - Internal server error, for (GET) [/files/61] ->

play.api.Application$$anon$1: Execution exception[[FileNotFoundException: c:\yona\data\uploads\0de0287c405d25b958fb6138603f87ba024e4148fd7b3ca273929e87e2652a5e (액세스가 거부되었습니다)]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.io.FileNotFoundException: c:\yona\data\uploads\0de0287c405d25b958fb6138603f87ba024e4148fd7b3ca273929e87e2652a5e (액세스가 거부되었습니다)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_131]
        at java.io.FileInputStream.open(Unknown Source) ~[na:1.8.0_131]
        at java.io.FileInputStream.<init>(Unknown Source) ~[na:1.8.0_131]
        at play.api.libs.iteratee.Enumerator$.fromFile(Enumerator.scala:582) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Results$Status.sendFile(Results.scala:378) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
[info] a./files/61 - 61.247.78.19 - - [15/May/2017:16:55:59 +0900] "GET /files/61 HTTP/1.1" 500 - "http://도메인/post/10" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" -
[info] a./messages.js - 61.247.78.19 - rimi [15/May/2017:16:55:59 +0900] "GET /messages.js HTTP/1.1" 200 - "http://도메인/files/61" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 5ms
[info] a./user/usermenuTabContentList - 61.247.78.19 - rimi [15/May/2017:16:56:00 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "http://도메인/files/61" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 57ms
```
위 액세스 파일을 또 uploads 폴더에서 찾아보면 파일은 존재합니다 ㅠㅠ
너무 괴롭혀서 죄송합니다...

**Comment by doortts** [comment]
@berryzed 오류 메시지 자체는 권한이 없는걸로 나옵니다. 혹시 yona를 실행시킨 유저가 바뀌었나요?

**Comment by berryzed** [comment]
@doortts 이상하게 서버 재실행했더니 정상적으로 동작합니다 감사합니다~~!!
