### ISSUE TITLE
윈도우 서버에서 yona 여러개 돌리기

### ISSUE THREAD

**Issue by lotiony** [yona-projects/yona#223]
안녕하세요? 
이부분은 이슈에 등록하는게 맞을 것 같아서 여기에 남깁니다.

현재 WIndows Server 2012 r2 서버에서  yona 1.0.4 + mariaDB 설치로 잘 사용중입니다.
http://도메인:9000/ 으로 사용중인데요,

이 서버에서 yona 프로세스를 몇개 더 돌려 호스팅을 해주고자 했습니다.
기본적인 생각으로는 yona를 현재 서비스중이 아닌 각각 다른 폴더에 복사본으로 만들어두고
윈도 커맨드 콘솔을 따로 띄워 실행하면 독립형이니 별 문제가 없겠다 싶었습니다.

제 서버에 요나를 몇개 돌리면서 (가볍게)  호스팅 해 줄 목적이었기 때문에 H2DB 1.5.1버전을 사용하는걸로 결정했구요
기존 c:\yona 폴더 내에 service 폴더 만들고 그안에 service id별로 폴더를 만들어 두었습니다.
![image](https://cloud.githubusercontent.com/assets/16128718/26273618/56aeac5a-3d6e-11e7-9c02-8e00b6399bc5.png)

그리고 각각 다른 포트로 서비스url을 주기 위해서 bat파일을 만들어 아래처럼 설정하였구요
@echo off
c:
cd c:\yona\service\kys
del RUNNING_PID
SET YONA_DATA=c:\yona\service\kys\yona_data
SET JAVA_OPTIONS=-Dhttp.port=9001
bin\yona.bat

이 bat 실행 전에 각각의 폴더에서 bin\yona.bat을 실행시켜서 conf파일을 만들고 yona_data로 옮겨두었습니다.
이렇게 하고 각각 콘솔을 열어서 yona를 돌려주면  되지 않을까? 라고 생각하고 윈도우 시작에 서비스로 등록을 해서 재부팅시 자동으로 올라오도록 세팅하려고 했습니다.
그런데 yona_start_kys.bat 실행시 요나가 정상 러닝이 안 되네요.

C:\yona\service>yona_start_kys.bat
c:\yona\service\kys\RUNNING_PID을(를) 찾을 수 없습니다.
Play server process ID is 9392
[info] play - database [default] connected at jdbc:h2:file:./yona
[info] play - Starting application default Akka system.
[debug] application - Registered AuthProvider 'google'
[debug] application - Registered AuthProvider 'github'
[info] play - Application started (Prod)
[info] application - User uploaded temporary files are cleaned up...(0 of 0)
Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:138)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:135)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer.<init>(NettyServer.scala:135)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:252)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

일단 SET JAVA_OPT 에서 설정한 포트가 안먹히는건지? 0.0.0.0:9000에 바인딩  실패가 뜨는것 같아서
application.conf 파일을 뒤져보다가

# Components used to construct the URL to this application.
application.scheme="http"
application.hostname="www.yourdomain.com"
application.port="8080"

이 부분에서 hostname과 port 주석처리를 제거하고 다시 실행해 보았으나 위와 동일한 메시지가 나와서, 이 옵션이 먹힌건지 아닌지를 확인하지 못하겠더라구요.

리눅스에서는 docker로 여러개 돌릴수 있을것 같은데 혹시 설계상 windows OS 위에서 여러 instance를 돌리는것을 염두에 두고 개발된게 아니어서 원래 안되는 것인지,
아니면 방법상에 문제가 있는지 확인을 좀 부탁드리겠습니다.

그리고 이왕이면 JAVA_OPTION을 설정하기보다는 위 conf파일에서처럼 사용 포트나 도메인을 직접 셋팅해 사용할 수 있으면 좋겠네요 ㅎ (원래 그렇게 쓰려고 만들어진 옵션이려나요?)

감사합니다.

**Comment by lotiony** [comment]
하~~ 자문자답입니다.
bat파일을 잘못 만들었네요!
SET JAVA_OPTIONS=-Dhttp.port=9001 가 아니고
SET JAVA_OPTS=-Dhttp.port=9001 였습니다!!

정상 되네요~_~

**Comment by lotiony** [comment]
위키에 [사용 포트 변경하기](https://github.com/yona-projects/yona/wiki/%EC%82%AC%EC%9A%A9-%ED%8F%AC%ED%8A%B8-%EB%B3%80%EA%B2%BD%ED%95%98%EA%B8%B0) 문서에 Windows 부분이 좀 헷갈리게 되어있는데

실제 커맨드라인에서 입력하는것처럼 
SET JAVA_OPTS=-Dhttp.port=9001
bin\yona.bat 
으로 수정되면 좋을것 같습니다

**Comment by doortts** [comment]
@lotiony 멤버 초대 및 wiki 수정 권한 드렸어요!  : ) 하하하~

**Comment by doortts** [comment]
그리고 이미 MariaDB가 설치되어 있다면 create database 명령으로 DB를 각각 만들고 각 인스턴스별로 접속 스키마(schema)만 다르게 해서 운영하는건 어떠세요?

**Comment by lotiony** [comment]
@doortts 감사합니다!  위키는 수정해 두었습니다.
mariadb에 디비 생성하는것도 생각은 해보았는데 그냥 로컬버전인것이 나을것 같다고 결론지었습니다.
저희 실제 서비스 디비에  테스트용?은 아니지만 개인적인(사적인) 서비스를 몇개 올리기도 좀 뭣하고 ㅎ

**Comment by doortts** [comment]
@lotiony 직접 위키도 수정해주시고, 먼저 쓰신 시간으로 얻은 내용, 다른 분들은 절약할 수 있게 도움주셔서 고맙습니다!
