### ISSUE TITLE
요나 실행시  Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server] 오류 발생

### ISSUE THREAD

**Issue by Gojhon** [yona-projects/yona#230]
Oops, cannot start the server.
Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.Configuration.reportError(Configuration.java:310)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:81)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/CodeComment.setAuthor(Lmodels/User;)V @2: invokevirtual
  Reason:
    Type 'models/User' (current frame, stack[1]) is not assignable to 'models/CodeComment'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'models/CodeComment', 'models/User' }
    stack: { 'models/CodeComment', 'models/User' }
  Bytecode:
    0x0000000: 2a2b b600 4db6 0051 2a2b b400 56b6 005a
    0x0000010: 2a2b b400 5db6 0060 b1                 

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79)

**Comment by doortts** [comment]
@Gojhon 사용하시는 Java 버전과 MariaDB 를 사용하신다면 버전이 어떻게 되세요?

**Comment by Gojhon** [comment]
@doortts  사용하는 자바는 1.8.0_121 버전을 사용하고요.  mysql ver 15.1 Distrib 5.5.39 MariaDB 라고 되어있습니다.

**Comment by Gojhon** [comment]
@doortts  업데이트를 해햐나나요?

**Comment by Gojhon** [comment]
@doortts 자바와 마리아 DB를 업데이트 하면 가능한가요?

**Comment by doortts** [comment]
@Gojhon 마리아DB 버전을 업데이트 해봐주시겠어요? 그리고 설치 OS는 어떻게 되세요?

**Comment by Gojhon** [comment]
cetos6.8입니다.

**Comment by doortts** [comment]
@Gojhon 문제 해결되셨어요?

**Comment by Gojhon** [comment]
@doortts  업데이트 중입니다. 업데이트를 안한 서버라 느리네요.

**Comment by Gojhon** [comment]
@doortts  똑같은 오류가 발생됩니다.

**Comment by doortts** [comment]
@Gojhon 음. 그럼 우선 java -version 결과와  mysql --version 결과 화면을 복사해서 붙여주시겠어요?

**Comment by Gojhon** [comment]
Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.Configuration.reportError(Configuration.java:310)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:81)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/CodeComment.setAuthor(Lmodels/User;)V @2: invokevirtual
  Reason:
    Type 'models/User' (current frame, stack[1]) is not assignable to 'models/CodeComment'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'models/CodeComment', 'models/User' }
    stack: { 'models/CodeComment', 'models/User' }
  Bytecode:
    0x0000000: 2a2b b600 4db6 0051 2a2b b400 56b6 005a
    0x0000010: 2a2b b400 5db6 0060 b1                 

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79)
	... 15 more

**Comment by Gojhon** [comment]
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Gojhon** [comment]
mysql  Ver 15.1 Distrib 5.5.39-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by Gojhon** [comment]
@doortts  올렸습니다.

**Comment by doortts** [comment]
@Gojhon 오라클 JDK로 다시 실행해봐주시겠어요? JDK 문제일 수 도 있어서요
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by Gojhon** [comment]
@doortts  클래스파일이 깨져서 다시 옮겨 졌더니 된다고 하네요.

**Comment by Gojhon** [comment]
@doortts  감사합니다
