### ISSUE TITLE
Javascript 로딩 문제

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#238]
안녕하세요. 처음 설치해서 사용해보려고 하는데,
관리자 계정 생성 뒤 yona 재시작 뒤부터 페이지 로딩은 되는데 javascript 경로를 못찾는 문제가 있어서 문의드립니다. 뭘 확인해야할까요? 

![2017-07-06 12 11 30](https://user-images.githubusercontent.com/7797499/27893968-4be18522-6244-11e7-9efa-4452a8d6661e.png)

[error] application -

! @74hbn57en - Internal server error, for (GET) [/assets/javascripts/common/yona.Usermenu.js] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
Caused by: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625
	at play.utils.Resources$.isUrlConnectionADirectory(Resources.scala:30) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$19.apply(Assets.scala:413) ~[com.typesafe.play.play_2.10-2.3.10.jar:1.5.1]
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$19.apply(Assets.scala:409) ~[com.typesafe.play.play_2.10-2.3.10.jar:1.5.1]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.4.jar:na]
[info] a./.Usermenu.js - 192.168.0.63 - - [06/Jul/2017:11:52:39 +0900] "GET /assets/javascripts/common/yona.Usermenu.js HTTP/1.1" 500 - "http://192.168.0.66:9000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -
[error] application -

! @74hbn57g6 - Internal server error, for (GET) [/favicon.ico] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
Caused by: java.lang.IllegalAccessError: class play.utils.Resources$ (in unnamed module @0x5468625) cannot access class sun.net.www.protocol.file.FileURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.file to unnamed module @0x5468625
	at play.utils.Resources$.isUrlConnectionADirectory(Resources.scala:30) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$19.apply(Assets.scala:413) ~[com.typesafe.play.play_2.10-2.3.10.jar:1.5.1]
	at controllers.AssetsBuilder$$anonfun$at$1$$anonfun$19.apply(Assets.scala:409) ~[com.typesafe.play.play_2.10-2.3.10.jar:1.5.1]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.util.Try$.apply(Try.scala:161) [org.scala-lang.scala-library-2.10.4.jar:na]
[info] a./favicon.ico - 192.168.0.63 - - [06/Jul/2017:11:52:39 +0900] "GET /favicon.ico HTTP/1.1" 500 - "http://192.168.0.66:9000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" -

**Comment by sjstyle** [comment]
운영중인 서버의 자바 버전은 어떻게 되시나요?

**Comment by dinobei** [comment]
Java 9버전입니다. (openjdk-9-jdk) 혹시 버전이 문제가 될 수 있나요?

**Comment by sjstyle** [comment]
네 현재 yona는 자바9환경에서 정상적으로 동작하지 않습니다. 가급적이면 오라클 벤더 자바8을 설치하시면 좋을 것 같습니다.

**Comment by dinobei** [comment]
감사합니다. 오라클 벤더의 자바8을 설치하여 해결했습니다.
