### ISSUE TITLE
@6pg164f2g: Cannot init the Global object 에러 발생

### ISSUE THREAD

**Issue by achim1124** [yona-projects/yona#24]
서버 환경은 다음과 같습니다.
OS : Windows 2008 Std 64bit
JAVA : 1.8.0_73
E:\yona-1.0.0\bin>java -version
**java version "1.8.0_73"**
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

yona 배포버젼을 하기 경로에 다운 받아 yona.bat를 실행하면 에러가 발생 되는데 원인을 모르겠네요.

**E:\yona-1.0.0\bin>yona.bat**
Play server process ID is 6828
Oops, cannot start the server.
@6pg164f2g: Cannot init the Global object
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:59)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:53)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:52)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:402)
        at play.api.WithDefaultGlobal$class.global(Application.scala:68)
        at play.api.DefaultApplication.global(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:82)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.configuration(Application.scala:84)
        at play.api.DefaultApplication.configuration(Application.scala:402)
        at play.api.Application$class.$init$(Application.scala:274)
        at play.api.DefaultApplication.<init>(Application.scala:402)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.UnsupportedClassVersionError: Global : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:31)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:402)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:54)

**Comment by doortts** [comment]
> Caused by: java.lang.UnsupportedClassVersionError: Global : Unsupported major.minor version 52.0

이 부분이 문제를 나타내는 부분인것 같습니다. 

밤에 제가 집에서 64bit 윈도우 + 1.8에서 테스트를 한번 해보고 이야기 드릴게요.
: )

**Comment by doortts** [comment]
@achim1124 windows 8 64bit + java 8에서 정상 실행되는 걸 확인했습니다.
해당 오류는 java 7이 설치된 경우에 발행하는 것 같습니다.

혹시 JAVA_HOME이 1.7로 지정되어 있지는 않은지 확인해 주세요.

그리고 혹시 h2 버전을 쓰신다면
E:\yona-1.0.0 에서
```
bin/yona.bat 
```
으로 실행해 주세요. mariadb 사용하신다면 무관하고요.

**Comment by achim1124** [comment]
그렇네요 java1.7버젼과 1.8버젼 2개가 설치 되어 있어서 발생된 문제 였네요.
1.7을 삭제 하니 정상적으로 실행이 됩니다.
도움 주셔서 감사합니다.^^

한가지더 문의 사항이 있는데요.
db접속은 잘 되는데 하기와 같이 에러가 발생됩니다.ㅜ
도움 주시면 감사하겠습니다.

**E:\yona-1.0.0\bin>yona.bat**
Play server process ID is 5984
[info] play - database [default] connected at jdbc:mysql://localhost:3306/yona
[warn] play - Your production database [default] needs evolutions!
[warn] play - Run with -DapplyEvolutions.default=true if you want to run them automatically (be careful)
....
!생략!
...

Oops, cannot start the server.
**@6pg6ne29i: Database 'default' needs evolution!
        at **play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:508)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)


**# MariaDB DataBase 정보**
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| test               |
| yona               |
+--------------------+
5 rows in set (0.00 sec)

**# yona DB table 목록**
MariaDB [(none)]> SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_S
CHEMA = 'yona';
+-----------------+
| TABLE_NAME      |
+-----------------+
| play_evolutions |
+-----------------+
1 row in set (0.00 sec)

**Comment by doortts** [comment]
@achim1124 혹시 아직 운영이 시작되지 않은 상황이시라면
DB 테이블 play_evolutions를 truncate 시켜보시면 좋을 것 같습니다.
```sql
truncate table play_evolutions;
```

참고로 해당 에러는 무언가의 이유로 sql evolution 스크립트가 정상적으로 작동하지 않았거나 변경되었을때 발생하는 문제입니다.

**Comment by achim1124** [comment]
truncate table play_evolutions; 을 해도 동일해서

drop database yona;를 하고 
다시 설치 해봐도 동일한 에러가 발생 되네요.

혹시 /etc/ 밑에 my.cnf? 파일 하나 만들라고 한거는

windows 서버 환경은 해당 사항 없는거죠?

**Comment by doortts** [comment]
에러메시지가 동일한지 한 번 자세히 봐주세요
```
[warn] play - Your production database [default] needs evolutions!
[warn] play - Run with -DapplyEvolutions.default=true if you want to run them automatically (be careful)
```
처음 적어주셨던 위 메시지는 에러가 아니라 사실은 DB 정합성이 안맞아서 나는 메시지거든요.
그래서 database를 drop 하셨으면 나지 않아야 하거든요. (나기도 어렵고.)

**Comment by achim1124** [comment]
네 하기와 같이 동일 하네요... 바쁘실텐데 계속 귀찮게 해드리네요..ㅜ

alter table recent_project add constraint fk_recent_project_project_2 foreign key (project_id) references project (id) on delete CASCADE on update CASCADE;

[warn] **play - Run with -DapplyEvolutions.default=true if you want to run them automatically (be careful)**
Oops, cannot start the server.
@6phh035nj: Database 'default' needs evolution!
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:508)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
잘 안되셔서 답답하실 분 보다야 낫죠. ㅎ

실행 스크립트에 
```
-DapplyEvolutions.default=true 
```
항목을 한번 추가해 보죠.

아래링크
https://github.com/yona-projects/yona/pull/16/commits/92683fad4fad96814b6fe9311c2319d2df36f3ce

보시고 bin 디렉터리의 yona.bat 파일 해당 라인을 한번 수정해 봐 주시겠어요?

**Comment by achim1124** [comment]
yona.bat 파일인데 알려주신 라인이 안보이는데 어디에 추가 해야 될까요?

@REM yona launcher script
@REM
@REM Environment:
@REM JAVA_HOME - location of a JDK home dir (optional if java on path)
@REM CFG_OPTS  - JVM options (optional)
@REM Configuration:
@REM YONA_config.txt found in the YONA_HOME.
@setlocal enabledelayedexpansion

@echo off
if "%YONA_HOME%"=="" set "YONA_HOME=%~dp0\\.."
set ERROR_CODE=0

set "APP_LIB_DIR=%YONA_HOME%\lib\"

rem Detect if we were double clicked, although theoretically A user could
rem manually run cmd /c
for %%x in (%cmdcmdline%) do if %%~x==/c set DOUBLECLICKED=1

rem FIRST we load the config file of extra options.
set "CFG_FILE=%YONA_HOME%\YONA_config.txt"
set CFG_OPTS=
if exist %CFG_FILE% (
  FOR /F "tokens=* eol=# usebackq delims=" %%i IN ("%CFG_FILE%") DO (
    set DO_NOT_REUSE_ME=%%i
    rem ZOMG (Part #2) WE use !! here to delay the expansion of
    rem CFG_OPTS, otherwise it remains "" for this loop.
    set CFG_OPTS=!CFG_OPTS! !DO_NOT_REUSE_ME!
  )
)

rem We use the value of the JAVACMD environment variable if defined
set _JAVACMD=%JAVACMD%

if "%_JAVACMD%"=="" (
  if not "%JAVA_HOME%"=="" (
    if exist "%JAVA_HOME%\bin\java.exe" set "_JAVACMD=%JAVA_HOME%\bin\java.exe"
  )
)

if "%_JAVACMD%"=="" set _JAVACMD=java

rem Detect if this java is ok to use.
for /F %%j in ('"%_JAVACMD%" -version  2^>^&1') do (
  if %%~j==Java set JAVAINSTALLED=1
)

rem BAT has no logical or, so we do it OLD SCHOOL! Oppan Redmond Style
set JAVAOK=true
if not defined JAVAINSTALLED set JAVAOK=false

if "%JAVAOK%"=="false" (
  echo.
  echo A Java JDK is not installed or can't be found.
  if not "%JAVA_HOME%"=="" (
    echo JAVA_HOME = "%JAVA_HOME%"
  )
  echo.
  echo Please go to
  echo   http://www.oracle.com/technetwork/java/javase/downloads/index.html
  echo and download a valid Java JDK and install before running yona.
  echo.
  echo If you think this message is in error, please check
  echo your environment variables to see if "java.exe" and "javac.exe" are
  echo available via JAVA_HOME or PATH.
  echo.
  if defined DOUBLECLICKED pause
  exit /B 1
)


rem We use the value of the JAVA_OPTS environment variable if defined, rather than the config.
set _JAVA_OPTS=%JAVA_OPTS%
if "%_JAVA_OPTS%"=="" set _JAVA_OPTS=%CFG_OPTS%

rem We keep in _JAVA_PARAMS all -J-prefixed and -D-prefixed arguments
rem "-J" is stripped, "-D" is left as is, and everything is appended to JAVA_OPTS
set _JAVA_PARAMS=

:param_beforeloop
if [%1]==[] goto param_afterloop
set _TEST_PARAM=%~1

rem ignore arguments that do not start with '-'
if not "%_TEST_PARAM:~0,1%"=="-" (
  shift
  goto param_beforeloop
)

set _TEST_PARAM=%~1
if "%_TEST_PARAM:~0,2%"=="-J" (
  rem strip -J prefix
  set _TEST_PARAM=%_TEST_PARAM:~2%
)

if "%_TEST_PARAM:~0,2%"=="-D" (
  rem test if this was double-quoted property "-Dprop=42"
  for /F "delims== tokens=1-2" %%G in ("%_TEST_PARAM%") DO (
    if not "%%G" == "%_TEST_PARAM%" (
      rem double quoted: "-Dprop=42" -> -Dprop="42"
      set _JAVA_PARAMS=%%G="%%H"
    ) else if [%2] neq [] (
      rem it was a normal property: -Dprop=42 or -Drop="42"
      set _JAVA_PARAMS=%_TEST_PARAM%=%2
      shift
    )
  )
) else (
  rem a JVM property, we just append it
  set _JAVA_PARAMS=%_TEST_PARAM%
)

:param_loop
shift

if [%1]==[] goto param_afterloop
set _TEST_PARAM=%~1

rem ignore arguments that do not start with '-'
if not "%_TEST_PARAM:~0,1%"=="-" goto param_loop

set _TEST_PARAM=%~1
if "%_TEST_PARAM:~0,2%"=="-J" (
  rem strip -J prefix
  set _TEST_PARAM=%_TEST_PARAM:~2%
)

if "%_TEST_PARAM:~0,2%"=="-D" (
  rem test if this was double-quoted property "-Dprop=42"
  for /F "delims== tokens=1-2" %%G in ("%_TEST_PARAM%") DO (
    if not "%%G" == "%_TEST_PARAM%" (
      rem double quoted: "-Dprop=42" -> -Dprop="42"
      set _JAVA_PARAMS=%_JAVA_PARAMS% %%G="%%H"
    ) else if [%2] neq [] (
      rem it was a normal property: -Dprop=42 or -Drop="42"
      set _JAVA_PARAMS=%_JAVA_PARAMS% %_TEST_PARAM%=%2
      shift
    )
  )
) else (
  rem a JVM property, we just append it
  set _JAVA_PARAMS=%_JAVA_PARAMS% %_TEST_PARAM%
)
goto param_loop
:param_afterloop

set _JAVA_OPTS=%_JAVA_OPTS% %_JAVA_PARAMS%
:run
 
set "APP_CLASSPATH=%APP_LIB_DIR%\yona.yona-1.0.0.jar;%APP_LIB_DIR%\js-engine.jar;%APP_LIB_DIR%\org.scala-lang.scala-library-2.10.4.jar;%APP_LIB_DIR%\com.typesafe.play.twirl-api_2.10-1.0.3.jar;%APP_LIB_DIR%\org.apache.commons.commons-lang3-3.1.jar;%APP_LIB_DIR%\com.typesafe.play.play_2.10-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.build-link-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.play-exceptions-2.3.6.jar;%APP_LIB_DIR%\org.javassist.javassist-3.18.2-GA.jar;%APP_LIB_DIR%\com.typesafe.play.play-iteratees_2.10-2.3.6.jar;%APP_LIB_DIR%\org.scala-stm.scala-stm_2.10-0.7.jar;%APP_LIB_DIR%\com.typesafe.config-1.2.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-json_2.10-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.play-functional_2.10-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.play-datacommons_2.10-2.3.6.jar;%APP_LIB_DIR%\joda-time.joda-time-2.3.jar;%APP_LIB_DIR%\org.joda.joda-convert-1.6.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-annotations-2.3.2.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-core-2.3.2.jar;%APP_LIB_DIR%\com.fasterxml.jackson.core.jackson-databind-2.3.2.jar;%APP_LIB_DIR%\org.scala-lang.scala-reflect-2.10.4.jar;%APP_LIB_DIR%\io.netty.netty-3.9.3.Final.jar;%APP_LIB_DIR%\com.typesafe.netty.netty-http-pipelining-1.1.2.jar;%APP_LIB_DIR%\org.slf4j.slf4j-api-1.7.6.jar;%APP_LIB_DIR%\org.slf4j.jul-to-slf4j-1.7.6.jar;%APP_LIB_DIR%\org.slf4j.jcl-over-slf4j-1.7.6.jar;%APP_LIB_DIR%\ch.qos.logback.logback-core-1.1.1.jar;%APP_LIB_DIR%\ch.qos.logback.logback-classic-1.1.1.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-actor_2.10-2.3.4.jar;%APP_LIB_DIR%\com.typesafe.akka.akka-slf4j_2.10-2.3.4.jar;%APP_LIB_DIR%\commons-codec.commons-codec-1.9.jar;%APP_LIB_DIR%\xerces.xercesImpl-2.11.0.jar;%APP_LIB_DIR%\xml-apis.xml-apis-1.4.01.jar;%APP_LIB_DIR%\javax.transaction.jta-1.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-java_2.10-2.3.6.jar;%APP_LIB_DIR%\org.yaml.snakeyaml-1.13.jar;%APP_LIB_DIR%\org.hibernate.hibernate-validator-5.0.3.Final.jar;%APP_LIB_DIR%\javax.validation.validation-api-1.1.0.Final.jar;%APP_LIB_DIR%\org.jboss.logging.jboss-logging-3.1.1.GA.jar;%APP_LIB_DIR%\com.fasterxml.classmate-1.0.0.jar;%APP_LIB_DIR%\org.springframework.spring-context-4.0.3.RELEASE.jar;%APP_LIB_DIR%\org.reflections.reflections-0.9.8.jar;%APP_LIB_DIR%\com.google.guava.guava-19.0.jar;%APP_LIB_DIR%\dom4j.dom4j-1.6.1.jar;%APP_LIB_DIR%\com.google.code.findbugs.jsr305-2.0.3.jar;%APP_LIB_DIR%\org.apache.tomcat.tomcat-servlet-api-8.0.5.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-jdbc_2.10-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.play-jdbc_2.10-2.3.6.jar;%APP_LIB_DIR%\com.jolbox.bonecp-0.8.0.RELEASE.jar;%APP_LIB_DIR%\com.h2database.h2-1.3.176.jar;%APP_LIB_DIR%\tyrex.tyrex-1.0.1.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-ebean_2.10-2.3.6.jar;%APP_LIB_DIR%\org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar;%APP_LIB_DIR%\org.avaje.ebeanorm.avaje-ebeanorm-agent-3.2.2.jar;%APP_LIB_DIR%\org.hibernate.javax.persistence.hibernate-jpa-2.0-api-1.0.1.Final.jar;%APP_LIB_DIR%\com.typesafe.play.play-java-ws_2.10-2.3.6.jar;%APP_LIB_DIR%\com.typesafe.play.play-ws_2.10-2.3.6.jar;%APP_LIB_DIR%\com.ning.async-http-client-1.8.14.jar;%APP_LIB_DIR%\oauth.signpost.signpost-core-1.2.1.2.jar;%APP_LIB_DIR%\oauth.signpost.signpost-commonshttp4-1.2.1.2.jar;%APP_LIB_DIR%\com.typesafe.play.play-cache_2.10-2.3.6.jar;%APP_LIB_DIR%\net.sf.ehcache.ehcache-core-2.6.8.jar;%APP_LIB_DIR%\org.mariadb.jdbc.mariadb-java-client-1.3.6.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit-3.5.3.201412180710-r.jar;%APP_LIB_DIR%\com.jcraft.jsch-0.1.50.jar;%APP_LIB_DIR%\com.googlecode.javaewah.JavaEWAH-0.7.9.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpclient-4.1.3.jar;%APP_LIB_DIR%\org.apache.httpcomponents.httpcore-4.1.4.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit.http.server-3.5.3.201412180710-r.jar;%APP_LIB_DIR%\org.eclipse.jgit.org.eclipse.jgit.java7-3.5.3.201412180710-r.jar;%APP_LIB_DIR%\sonia.svnkit.svnkit-1.8.5-scm2.jar;%APP_LIB_DIR%\net.java.dev.jna.jna-3.5.2.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.svnkit-trilead-ssh2-0.0.7.jar;%APP_LIB_DIR%\com.trilead.trilead-ssh2-1.0.0-build217.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.core-0.0.7.jar;%APP_LIB_DIR%\de.regnis.q.sequence.sequence-library-1.0.2.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.connector-factory-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.usocket-jna-0.0.7.jar;%APP_LIB_DIR%\net.java.dev.jna.platform-3.5.2.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.usocket-nc-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.sshagent-0.0.7.jar;%APP_LIB_DIR%\com.jcraft.jsch.agentproxy.pageant-0.0.7.jar;%APP_LIB_DIR%\org.tmatesoft.sqljet.sqljet-1.1.10.jar;%APP_LIB_DIR%\org.antlr.antlr-runtime-3.4.jar;%APP_LIB_DIR%\sonia.svnkit.svnkit-dav-1.8.5-scm2.jar;%APP_LIB_DIR%\sonia.svnkit.svnkit-javahl16-1.8.5-scm2.jar;%APP_LIB_DIR%\org.apache.subversion.svn-javahl-api-1.8.1.jar;%APP_LIB_DIR%\net.sourceforge.jexcelapi.jxl-2.6.10.jar;%APP_LIB_DIR%\log4j.log4j-1.2.14.jar;%APP_LIB_DIR%\org.apache.shiro.shiro-core-1.2.1.jar;%APP_LIB_DIR%\commons-beanutils.commons-beanutils-1.8.3.jar;%APP_LIB_DIR%\info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar;%APP_LIB_DIR%\org.apache.commons.commons-email-1.3.1.jar;%APP_LIB_DIR%\javax.mail.mail-1.4.5.jar;%APP_LIB_DIR%\javax.activation.activation-1.1.1.jar;%APP_LIB_DIR%\commons-lang.commons-lang-2.6.jar;%APP_LIB_DIR%\org.apache.tika.tika-core-1.2.jar;%APP_LIB_DIR%\commons-io.commons-io-2.4.jar;%APP_LIB_DIR%\org.julienrf.play-jsmessages_2.10-1.6.2.jar;%APP_LIB_DIR%\commons-collections.commons-collections-3.2.1.jar;%APP_LIB_DIR%\org.jsoup.jsoup-1.8.3.jar;%APP_LIB_DIR%\com.googlecode.juniversalchardet.juniversalchardet-1.0.3.jar;%APP_LIB_DIR%\com.github.zafarkhaja.java-semver-0.7.2.jar;%APP_LIB_DIR%\com.googlecode.htmlcompressor.htmlcompressor-1.4.jar;%APP_LIB_DIR%\org.springframework.spring-jdbc-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.springframework.spring-beans-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.springframework.spring-core-4.1.5.RELEASE.jar;%APP_LIB_DIR%\commons-logging.commons-logging-1.2.jar;%APP_LIB_DIR%\org.springframework.spring-tx-4.1.5.RELEASE.jar;%APP_LIB_DIR%\org.mozilla.rhino-1.7.7.1.jar;%APP_LIB_DIR%\yona.yona-1.0.0-assets.jar"
set "APP_MAIN_CLASS=play.core.server.NettyServer"

rem Call the application and pass all arguments unchanged.
"%_JAVACMD%" %_JAVA_OPTS% %YONA_OPTS% -cp "%APP_CLASSPATH%" %APP_MAIN_CLASS% %*
if ERRORLEVEL 1 goto error
goto end

:error
set ERROR_CODE=1

:end

@endlocal

exit /B %ERROR_CODE%

**Comment by doortts** [comment]
```
rem We use the value of the JAVA_OPTS environment variable if defined, rather than the config.
set _JAVA_OPTS=%JAVA_OPTS%
```
이 부분을 아래처럼 고쳐봐주세요
약 58번째 줄 근처인것 같습니다.

```
rem We use the value of the JAVA_OPTS environment variable if defined, rather than the config.
if "%JAVA_OPTS%"=="" SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=%YONA_HOME%\conf\application.conf -Dlogger.file=%YONA_HOME%\conf\application-logger.xml -DapplyEvolutions.default=true
set _JAVA_OPTS=%JAVA_OPTS%
```

**Comment by achim1124** [comment]
**YONA 설치 경로 : E:\yona-1.0.0\bin**

if "%JAVA_OPTS%"=="" SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=**%YONA_HOME%**\conf\application.conf -Dlogger.file=**%YONA_HOME%**\conf\application-logger.xml -DapplyEvolutions.default=true

위와  항목을 yona.bat에 추가 하여 실행 하였더니 아래와 같은 Error 발생 되네요.

▷Error 로그
Oops, cannot start the server.
Configuration error: Configuration error[E:\yona-1.0.0\bin\..\conf\application.conf: java.io.FileNotFoundException: E:\yona-1.0.0\bin\..\conf\application.conf


아마 YONA_HOME 경로가  E:\yona-1.0.0\bin\.. 이런식으로 되있어서  발생 되는거 같은데요.

아래와 같이 풀경로를 주고 실행 하니깐 정상적으로 올라 오네요.
일단 편법으로 실행이 되긴 했는데 YONA_HOME 경로 지정이 제대로 안되는건지... 
이대로 운영해도 문제 없을까요?
if "%JAVA_OPTS%"=="" SET JAVA_OPTS=-Dyona.home=%YONA_HOME% -Dconfig.file=E:\yona-1.0.0\bin\conf\application.conf -Dlogger.file=E:\yona-1.0.0\bin\conf\application-logger.xml -DapplyEvolutions.default=true


▷ 정상 실행 화면
E:\yona-1.0.0\bin>yona.bat
**E:\yona-1.0.0\bin\\\..    --> YONA_HOME이 어느 경로인지 한번 출력 해봤어요.**
Play server process ID is 6120
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[info] play - Starting application default Akka system.
[info] play - Application started (Prod)
[info] application - User uploaded temporary files are cleaned up...(0 of 0)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000


감사합니다.

**Comment by doortts** [comment]
네. 경로를 바꾸지 않으신다면 운영해도 문제는 없으세요.

E:\yona-1.0.0 에서
```
bin\yona 
```
로 실행하시면 아마 full path 를 지정하지 않으셔도 동작할 것 같습니다만 확인해 봐야 할 것 같네요.

**Comment by doortts** [comment]
v1.0.2 에서 테스트 해보시고 여전하시다면 다시 이슈를 열어주세요.
