### ISSUE TITLE
이메일 알림 전송 실패

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#240]
팀내에서 협업시 사용을 고려하며 테스트중인데 알림기능에서 문제가 있습니다.
현재 관리자 이메일 전송 기능은 정상 동작하는데, 게시글 수정이나 사용자 언급 등에서 이메일 알림이 동작하지않습니다.
버그는 아닌것같고 제가 뭔가 잘못설정한게 아닐까 하는데... 어떤 부분을 참고해야할까요?

요나 위키보고 `application.conf`의 아래부분은 변경한 상태입니다.

![2017-07-12 12 30 29](https://user-images.githubusercontent.com/7797499/28103726-2cdb1224-6712-11e7-8956-e58de2bf5f9e.png)

아래는 이메일 알림 전송 실패하는 로그부분입니다.

```
[warn] application - Failed to send a notification: models.NotificationMail$EventEmail@7c4b89b5
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at mailbox.EmailAddressWithDetail.<init>(EmailAddressWithDetail.java:46)
        at models.NotificationMail.getReplyTo(NotificationMail.java:602)
        at models.NotificationMail.sendMail(NotificationMail.java:516)
        at models.NotificationMail.sendNotification(NotificationMail.java:418)
        at models.NotificationMail.access$100(NotificationMail.java:57)
        at models.NotificationMail$1.sendMail(NotificationMail.java:149)
        at models.NotificationMail$1.run(NotificationMail.java:112)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by doortts** [comment]
@dinobei 
즉, 관리자가 직접 관리자 메뉴에서 메일을 발송하는 것 말고는 이슈등록, 수정, 코멘트 등등에서 메일이 발송되지 않는다는 이야기이신거죠?

**Comment by doortts** [comment]
@dinobei 
관리자 메뉴로 들어가셔서 이메일주소중에 이상한 이름의 이메일, 이를테면 @ 이 없는 이메일이라던가 하는 이메일이 없는지 한번 확인해 주세요.

**Comment by dinobei** [comment]
@doortts 
네 맞습니다. 아래 1, 2번 상황에서는 메일 전송이 정상적으로 이뤄지는것은 확인하였습니다.

1. 관리자가 직접 메일 전송
2. 프로젝트 이관, 그룹/프로젝트에 사용자 초대, 비밀번호 재설정

관리자 메뉴에서 전체 사용자중에 이메일은 모두 정상적으로 기입되어있는것도 확인하였습니다.

**Comment by doortts** [comment]
@dinobei 
네. 확인을 위해 혹시 DB접근이 가능하시면 다음 두 쿼리의 결과값이 동일한지 한 번 확인해 주시겠어요?
```
select count(*) from n4user where email like '%@%';
select count(*) from n4user;
```

그리고 아래 결과가 0 이 나오는지도요.
```
select count(*) from n4user where email not like '%@%';
```

**Comment by dinobei** [comment]
@doortts 
네, 확인해보았습니다.
두 쿼리의 결과값은 동일하고 결과 0도 확인했습니다.

아래 캡쳐 첨부합니다.
![2017-07-12 6 44 54](https://user-images.githubusercontent.com/7797499/28111961-40c46752-6732-11e7-8958-264401088f38.png)

**Comment by sjstyle** [comment]
@dinobei 저는 imap 설정 부분이 의심스럽네요. 
혹시 imap 관련 설정들을 하셨나요?

https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L196

**Comment by dinobei** [comment]
@sjstyle
처음에 imap 설정부분을 건드리긴했었는데, 아래 그림처럼 처리해놓았고, 현재 `imap.use = false`로 되어있습니다.

![2017-07-12 7 19 26](https://user-images.githubusercontent.com/7797499/28113318-105bb048-6737-11e7-9b20-7b49d7aa7d67.png)

**Comment by sjstyle** [comment]
imap.address에 유효하지 않은 이메일이 입력되있어서 그럴지도 모른다는 생각이 듭니다

**Comment by dinobei** [comment]
@sjstyle 
오... 맞습니다. 해당 부분 설정을 디폴트로 돌렸더니 알람 메일이 정상적으로 옵니다!
