### ISSUE TITLE
H2 1.6.1 DB 마이그레이션 오류

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#247]
안녕하세요. 
H2 1.6.1 업그레이드시 DB 마이그레이션 오류가 발생합니다.

### 테스트
1. 1.5.1 > 1.6.0: 정상
2. 1.5.1 > 1.6.1: 오류발생
3. 1.6.0 > 1.6.1: 오류발생

### 로그
케이스 2번 3번 동일한 오류가 발생합니다.

```
[INFO] JAVA OPTIONS: -Xms2048m -Xmx4096m
Picked up _JAVA_OPTIONS: -Xms2048m -Xmx4096m
Play server process ID is 7
[info] play - database [default] connected at jdbc:h2:file:/yona/yona
[error] play - Syntax error in SQL statement "[*]<<<<<<< HEAD

ALTER TABLE TAG DROP CONSTRAINT IF EXISTS UQ_TAG_CATEGORY_NAME "; SQL statement:
<<<<<<< HEAD

ALTER TABLE tag DROP CONSTRAINT IF EXISTS uq_tag_category_name [42000-176] [ERROR:42000, SQLSTATE:42000]
Oops, cannot start the server.
@74mkbp5b3: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:296)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:496)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

늘 감사합니다.

**Comment by yongseokleecom** [comment]
H2 패치로 해결완료했습니다.

**Comment by doortts** [comment]
@yongseokleecom h2 버전 배포 파일에 문제가 있는걸 발견해서 다시 파일 올렸습니다.  확인해주셔서 고맙습니다.
