### ISSUE TITLE
branch name이 길 경우 개행되는 문제

### ISSUE THREAD

**Issue by E-nuri** [yona-projects/yona#252]
## 현재 상황(문제점)
PR 메뉴에서 PR등록을 하고 난 뒤 해당 PR 정보 페이지에서 볼 경우 발생한다.
프로젝트의 경로와 브랜치의 이름이 짧을 경우엔 이상이 없지만 일정길이 이상 길어질 경우 다음줄로 강제 개행됨
강제 개행으로 인해 가독성이 나빠지는 문제.

## 문제가 영향이 미치는 곳
PR 메뉴의 open, closed 페이지.

## 해결방안(추정)
아래의 CSS 값 수정

* 1-a.
```
.board-body .author-info
```
기존 : display: inline-block;
변경 후: display: block;

* 1-b.
```
.right-txt
```
기존: text-align: right;
변경 후: text-align: left;

## before
<img width="1174" alt="before" src="https://user-images.githubusercontent.com/20082776/28763152-d8e2c254-75f6-11e7-9f08-89080b7d58a6.png">

## after
<img width="1175" alt="after" src="https://user-images.githubusercontent.com/20082776/28763156-e78c647c-75f6-11e7-8a70-cc34c3f02150.png">

**Comment by E-nuri** [comment]
단편적으로 Inspector에서 css값을 이것저것 바꿔가면서 해본거라 다른부분에서 어떤 side effect가 있을지 모릅니다.
재검토가 필요합니다.

**Comment by E-nuri** [comment]
신입이라 웹 개발을 잘 모릅니다.
css파일을 찾아서 직접 해보려고했는데 어느 경로를 찾아들어가야하는지도 잘 모르겠구요.
혹시 도움 주시면 나중에 비슷한 버그가 있을때 직접 해보고싶습니다.

**Comment by doortts** [comment]
@E-nuri 
오 좋네요!! 

문제되는 부분도 정확히 찾으신것 같구요.

관련 코드로는
---
- 페이지 자체는
  - https://github.com/yona-projects/yona/blob/master/app/views/git/view.scala.html#L39
- css가 만들어지는 less 파일은
  - https://github.com/yona-projects/yona/blob/master/app/assets/stylesheets/less/_page.less#L2726

[소스코드를 내려 받아서 빌드](https://github.com/yona-projects/yona#소스코드를-직접-내려-받아서-빌드-실행하기)를 참고하셔서 한 번 pull request 보내주시면 어떠세요? : )

**Comment by E-nuri** [comment]
@doortts 
감사합니다. 공부해보고 PR해보겠습니다

**Comment by E-nuri** [comment]
@doortts 
https://repo.yona.io/yona-projects/yona/post/5

알려주신 링크를 보고 설치했는데 마지막 결과화면을 못보고 있습니다
콘솔을 띄우고 start를 하면 아래의 에러로그가 나옵니다.

[https://github.com/yona-projects/yona/blob/master/docs/ko/install-yona-server.md](링크)를 보고 application.conf에서 password도 수정했습니다.


`Play server process ID is 3739
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES).Message:Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:130)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91)
	at org.mariadb.jdbc.Driver.connect(Driver.java:109)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
	... 22 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:566)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:507)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:392)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
	at org.mariadb.jdbc.Driver.connect(Driver.java:104)
	... 28 more
`

**Comment by E-nuri** [comment]
<img width="508" alt="2017-08-18 5 02 17" src="https://user-images.githubusercontent.com/20082776/29449779-12985b50-8437-11e7-8fba-f27259417dae.png">

DB에 사용자를 추가 안해서 발생한 문제로 생각됩니다.
그래서 추가를 시도하려고 DB에 접속해서 show databases로 yona를 보고 선택한 뒤 tables를 봤는데 아무것도 없습니다.

[https://github.com/yona-projects/yona/blob/master/docs/ko/install-mariadb.md](링크)에 나온것처럼 mysql -uroot -p 한 뒤 create user 'yona'@'localhost' IDENTIFIED BY 'yonadan'; 명령어를 실행하는게 맞는건지요?

**Comment by E-nuri** [comment]
@doortts 위의 설치과정에서 발생한 문제점은 따로 작성해서 공유할 수 있도록 PR보내겠습니다.

**Comment by doortts** [comment]
@E-nuri 님이 도움주셔서 v1.7부터 해당 문제가 수정되었습니다.
