### ISSUE TITLE
1.6.1 h2 버전 실행시 smtp 오류

### ISSUE THREAD

**Issue by kirious** [yona-projects/yona#256]
yona 1.6.1 h2 버전 첫실행후 관리자 지정후 서버 재시작 하면

아래 메세지 처럼 오류와 함께 실행이 안됩니다.

java.lang.RuntimeException: smtp.host needs to be set in application.conf in order to use this plugin (or set smtp.mock to true)
        at com.typesafe.plugin.CommonsMailerPlugin$$anonfun$8.apply(MailerPlugin.scala:497)
        at com.typesafe.plugin.CommonsMailerPlugin$$anonfun$8.apply(MailerPlugin.scala:497)
        at scala.Option.getOrElse(Option.scala:120)
        at com.typesafe.plugin.CommonsMailerPlugin.mailerInstance$lzycompute(MailerPlugin.scala:497)
        at com.typesafe.plugin.CommonsMailerPlugin.mailerInstance(MailerPlugin.scala:494)
        at com.typesafe.plugin.CommonsMailerPlugin.onStart(MailerPlugin.scala:512)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

1.6.0에서는 정상적으로 실행이 되는데, 1.6.1 버전에서만 발생합니다.

확인 부탁드립니다~

**Comment by doortts** [comment]
@kirious 
혹시 YONA_DATA 설정 하셨나요? 안하셨다면 해주셔야 할 것 같습니다.

아래 링크를 참고해주세요.
https://github.com/yona-projects/yona/blob/master/docs/ko/yona-run-and-restart.md#yona-실행-방법

**Comment by kirious** [comment]
1.6.0에서는 bin디렉토리가 자동으로 YONA_DATA로 설정이 되는것 같은데,

1.6.1에서 변경된 건가요? 가이드대로 1.6.1에서 YONA_DATA를 설정하여 첫실행하면 

경로를 못찾는 문제가 발생하여(첫실행인데 application.conf파일을 찾습니다.), 

bin/yona.bat을 직접 실행하여 DB파일이 생성된 이후에

DB파일을 DATA디렉토리로 이동하고, 가이드대로 설정하니 정상 실행이 됩니다.

**Comment by doortts** [comment]
@kirious 
해당 문제는 v1.7 에서 개선될 예정입니다.
h2 버전의 경우 YONA_DATA 설정 없이 실행하는 것에 대해 조금 고민이 필요한것 같습니다.

**Comment by doortts** [comment]
v1.7부터 해당 문제가 수정되었습니다.
문제 발생시 다시 오픈해주세요.
