### ISSUE TITLE
1.6.1 h2 bin버전 windows에서 첫 실행시 오류

### ISSUE THREAD

**Issue by hsoo** [yona-projects/yona#257]
첫 실행시 오류가 발생하면서 conf 가 생성되지 않습니다.

```
D:\yona\yona-1.6.1>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

D:\yona\yona-1.6.1>bin\yona.bat
Play server process ID is 17124
Oops, cannot start the server.
@750p0ha5d: Cannot init the Global object
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:59)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:53)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$globalInstance(Application.scala:52)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$globalInstance(Application.scala:402)
        at play.api.WithDefaultGlobal$class.global(Application.scala:68)
        at play.api.DefaultApplication.global(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:82)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultConfiguration$$fullConfiguration(Application.scala:402)
        at play.api.WithDefaultConfiguration$class.configuration(Application.scala:84)
        at play.api.DefaultApplication.configuration(Application.scala:402)
        at play.api.Application$class.$init$(Application.scala:274)
        at play.api.DefaultApplication.<init>(Application.scala:402)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:53)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.UnsupportedClassVersionError: Global : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at play.api.WithDefaultGlobal$class.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:31)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal$lzycompute(Application.scala:402)
        at play.api.DefaultApplication.play$api$WithDefaultGlobal$$javaGlobal(Application.scala:402)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:54)
        ... 21 more

D:\yona\yona-1.6.1>
```

**Comment by doortts** [comment]
@hsoo 
에러 자체는 자바버전이 맞지 않는다는 에러인데요
괜찮으시다면 v1.6.0 으로 테스트 해 봐 주시겠어요?

https://github.com/yona-projects/yona/releases/tag/v1.6.0

**Comment by hsoo** [comment]
v1.6.0 도 똑 같은 에러가 나옵니다.

```
D:\yona\yona-1.6.0>bin\yona.bat
Play server process ID is 24340
Oops, cannot start the server.
@7510hg4nl: Cannot init the Global object
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:59)
        at play.api.WithDefaultGlobal$$anonfun$play$api$WithDefaultGlobal$$globalInstance$1.apply(Application.scala:53)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)

```

자바는 어떤 버전을 설치 하면 될까요?

**Comment by doortts** [comment]
@hsoo 
시스템내에 다른 버전(구 버전)의 Java 버전에 설치되어 있고 JAVA_HOME 설정이 그쪽으로 잡혀 있는 것이 아닌가 싶습니다. 혹시 다른 버전의 Java가 설치되어 있나요?

그리고 
```
echo %JAVA_HOME%
```
결과가 어떻게 되나요?

**Comment by sjstyle** [comment]
`set` 결과도 올려주시면 좋을 것 같습니다~

**Comment by hsoo** [comment]
JAVA_HOME이 1.7.x 버전으로 설정되어 있어서 1.8로 바꾸니 작동됩니다.
