### ISSUE TITLE
커밋 메일 내용이 확인 안돼요

### ISSUE THREAD

**Issue by woobong** [yona-projects/yona#264]
안녕하세요. 궁금한 점이 있어서 문의 드립니다.

기존에는 커밋 메세지가 아래 같이 보였던 것 같은데요. 

생각 없이 좀 지나서 확인해보니
New CommitsBranchesrefs/heads/Develop
의 형태로만 메일 내용이 보이고, 커밋 메세지가 안보이기 시작했습니다..

메일 내용의 HTML 소스코드 보기로 확인 하니, 몇몇 엘리먼트의 "" 닫기 문제라던지, 
로 인하여, 뒤에 엘리먼트가 먹혀서(?) 표시가 안되는 것 같은데요.

구글 SMTP 를 사용하고 있습니다.
저도 소스코드로 살펴보고는 있는데, 현재 상황에서 문제가 어디인지는 아직 발견하지는 못했습니다..
한번 같이 공유해보고자 문의 드립니다 :)

**Comment by doortts** [comment]
다음 릴리즈에서 해결될 예정입니다.

https://repo.yona.io 에서 테스트 가능하시다면 한 번 부탁드릴게요.

**Comment by doortts** [comment]
v1.7에서 해결되었습니다. 업그레이드 후 동일 문제가 발생하면 알려주세요.

**Comment by woobong** [comment]
감사합니다 :+1: 

확인해보고 답글 달도록 하겠습니다!

**Comment by woobong** [comment]
`
Failed to send a notification: models.NotificationMail$EventEmail@5aed1119
java.lang.UnsupportedOperationException
        at models.resource.GlobalResource.getProject(GlobalResource.java:28)
        at models.NotificationMail.getHtmlMessage(NotificationMail.java:615)
        at models.NotificationMail.sendMail(NotificationMail.java:549)
        at models.NotificationMail.sendNotification(NotificationMail.java:418)
        at models.NotificationMail.access$100(NotificationMail.java:57)
        at models.NotificationMail$1.sendMail(NotificationMail.java:149)
        at models.NotificationMail$1.run(NotificationMail.java:112)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`
위와 같이 에러가 발생하며, 커밋 메세지 메일이 전송 되지 않습니다.
설정의 이메일 전송 기능으로, 메일을 전송하는 기능은 정상적으로 동작을 하네요..

**Comment by doortts** [comment]
@woobong 
v1.8 에서 해당 부분 및 관련 부분들의 코드가 수정되었습니다.
테스트 한 번 부탁드려도 될까요?

https://repo.yona.io 도 v1.8.0으로 업그레이드 해 놓았습니다.

**Comment by doortts** [comment]
v1.8.1에도 동일 문제 발생시 다시 열어주세요.
