### ISSUE TITLE
자동 업데이트 기능(?)에서  repository 접근 문제

### ISSUE THREAD

**Issue by blueprajna** [yona-projects/yona#269]
[warn] application - Failed to fetch the latest Yobi version to update
org.eclipse.jgit.api.errors.TransportException: http://repo.yona.io/yona/yona: 301 Moved Permanently
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:221) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:102) ~[yona.yona-1.6.1.jar:1.6.1]
	at models.YobiUpdate.refreshVersionToUpdate(YobiUpdate.java:82) ~[yona.yona-1.6.1.jar:1.6.1]
	at models.YobiUpdate$1.run(YobiUpdate.java:63) ~[yona.yona-1.6.1.jar:1.6.1]
Caused by: org.eclipse.jgit.errors.TransportException: http://repo.yona.io/yona/yona: 301 Moved Permanently
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:506) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:290) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:102) ~[yona.yona-1.6.1.jar:1.6.1]

구동시 자동업데이트 기능을 위해 접속하는 repository가 접근이 제한되어 있는것으로 보입니다.

**Comment by doortts** [comment]
@blueprajna H2 버전을 쓰고 계신거죠?

**Comment by blueprajna** [comment]
@doortts 네 h2버전입니다

**Comment by doortts** [comment]
@blueprajna 
conf/application.conf 파일을 여셔서 application.update.repositoryUrl 값을 아래처럼 변경해주세요.

```
application.update.repositoryUrl = "https://github.com/yona-projects/yona"
```
