### ISSUE TITLE
프로젝트 삭제시 에러가 발생 합니다.

### ISSUE THREAD

**Issue by jisoon** [yona-projects/yona#27]
에러 메세지는 아래와 같습니다.

2016-03-25 11:17:22,049 - [ERROR] - from play in play-akka.actor.default-dispatcher-237 
Cannot invoke the action, eventually got an error: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from project where id=? and name=? and overview=? and vcs=? and siteurl=? and owner=? and created_date=? and last_issue_number=? and last_posting_number=? and last_pushed_date=? and default_reviewer_count=? and is_using_reviewer_count=? and project_scope=? and previous_owner_login_id is null and previous_name is null and previous_name_changed_time is null and original_project_id is null and organization_id is null] bind[null]

2016-03-25 11:17:22,069 - [ERROR] - from application in play-akka.actor.default-dispatcher-237 

! @6pgec72gm - Internal server error, for (DELETE) [/assa/Nexpector_cloud/delete] ->

play.api.Application$$anon$1: Execution exception[[OptimisticLockException: Data has changed. updated [0] rows sql[delete from project where id=? and name=? and overview=? and vcs=? and siteurl=? and owner=? and created_date=? and last_issue_number=? and last_posting_number=? and last_pushed_date=? and default_reviewer_count=? and is_using_reviewer_count=? and project_scope=? and previous_owner_login_id is null and previous_name is null and previous_name_changed_time is null and original_project_id is null and organization_id is null] bind[null]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from project where id=? and name=? and overview=? and vcs=? and siteurl=? and owner=? and created_date=? and last_issue_number=? and last_posting_number=? and last_pushed_date=? and default_reviewer_count=? and is_using_reviewer_count=? and project_scope=? and previous_owner_login_id is null and previous_name is null and previous_name_changed_time is null and original_project_id is null and organization_id is null] bind[null]
        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:95) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:54) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:48) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:99) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:456) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:592) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:396) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1867) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1857) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebean.Ebean.delete(Ebean.java:596) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at play.db.ebean.Model.delete(Model.java:171) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
        at models.Project.delete(Project.java:672) ~[yona.yona-1.0.0.jar:1.0.0]
        at controllers.ProjectApp.deleteProject(ProjectApp.java:343) ~[yona.yona-1.0.0.jar:1.0.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$103$$anonfun$apply$103.apply(routes_routing.scala:2450) ~[yona.yona-1.0.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$103$$anonfun$apply$103.apply(routes_routing.scala:2450) ~[yona.yona-1.0.0.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at Global$1.call(Global.java:190) ~[yona.yona-1.0.0.jar:na]
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.0.0.jar:1.0.0]
        at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yona.yona-1.0.0.jar:1.0.0]
        at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:85) ~[yona.yona-1.0.0.jar:1.0.0]
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:21) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebean.Ebean.execute(Ebean.java:1264) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted

2016-03-25 11:17:22,085 - [INFO] - from access./assa/Nexpector_cloud/delete in play-akka.actor.default-dispatcher-237 
192.168.1.1 - - [25/Mar/2016:11:17:22 +0900] "DELETE /assa/Nexpector_cloud/delete HTTP/1.1" 500 - "http://106.248.228.114:9000/assa/Nexpector_cloud/deleteform" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36" -

확인 부탁 드립니다.

히스토리는 저장소 변경 하다가 error 가 발생 하였고 그이후로 프로젝트 삭제가 안된다고 합니다.

혹 DB 에서 직접 삭제 할 수 있는 쿼리 있으시면 부탁 드리겠습니다.
project 테이블이 릴레이션 관계 때문에 삭제 하기 힘드네요 ^^

**Comment by doortts** [comment]
@jisoon 안녕하세요?
저장소 변경하다가의 의미는 `svn -> git으로 저장소 타입을 변경`을 의미하시는건가요?

**Comment by jisoon** [comment]
아. 죄송 매번 설명이 부족하네요. 죄송합니다.

로그를 확인해 보면 git - > svn 인것 같습니다.(확실 한지는 모르겠네요)
```
2016-03-25 02:40:20,624 - [INFO] - from access./assa/Nexpector_cloud/git-receive-pack in play-akka.actor.default-dispatcher-142
192.168.1.1 - assa [25/Mar/2016:02:40:20 +0900] "POST /assa/Nexpector_cloud/git-receive-pack HTTP/1.1" 200 - - "git/2.5.0.windows.1" 127ms

2016-03-25 02:40:24,881 - [INFO] - from application in play-akka.actor.default-dispatcher-146
Illegal SVN revision: HEAD

2016-03-25 02:40:24,914 - [ERROR] - from play in play-akka.actor.default-dispatcher-146
Cannot invoke the action, eventually got an error: org.tmatesoft.svn.core.SVNException: svn: E180001: Unable to open an ra_local session to URL
svn: E180001: Unable to open repository 'file:///home/yona/yona/repo/svn/assa/Nexpector_cloud'
```

이런 에러가 발생 하였습니다. 이후로 프로젝트 홈화면과 코드 메뉴가 비정상적으로 표현 되었습니다.

그래서 제가 `/home/yona/yona/repo/svn/assa/Nexpector_cloud` 디렉토리는 만들어 주었습니다.(다른 svn 디렉토리 내용을 cp 했습니다.)

그리고 프로젝트 삭제를 하였습니다.
에러가 발생 하였습니다.

**Comment by doortts** [comment]
네. 그렇군요. (설명은 잘 해주고 계세요?)

그리고 이미 프로젝트 자체는 삭제되었을 수도 있습니다.

프로젝트 삭제를 원하시는게 맞으시다면 repo 아래의 저장소 디렉터리도 같이 삭제해 주시면 될 것 같습니다.

```
/home/yona/yona/repo/svn/assa/Nexpector_cloud
```

그리고 혹시 서버를 재시작 한번 보셨나요?

**Comment by jisoon** [comment]
project 테이블에는 아직 정보가 남아 있는데 괜찮을 까요?

**Comment by jisoon** [comment]
V1.0.1 에서는 이상 없이 동작 합니다.
