### ISSUE TITLE
Win10에서 Yona 설치가 안됩니다

### ISSUE THREAD

**Issue by bulchor** [yona-projects/yona#28]
windows 10 Edu Ed에서 mariaDB설치하고 yona/bin폴더에서 yona.bat을 실행하면 아래의 에러가 발생합니다.
mariaDB접속 테스트는 접속이됩니다.
>mysql -uyona -p"yonadan" -Dyona

"윈도우7 x64에서 실행안됨" 이슈를 읽어봐도 잘 모르겠습니다.
아래는 yona.bat을 실행하면 발행하는 오류메세지입니다.

C:\Tool\yona\bin>yona.bat
Play server process ID is 6028
[error] c.j.b.h.AbstractConnectionHook - Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES).Message:Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
Oops, cannot start the server.
Configuration error: Configuration error[Cannot connect to database [default]]
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at play.api.db.BoneCPPlugin.onStart(DB.scala:238)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:121)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.Driver.connect(Driver.java:110)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
        ... 22 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:464)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:428)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:351)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:664)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:587)
        at org.mariadb.jdbc.Driver.connect(Driver.java:105)
        ... 28 more

**Comment by bulchor** [comment]
설치파일은
mariadb 10.1.12-win32.msi
yona-1.0.0-bin.zip 입니다.

**Comment by doortts** [comment]
안녕하세요? 
아마 #25 와 동일한 문제로 생각됩니다. 밤에 집에가서 #14 와 같이 보고 처리해 보겠습니다.
@Clark19 님은 해결하셨다고 하셨던데 여쭤봐야겠습니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.0.1
이 걸로 한 번 테스트해봐 주시겠어요?

**Comment by bulchor** [comment]
동일하게 오류가 발생합니다.

application.conf에 패스워드를 초기값인 yonadan으로 변경하면 정상실행이 됩니다.

**Comment by doortts** [comment]
@bulchor 그렇다면 yona 유저의 password가 yonadan 으로 지정되어 있는 상태라서 일겁니다.

DB 접속하셔서
```sql
ALTER USER  'yona'@'localhost' IDENTIFIED BY '원하는 password';
```
로 바꾸시고 application.conf 에도 변경한 password로 지정해 주세요.

**Comment by bulchor** [comment]
Yona 1.0.1을 받아서 실행한 내역(간략)

1. DB의 yona유저의 비밀번호를 지정한 후 접속테스트 정상인 것을 확인한 후에
2. application.conf 변경하고 yona.bat을 실행, 오류발생...

3. 혹시나 해서 yona유저의 비밀번호를 yonadan으로 변경하고
4. application.conf 수정하고 다시 실행, 정상동작.

2016. 4. 12. 오후 1:05에 Suwon Chae <notifications@github.com>님이 작성:

@bulchor<https://github.com/bulchor> 그렇다면 yona 유저의 password가 yonadan 으로 지정되어 있는 상태라서 일겁니다.

DB 접속하셔서

ALTER USER  'yona'@'localhost' IDENTIFIED BY '원하는 password';

로 바꾸시고 application.conf 에도 변경한 password로 지정해 주세요.

**Comment by doortts** [comment]
@bulchor 혹시 yona.bat 실행을 
bin 디렉터리에서 하셨나요?
아니면
bin\yona 식으로 상위 폴더에서 하셨나요?

혹시 전자라면 후자 방식으로 한 번 해봐주시겠어요?

**Comment by bulchor** [comment]
bin\yona으로 실행했습니다.

2016. 4. 16. 오후 10:46에 Suwon Chae <notifications@github.com>님이 작성:

@bulchor<https://github.com/bulchor> 혹시 yona.bat 실행을
bin 디렉터리에서 하셨나요?
아니면
bin\yona 식으로 상위 폴더에서 하셨나요?

혹시 전자라면 후자 방식으로 한 번 해봐주시겠어요?

**Comment by doortts** [comment]
@bulchor 님
default application.conf 가 yona.yona-1.0.x.jar 파일에 포함되는데 이것때문에 문제가 생기는것 같아요. DB password도 기본값으로만 인식하고.

windows 에서 YONA_HOME을 지정하게 만들어야 하나 고민중입니다. 시스템 환경변수로 JAVA_HOME 등록하듯이 YONA_HOME을 등록하게 해야 하나..

그런데 그거하라면 귀찮아지는데 사용하는사람이 번거로워지는건 싫어서 고민되네요.

조금더 테스트 해보고 방법 찾아보겠습니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/issues/25#issuecomment-200467623 와도 연관이 있는것 같습니다

**Comment by brainagenet** [comment]
@bulchor @doortts 늦었지만 해결이 되었는지 궁금합니다만 `application.conf`의 db password 등의 값에 특수 문자 등이 있을 경우에는 다음과 같이 처리하면 잘 됩니다.

```
# MariaDB
db.default.driver=org.mariadb.jdbc.Driver
# db.default.url="jdbc:mariadb://127.0.0.1:3306/yonadb?useServerPrepStmts=true"
db.default.user=yona
db.default.password="!yoNa#86ds8f4"
```

위와 같이 `"` 묶어주면 정상적으로 잘 동작합니다.

**Comment by doortts** [comment]
windows 실행 방법 설명을 변경했습니다.
https://github.com/yona-projects/yona#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0

확인해보시고 필요하시면 다시 이슈 열어주세요
