### ISSUE TITLE
코드 리뷰 코멘트 작성시 "서버 오류가 발생하여 서비스를 이용할 수 없습니다"

### ISSUE THREAD

**Issue by dinobei** [yona-projects/yona#299]
코드리뷰 기능을 지금껏 안쓰고있다가 테스트를 해보니 오류가 발생합니다.

아래는 서버 오류로그입니다.
```
[error] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[(conn:4549) CONSTRAINT `ck_comment_thread_start_side` failed for `yona`.`comment_thread`\n Query is: insert into comment_thread (dtype, state, created_date, prev_commit_id, commit_id, author_id, author_login_id, author_name, pull_request_id, project_id) values (?,?,?,?,?,?,?,?,?,?), parameters ['non_ranged','OPEN','2017-09-21 10:43:59.496',<null>,'352d0f920b24c8248e52d278ab9799f020e14db4',2,'test_id','홍길동',<null>,38]]
[error] application -
! @75cpcd101 - Internal server error, for (POST) [/Developer/CoreLibrary/commit/352d0f920b24c8248e52d278ab9799f020e14db4/comments] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error[(conn:4549) CONSTRAINT `ck_comment_thread_start_side` failed for `yona`.`comment_thread`\n Query is: insert into comment_thread (dtype, state, created_date, prev_commit_id, commit_id, author_id, author_login_id, author_name, pull_request_id, project_id) values (?,?,?,?,?,?,?,?,?,?), parameters ['non_ranged','OPEN','2017-09-21 10:43:59.496',<null>,'352d0f920b24c8248e52d278ab9799f020e14db4',2,'test_id','홍길동',<null>,38]]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[(conn:4549) CONSTRAINT `ck_comment_thread_start_side` failed for `yona`.`comment_thread`\n Query is: insert into comment_thread (dtype, state, created_date, prev_commit_id, commit_id, author_id, author_login_id, author_name, pull_request_id, project_id) values (?,?,?,?,?,?,?,?,?,?), parameters ['non_ranged','OPEN','2017-09-21 10:43:59.496',<null>,'352d0f920b24c8248e52d278ab9799f020e14db4',2,'test_id','홍길동',<null>,38]]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:57) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:66) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:448) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn:4549) CONSTRAINT `ck_comment_thread_start_side` failed for `yona`.`comment_thread`
Query is: insert into comment_thread (dtype, state, created_date, prev_commit_id, commit_id, author_id, author_login_id, author_name, pull_request_id, project_id) values (?,?,?,?,?,?,?,?,?,?), parameters ['non_ranged','OPEN','2017-09-21 10:43:59.496',<null>,'352d0f920b24c8248e52d278ab9799f020e14db4',2,'test_id','홍길동',<null>,38]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:128) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: CONSTRAINT `ck_comment_thread_start_side` failed for `yona`.`comment_thread`
Query is: insert into comment_thread (dtype, state, created_date, prev_commit_id, commit_id, author_id, author_login_id, author_name, pull_request_id, project_id) values (?,?,?,?,?,?,?,?,?,?), parameters ['non_ranged','OPEN','2017-09-21 10:43:59.496',<null>,'352d0f920b24c8248e52d278ab9799f020e14db4',2,'test_id','홍길동',<null>,38]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:602) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:398) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:359) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:348) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
```

**Comment by doortts** [comment]
@dinobei 
https://repo.yona.io 에서도 동일한 오류나 유사한 오류가 재현되는지 테스트 해 봐 주실 수 있을까요?

**Comment by dinobei** [comment]
안녕하세요. 데모사이트(https://dinobei@repo.yona.io/dinobei/CodeReviewTest)에서 테스트해보니 잘 동작합니다. 제가 확인해야할 설정같은게 있을까요?

**Comment by doortts** [comment]
@dinobei 
혹시 push -f 등을 사용해서 기존 커밋을 지워버리거나 한 상황이 있었나요?

**Comment by dinobei** [comment]
@doortts 
현재 테스트하는 프로젝트는 지운적은 없었습니다만,
예전에, 특정 프로젝트의 git 코드를 전체적으로 다시 푸시하기 위해서 #273 을 참고해서 지우고 다시 만든적은 있습니다..

**Comment by sjstyle** [comment]
@doortts 
`repo.yona.io` 에 `comment_thread ` 테이블에 `ck_comment_thread_start_side` constraint가 있나요? 자세히보진 않았지만 해당 조건 때문에 null 입력이 불가능 해 보입니다.

**Comment by doortts** [comment]
@sjstyle 
전혀 감을 잡지 못하고 있었는데 이야기를 듣고보니 MySQL은 전통적으로 (...) check constraints 를 지원하지 않고 있는데 최근 MariaDB (10.2.x 대 아마도?)에서 check constraints 를 지원할거라는 노트를 봤던 기억이 떠오르네요. 관련해서 발생한 문제일 수도 있겠네요.

@dinobei 
```
mysql -V
```
명령으로 MariabDB 버전이 어떻게 되는지 확인해 주시겠어요?

repo.yona.io 는 현재 10.1.x 인데 버전을 올려봐야겠네요.

**Comment by doortts** [comment]
@dinobei 
http://repo.yona.io DB를 `mysql  Ver 15.1 Distrib 10.2.9-MariaDB, for Linux (x86_64) using readline 5.1`로 올렸습니다. http://repo.yona.io 에서 테스트 다시 한 번 더 부탁드릴게요.

**Comment by dinobei** [comment]
@doortts 
현재 세팅한 서버는 `mysql  Ver 15.1 Distrib 10.2.6-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`입니다. http://repo.yona.io 접속해서 동일하게 코드 제거하고 재테스트해보니 정상 동작합니다. 제 서버에서만 안되는거같네요.

**Comment by sjstyle** [comment]
@doortts 테스트 방법에 문제가 있는 것 같습니다.

제 docker 환경에서도 @dinobei 님이 말씀하신 문제가 발생하고 있습니다.
```
root@e66afc753299:/# mysql -V
mysql  Ver 15.1 Distrib 10.2.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

말씀하신 문제가 맞다면 mariadb 가 낮은 상태에서 진행되었을 `repo.yona.io`는 디비 버전을 올렸다고 존재하지 않던 check constraint 가 생길리 없으므로 여전히 발생하지 않을 것 같습니다. 버전을 애초에 올린 mariadb에 yona 클린 설치를 했서 문제가 발생하는지 여부를 체크해야할 것으로 보입니다.

**Comment by dinobei** [comment]
@doortts 
음.. 정리해보면 10.2.x 이상?에서 check constraint가 문제로 추측되는건가요?
docker말고 또 다른 물리적인 서버에 클린설치해보았는데, mysql 버전은 `mysql  Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2` 이고, 정상 동작하고있습니다.
mariadb 버전업 뒤 동작하지 않는지 테스트해보면되나요?

**Comment by doortts** [comment]
@dinobei 
네 맞습니다. 10.2.x 이상?에서 check constraint가 문제로 추측됩니다.

즉, 
- MariaDB 10.1.x 를 쓰다가 업그레이드 하는 경우에는 문제가 없는데
- MariaDB 10.2.x를 새로 설치해서 쓰는 경우 문제가 생기는 것으로 보입니다.

constrints 를 제거하는 것을 고려해 봐야 할 것 같습니다.

**Comment by dinobei** [comment]
음.. 그럼 버전업에서 해결 가능한 문제로 보면 될까요?
이미 운영중인 요나서버라서 디비관련 수정작업을 하기가 좀 그렇네요..

**Comment by doortts** [comment]
@dinobei v1.9 부터 두 가지 MariaDB 버전으로 배포판을 만들어서 제공하고 있습니다. 현재 MariaDB 버전에 맞는 배포판을 내려 받아서 확인해 주시겠어요?

**Comment by dinobei** [comment]
@doortts 
안녕하세요.
1.9 버전부터는 계속 업데이트 반영해서 사용중인데, 해당 증상 전혀 없는걸 확인했습니다.
