### ISSUE TITLE
[버그?] 1.8.1 에서 git push 시 Pipe close

### ISSUE THREAD

**Issue by siro012** [yona-projects/yona#311]
아래와 같은 에러 로그가 나오는데 어떤 설정이 잘못된 것일까요?
nginx 로 proxy 걸어서 사용하고 있습니다

receivePack failed
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260) ~[na:1.8.0_144]
	at java.io.PipedInputStream.receive(PipedInputStream.java:226) ~[na:1.8.0_144]
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149) ~[na:1.8.0_144]
	at org.eclipse.jgit.transport.SideBandOutputStream.writeBuffer(SideBandOutputStream.java:171) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.SideBandOutputStream.flushBuffer(SideBandOutputStream.java:127) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.BaseReceivePack.close(BaseReceivePack.java:1710) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:209) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at playRepository.RepositoryService$2.run(RepositoryService.java:290) ~[yona.yona-1.8.1.jar:1.8.1]

**Comment by siro012** [comment]
nginx 설정 문제였습니다. proxy_http_version 1.1 로 맞추니 되는군요
