### ISSUE TITLE
SVN commit 오류

### ISSUE THREAD

**Issue by sycop78** [yona-projects/yona#312]
yona 1.8.0을 설치하여 사용중입니다.
그런데 svn으로 사용중인데 svn commit를 하면 다음과 같은 에러가 나옵니다.

Web상 오류 [서버 오류가 발생하여 서비스를 이용할 수 없습니다]

Application.log Error : 

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.RuntimeException: java.io.IOException: No such file or directory]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]

**Comment by doortts** [comment]
@sycop78 
저장소가 svn으로 생성되었는지 확인 한 번 해주시겠어요?
위 에러는 git commit 이 동작하다가 실패한 로그로 보입니다.

**Comment by sycop78** [comment]
svn은 정상적으로 사용하고 있습니다
http로 이크립스에서 현재 사용하고 있고요

=> yona를 브라우저에서 사용할경우에만 에러가 나요..  
   [프로젝트] -> [코드] -> 파일선택 -> edit -> [저장] -> "서버 오류가 발생하여 서비스를 이용할 수 없습니다" 화면에 나옵니다.~~

git로 해보면 정상이긴해요. 
그리고 pc에서 그냥 hdb버전으로 실행해도 마찬가지에요 자바버전하고 상관있을까요
  1.8.0.152(현재 최신버전으로 해도 만찬가지로 그래요)

**Comment by doortts** [comment]
@sycop78 
아! SVN 프로젝트에서 웹에서 바로 파일 수정하는 경우 발생하는 오류이신거죠?

**Comment by sycop78** [comment]
네 맞습니다
