### ISSUE TITLE
Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server]

### ISSUE THREAD

**Issue by JeongJun-Lee** [yona-projects/yona#334]
원도우즈에서 잘 되던 yona-1.5 소스를 맥으로 옮겨왔습니다.
맥에서 yona-1.8로 git pull 한 후, 소스 빌드를 했습니다.
빌드에는 문제는 없었습니다. 실행시 다음과 같은 에러가 뜹니다.
빌드 클린 후 전체 빌드를 다시해야 할까요?

jjs-macbook-pro:yona comseong$ ../activator
[info] Loading project definition from /Users/comseong/dev/yona/activator-1.2.10-minimal/yona/project
[info] Set current project to yona (in build file:/Users/comseong/dev/yona/activator-1.2.10-minimal/yona/)
[yona] $ start
[info] Wrote /Users/comseong/dev/yona/activator-1.2.10-minimal/yona/target/scala-2.10/yona_2.10-1.8.1.pom
[info] Compiling 4 Java sources to /Users/comseong/dev/yona/activator-1.2.10-minimal/yona/target/scala-2.10/classes...
[info] Packaging /Users/comseong/dev/yona/activator-1.2.10-minimal/yona/target/scala-2.10/yona_2.10-1.8.1.jar ...
[info] Done packaging.

(Starting server. Type Ctrl+D to exit logs, the server will remain in background)
 
Play server process ID is 25556
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
Oops, cannot start the server.
Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
	at play.api.Configuration.reportError(Configuration.scala:743)
	at play.Configuration.reportError(Configuration.java:310)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:81)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/CodeComment.setAuthor(Lmodels/User;)V @2: invokevirtual
  Reason:
    Type 'models/User' (current frame, stack[1]) is not assignable to 'models/CodeComment'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'models/CodeComment', 'models/User' }
    stack: { 'models/CodeComment', 'models/User' }
  Bytecode:
    0x0000000: 2a2b b600 4db6 0051 2a2b b400 56b6 005a
    0x0000010: 2a2b b400 5db6 0060 b1                 

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:79)
	... 15 more

**Comment by doortts** [comment]
Java version을 알려주시겠어요?

```
java -version
```

**Comment by JeongJun-Lee** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by sjstyle** [comment]
제 생각에는 yona 1.5에 컴파일된 class 파일들과 yona 1.8에서 새롭게 컴파일 된 class 파일들이 섞여버려서 에러가 발생하는게 아닐까 생각됩니다. target 폴더 밑을 다 지운다음에 실행해 보시겠어요?

**Comment by comseong** [comment]
네 지우고 다시 빌드했더니 됩니다. 감사합니다. 그럼 닫겠습니다.

**Comment by JeongJun-Lee** [comment]
네 지운다음 재빌드했더니 됩니다. 그럼 닫겠습니다. 감사합니다.
