### ISSUE TITLE
H2 DB 버전 export 후 MariaDB 버전에서 import 오류

### ISSUE THREAD

**Issue by eventjang** [yona-projects/yona#336]
안녕하세요.
사내에서 초기에 간단히 사용하려고 H2 DB버전을 사용해보고 마음에 들어
전 프로젝트에 요나를 사용하려고 계획을 했고, MariaDB 를 사용하기로 했습니다.

기존 Data를 MariaDB로 옮기려고 export하였고,
새롭게 설치한 Yona에 Import를 하는데 에러가 나더군요.

무슨 문제일까요?
도움을 요청 드립니다.

[        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:84)
        at org.mariadb.jdbc.internal.protocol.AsyncMultiRead.call(AsyncMultiRead.java:12)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.springframework.transaction.TransactionSystemException: Could not roll back JDBC transaction; nested exception is java.sql.SQLException: Connection is closed!
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doRollback(DataSourceTransactionManager.java:290)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:849)
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:826)
        at data.DefaultExchanger.importData(DefaultExchanger.java:266)
        at data.DataService.importData(DataService.java:196)
        at controllers.SiteApp.importData(SiteApp.java:322)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$95$$anonfun$apply$95.apply(routes_routing.scala:2730)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$95$$anonfun$apply$95.apply(routes_routing.scala:2730)
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
        at Global$2.call(Global.java:264)
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57)
        at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
        at scala.Option.map(Option.scala:145)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLException: Connection is closed!
        at com.jolbox.bonecp.ConnectionHandle.checkClosed(ConnectionHandle.java:459)
        at com.jolbox.bonecp.ConnectionHandle.rollback(ConnectionHandle.java:1270)
        at org.springframework.jdbc.datasource.DataSourceTransactionManager.doRollback(DataSourceTransactionManager.java:287)
        ... 46 more]

**Comment by doortts** [comment]
@eventjang 
안녕하세요? export 와 import를 무엇으로 하셨나요?

h2 에서 MariaDB로 이동시에는 

https://github.com/yona-projects/yona-export

를 한 번 봐주세요

**Comment by eventjang** [comment]
@doortts 
안녕하세요. 채수원 선생님,
export / import 모두 요나 웹사이트의 관리자 메뉴에 들어가서 GUI를 통해 처리했습니다.

말씀하신 yona-export 를 설치했고,
npm start -- export
를 실행하니 오류가 발생하네요.

start exporting from hoyeon.jang/인터챗
오류 발생!! HTTP 응답코드를 확인하세요!  http://기존요나주소-_-api/v1/owners/hoyeon.jang/projects/인터챗/exports undefined undefined

undefined undefined 라고 나오는데 원인을 알 수 있을까요?

**Comment by eventjang** [comment]
@doortts 
안녕하세요. 채수원 선생님, 답변 고맙습니다.

export / import 모두 요나 웹사이트 > 서비스관리자 > 데이타 > export / import 로 했었습니다.

말슴하신 yona-export 설치하여 export명령어를 실행하니 아래와 같이 나옵니다.

start exporting from hoyeon.jang/인터챗
오류 발생!! HTTP 응답코드를 확인하세요!  http://요나서비스URL/-_-api/v1/owners/hoyeon.jang/projects/인터챗/exports 403 Forbidden

혹시나해서 위 URL을 브라우저에서 호출해보니 data가 잘나오는데요.
yona-export에서는 403 에러가 나는질 모르겠습니다.

**Comment by eventjang** [comment]
export 성공했습니다.
원인은 프로젝트명이 한글이어서 생기는 문제였네요.
프로젝트명을 영문으로 변경하니 해결 되었습니다.
이건 이슈로 등록 후 추후 수정해주시면 좋을 것 같다는 생각입니다.

고맙습니다.

**Comment by doortts** [comment]
@eventjang 
확인해주시고 테스트 까지 해주셔서 고맙습니다. 
해당 이슈는 yona-export 프로젝트에 이슈로 등록했습니다.
https://github.com/yona-projects/yona-export/issues/4
