### ISSUE TITLE
라벨 생성 오류

### ISSUE THREAD

**Issue by jisoon** [yona-projects/yona#34]
@doortts 님 안녕하세요 죄송스럽게도 또 이슈를 보고합니다.

기존에 있던 이슈 라벨을 삭제하고 다시 같은 분류 같은 이름으로 라벨 생성시 에러가 발생 하였습니다.

그이후 해당 분류에 대한 라벨을 추가 할때 에러가 발생 합니다.

간략한 에러 내용은 아래와 같습니다.

```
2016-04-09 11:20:58,963 - [ERROR] - from play in play-akka.actor.default-dispatcher-129
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]

2016-04-09 11:20:58,975 - [ERROR] - from application in play-akka.actor.default-dispatcher-129
```

분류나 라벨이 유니크 하지 않아서 생기는 에러 같은데 확인 부탁 드리겠습니다.

참고로 기존에 없는 새로운 분류의 라벨이나 삭제 발생 하지 않았던 분류에 라벨은 이상없이 잘 등록 됩니다.

**Comment by doortts** [comment]
혹시 화면에는 어떻게 오류가 표시되세요?

**Comment by jisoon** [comment]
@doortts 님  화면은 단순히 라벨을 생성할 수 없다고 나옵니다.

![default](https://cloud.githubusercontent.com/assets/11565410/14401863/f07ee056-fe5a-11e5-8970-29f45ec1793d.png)

혹 에러 로그 전문이 필요 하신가요?

**Comment by doortts** [comment]
@jisoon 네 에러로그 전문을 보여 주시면 더 좋을 것 같습니다. 만약 여기 공개하기 곤란한 문자열등이 있다면 메일로 주셔도 무방합니다. doortts@gmail.com 입니다.

**Comment by jisoon** [comment]
@doortts  에러 로그 전문 입니다.

```
2016-04-09 11:14:06,704 - [ERROR] - from play in play-akka.actor.default-dispatcher-132
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]

2016-04-09 11:14:06,706 - [ERROR] - from application in play-akka.actor.default-dispatcher-132


! @6pkjdmnai - Internal server error, for (POST) [/jisoonchoi/NEC/issue/labels] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Unique expecting 0 or 1 rows but got [2]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1278) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:908) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
@       
"application.log" 663L, 56676C                                                                                    434,2-9       66%
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted
```

**Comment by doortts** [comment]
![image](https://cloud.githubusercontent.com/assets/520523/14402525/82f703b0-fe73-11e5-85dc-10e37f2731bf.png)

이상하네요 원래 동일 라벨이 존재할 경우에는 위와 같은 메시지가 나와야 하거든요.

사용하시는 OS와 브라우저가 어떻게 되세요?

**Comment by jisoon** [comment]
@doortts  제가 사용 중인건 Windows10 , 크롬입니다. 아 참고로 다시 말씀 드리면 해당 라벨을 삭제 한 후 동일한 분류 동일한 이름으로 다시 생성 하려고 할 때 최초 발생을 했구요 그다음에는 해당 분류의 라벨은 추가가 안되더군요

a(분류) - 1(이름) 삭제 -> a - 1 재 등록 -> error 발생 이후
a - 2 추가 error 발생 

이런 시나리오 입니다.

**Comment by doortts** [comment]
삭제하면 화면에서 안보이는데 다시 등록하려면 발생하시는거죠?
그리고
https://github.com/yona-projects/yona/releases/tag/v1.0.1 
이걸로 테스트 중이신거죠?

크롬브라우져이시면 개발자 도구를 여셔서 
![image](https://cloud.githubusercontent.com/assets/520523/14402636/cca05950-fe76-11e5-9414-0363c663409d.png)
캐시를 한번 disable 시켜보고 해봐주세요.

개발자도구는 메뉴 ctrl-shift-i 아니면 메뉴에서 선택해 주시고요.

**Comment by jisoon** [comment]
@doortts 
네 1.0.1 로 하고 있습니다. 일단 말씀해 주신것 처럼 크롬으로 다시 테스트 해보겠습니다.

**Comment by doortts** [comment]
그럼 이슈에 가서 한번 라벨을 선택할때 삭제한 라벨이 보이는지 확인해주시겠어요? 
아니면 지운건 제외하고 나머지가 보이는지도요.

**Comment by doortts** [comment]
혹시 텔레그램 쓰시면 https://telegram.me/joinchat/A-3VSTyfpszxjOcW2IzR2g 에 접속하셔서 같이 한번 보시는것도 어떨까 싶습니다.

**Comment by jisoon** [comment]
헉.. 저도 그러고 싶은데 지금 파견 나와서 6시넘어서 자리를 비워 줘야 하거든요 ㅜㅜ
필요 하시면 로그 파일 메일로 보내 드릴까요?

**Comment by doortts** [comment]
로그로는 충분히 확인되었습니다.
제가 윈도우즈에 설치해서 한번 테스트 해 보겠습니다.
설치도 윈도우즈에 되어 있는거고 MariaDB사용하시는것 맞으신가요?

**Comment by jisoon** [comment]
앗 오해의 소지가 클라이언트가 윈도우고요 

서버는 센트오에스 입니다 마리아 디비 거요

**Comment by doortts** [comment]
그렇다면 시간되실때 repo.yona.io 에서도 테스트 해 봐 주시겠어요?
저는 로컬이나 repo.yona.io 에서 해당 현상을 겪진 않았거든요.
repo.yona.io 도 centos 6 + maria db 입니다.

**Comment by jisoon** [comment]
넵 저도 디비를 보고 싶은데 외부오 포트를 열지 않아서 ㅜㅜ

확인 하고 말씀 드리겠습니다.

**Comment by jisoon** [comment]
@doortts 

원인은 issue_label_category 테이블에 해당 분류가 남아 있어서 발생한 오류 였습니다.
아마도 1.0.0 에 라벨 삭제 버그가 있었던것 같습니다.

해당 row 를 삭제 하고 테스트 했을때 이상 없이 동작 하였습니다.

고생 하셨습니다.
