### ISSUE TITLE
특정 commit을 보려고 하면 "서버 오류가 발생하여 서비스를 이용할 수 없습니다"

### ISSUE THREAD

**Issue by yoonionh** [yona-projects/yona#348]
특정 커밋을 보려고 하면 에러메시지가 발생하면서, 첫 페이지로 강제 이동하게 되네요.

아래는 로그인데, Git이름은 의도적으로 가렸습니다.

고수님들의 의견 부탁 드립니다. ^^;

! @76bpg8ga9 - Internal server error, for (GET) [/yoonionh/[??GitName??]/commit/c01c5da] ->

play.api.Application$$anon$1: Execution exception[[MissingObjectException: Missing unknown 084f2c05c58a3321c2575cb728759bab050a4ce1]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 084f2c05c58a3321c2575cb728759bab050a4ce1
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:158) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:173) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:144) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.Repository.open(Repository.java:295) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at playRepository.GitRepository.getFileDiffs(GitRepository.java:1648) ~[yona.yona-1.8.0.jar:1.8.0]
[info] a./yoonionh/[??GitName??]/commit/c01c5da - 0:0:0:0:0:0:0:1 - - [19/Dec/2017:20:28:04 +0900] "GET /yoonionh/[??GitName??]/commit/c01c5da HTTP/1.1" 500 - "http://localhost:9000/yoonionh/[??GitName??]/code/master" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" -
[info] a./messages.js - 0:0:0:0:0:0:0:1 - yoonionh [19/Dec/2017:20:28:04 +0900] "GET /messages.js HTTP/1.1" 200 - "http://localhost:9000/yoonionh/[??GitName??]/commit/c01c5da" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" 5ms [info] a./user/usermenuTabContentList - 0:0:0:0:0:0:0:1 - yoonionh [19/Dec/2017:20:28:04 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "http://localhost:9000/yoonionh/[??GitName??]/commit/c01c5da" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36" 26ms

**Comment by doortts** [comment]
@yoonionh 
이크. 이 이슈는 놓치고 있던 이슈네요. 
```
Missing unknown 084f2c05c58a3321c2575cb728759bab050a4ce1
```

이 부분으로 보아 특정 브랜치나 파일등이 서버에서 삭제된것으로 보입니다. 혹시 서버에서 직접 파일작업등을 하신 적이 있나요?

**Comment by doortts** [comment]
@yoonionh 음. 혹시 서브모듈이 포함된 git 프로젝트 이신가요?

관련이슈 https://github.com/yona-projects/yona/issues/272

**Comment by doortts** [comment]
@yoonionh submodule 을 사용하고 계신가요?

**Comment by yoonionh** [comment]
안녕하세요 yoonionh 입니다.
맞습니다. submodule 이용하고 있습니다.


회사 망에서 yona를 적용하고 있는데.
회사 망에서 email이나 github가 차단되어 있어서 답변을 빨리 드리지 못했네요.

꾸준히 메일 주시고 챙겨 주셔서 고맙습니다. ^^

2018-03-08 21:33 GMT+09:00 Suwon Chae <notifications@github.com>:

**Comment by doortts** [comment]
@yoonionh 이제 서브모듈을 지원할 시점이 왔나봐요. 이 이슈가 strikeout( 3명이 동일 이슈로 신고)이 되었거든요.

**Comment by yoonionh** [comment]
하핫 신경써 주신다니
감사합니다 ㅎㅎ


2018년 3월 11일 (일) 오후 11:09, Suwon Chae <notifications@github.com>님이 작성:
