### ISSUE TITLE
Yona DB연결 파일 수정 후 실행 에러

### ISSUE THREAD

**Issue by pcappli63** [yona-projects/yona#352]
다음과 같은 에러 코드가 뜹니다. 이유가 무엇일까요?

[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play -
Oops, cannot start the server.
@76i3n8mhk: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
@pcappli63 
안녕하세요? 해당 오류는 최초 설치시라면 설치도중 DB작업에 오류가 있었거나 운영중이셨단 DB 내용을 직접 수정하셨거나 하셨을때 발생하는 오류입니다.

에러를 보기 전 상황을 좀 더 설명해 주시겠어요?
