### ISSUE TITLE
[버그] 최초 코드 푸쉬 후 서버 오류가 발생하여 서비스를 이용할 수 없습니다

### ISSUE THREAD

**Issue by thorwel** [yona-projects/yona#363]
서버 사양
Fedora 28
yona 1.9.0
MariaDB 10.2.31

몇몇 비슷한 증상이 있는것 같아서 이슈 트래킹 체크해봤었는데요,

몇가지 테스트 방법으로 확인된 사항 알려드립니다.

일단 YONA 오류코드는
MissingObjectException
500 에러로 떨어집니다.

1. 최초 PUSH 코드가 일정 개수 초과할 경우
- 최초 코드 커밋 내용 확인하려고 할 때 해당 오류가 발생합니다.
- 해당 증상은 다른 프로젝트 생성 후 소규모 코드 푸쉬 후에서는 발생하지 않았습니다.
- 한번에 읽어 올 수 있는 제한이 있는 것인지는 알 수 없으나, 소규모는 파일 변동사항이 읽힙니다.

2. 최초 PUSH 후 커밋 내용은 확인 할 수 없으나, 수정 후 2번째 comit 부터는 변경 사항 확인 가능
- 500에러가 발생하다가도, 2번째 커밋부터는 정상적으로 내용을 확일 할 수 있습니다.
- 초기 커밋 내용도 비교로 확인 할 수 있었던 걸로 추정 할 때,
- DB내의 코드가 꼬인 부분이 아닌 것으로 추정됩니다.

심지어 1번의 경우에는 처음에는 확인이 가능했습니다.
약간의 시간이 지난 후 확인 하려고 할 때, 발생한 문제입니다. (서버 재시작 X)

**Comment by doortts** [comment]
@thorwel 안녕하세요? https://repo.yona.io 에서도 재현여부 혹시 테스트 한 번 해주실 수 있을까요?

**Comment by doortts** [comment]
@thorwel 아 그리고 git 프로젝트인가요? 아니면 SVN 이신가요?

**Comment by thorwel** [comment]
@doortts git 프로젝트입니다. 테스트는 가입후 진행해보겠습니다.

**Comment by doortts** [comment]
@yoonionh 음. 혹시 서브모듈이 포함된 git 프로젝트 이신가요?

관련이슈 https://github.com/yona-projects/yona/issues/272

서버 오류 로그 전체메시지 첨부가 가능하실까요?

**Comment by thorwel** [comment]
@doortts 혹시나 도움이 될지 몰라 자세한 사내 서버 사양 기입합니다.
git 서버로만 사용할 용도라 사양이 좋지는 않습니다.


CPU | 4x Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
8GB RAM

Fedora release 28 (Twenty Eight)
10.2.13-MariaDB MariaDB Server
nginx version: nginx/1.12.1

JAVA
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

NGINX로 80 포트 프록시 패스 중입니다.
config 첨부합니다.

`server {
    listen       80;
    server_name domain;
    client_max_body_size 2G;
    location / {
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://localhost:9000;
        proxy_redirect http://localhost:9000/ http://domain/;
    }
}`

**Comment by thorwel** [comment]
@doortts 서브 모듈이 딱 하나 포함되어 있긴합니다.

문제는 처음에는 잘보이다가 안보여서...

오류 메시지도 첨부드립니다.

`[error] play - Cannot invoke the action, eventually got an error: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 3a884be196886a6438cf899edbcdb63880634a3c
[error] application - 

! @7780enflc - Internal server error, for (GET) [/*****/bd2a6c0a6055e9884a14d9d6277508b4ac496d6e?branch=refs%2Fheads%2Fmaster] ->

play.api.Application$$anon$1: Execution exception[[MissingObjectException: Missing unknown 3a884be196886a6438cf899edbcdb63880634a3c]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 3a884be196886a6438cf899edbcdb63880634a3c
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:158) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:173) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:144) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.lib.Repository.open(Repository.java:295) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at playRepository.GitRepository.getFileDiffs(GitRepository.java:1664) ~[yona.yona-1.9.0.jar:1.9.0]`
