### ISSUE TITLE
요나를 실행하려고 했더니 Query is : ALTER TABLE attachment DROP CONSTRAINT IF EXISTS ck_attachment_contai ner_type [ERROR:1064, SQLSTATE:42000] 발생합니다.

### ISSUE THREAD

**Issue by wifiz** [yona-projects/yona#365]
안녕하세요. 기존에 1.8.1 쓰다가 1.9.0 버전이 나와 소스를 받아 빌드하여 실행하였더니 아래처럼 에러가 발생하네요..
그래서 다시 깃에서 1.8.1 버전을 땡겨서 실행했더니..여전히 같은 에러가 발생해서 요나를 실행하지 못하고 있습니다.
혹시 해결 방법이 있을까요?..

Play server process ID is 2320
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - (conn:42567) You have an error in your SQL syntax; check the manu
al that corresponds to your MariaDB server version for the right syntax to use n
ear 'CONSTRAINT IF EXISTS ck_attachment_container_type' at line 1
Query is : ALTER TABLE attachment DROP CONSTRAINT IF EXISTS ck_attachment_contai
ner_type [ERROR:1064, SQLSTATE:42000]
Oops, cannot start the server.
@7788da3lk: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.sc
ala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scal
a:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Ev
olutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Ev
olutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:3
30)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$a
pply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531
)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evol
utions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evol
utions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)

        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.sca
la:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.sca
la:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:
289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:
284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
@wifiz 안녕하세요? 소스 기반으로 실행을 하셨으면 사용하시는 MariaDB 버전으로 인해 발생하는 문제입니다.
이번 1.9는 MariaDB 기본 바이너리 버전을  2개 배포하고 있습니다. 10.1 용과 10.2

해결방법은 두 가지가 있는데요
우선 DB에 접속하셔서
```
delete from play_evolutions where id = 20;
```
을 실행하신 다음

방법1
---
MariaDB 버전을 10.2 로 업그레이드 한다

방법2
---
(MariaDB 버전을 10.1 을 유지하는 경우) 
conf/evolutions/20.sql을 삭제 한다

그럼 해보시고 알려주세요.

**Comment by wifiz** [comment]
@doortts 감사합니다. 덕분에 해결됐습니다.

**Comment by venuspink** [comment]
저도 같은 문제로 삽질했었구요.. 요 이슈보고 해결했습니다.
마리아디비 10.1에서 끙끙대지 마시고 10.2로 재설치 하면 잘 됩니다.
ubuntu18 + yona1.11.0 + mariaDB-10.2
