### ISSUE TITLE
[로그] 에러로그가 보여 올려봅니다

### ISSUE THREAD

**Issue by siro012** [yona-projects/yona#369]
알람이 표시가 되지 않아 로그를 찾아보던 중 아래와 같은 부분이 있어 올려봅니다.
혹시 설정할 수 있는 방법이 있는지 문의 드립니다.

018-03-12 16:50:49,726 - [ERROR] - from akka.actor.OneForOneStrategy in application-akka.actor.default-dispatcher-80 
There is no HTTP Context available from here.
java.lang.RuntimeException: There is no HTTP Context available from here.
	at play.mvc.Http$Context.current(Http.java:34) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.mvc.Controller.session(Controller.java:72) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at controllers.UserApp.getUserFromSession(UserApp.java:643) ~[yona.yona-1.9.0.jar:1.9.0]
	at controllers.UserApp.currentUser(UserApp.java:630) ~[yona.yona-1.9.0.jar:1.9.0]
	at models.NotificationEvent.getProjectCommitReceivers(NotificationEvent.java:1018) ~[yona.yona-1.9.0.jar:1.9.0]
	at models.NotificationEvent.afterNewCommits(NotificationEvent.java:1186) ~[yona.yona-1.9.0.jar:1.9.0]
	at actors.CommitsNotificationActor.doReceive(CommitsNotificationActor.java:38) ~[yona.yona-1.9.0.jar:1.9.0]
	at actors.PostReceiveActor.onReceive(PostReceiveActor.java:55) ~[yona.yona-1.9.0.jar:1.9.0]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167) ~[com.typesafe.akka.akka-actor
_2.10-2.3.4.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97) ~[com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na
]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.
akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar
:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-librar
y-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4
.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-libra
ry-2.10.4.jar:na]

**Comment by kenu** [comment]
메일 답장 기능 테스트 중 비슷한 로그를 봤습니다.
```
[info] mail.in - {Subject: Re: [playground] 이메일 답장 시 yona에 등록되지 않는 문제 (#8), From: {=?UTF-8?B?7ZeI6rSR64Ko?= <****@hellonature.net>}, To: {Yona <****@hellonature.net>,****@gmail.com,****@hellonature.net}} SUCCESS 1225ms
[info] application - Cannot comment a resource of unknown type: issue_comment/9908
[warn] application - Failed to process an email: {Subject: Re: [playground] 이메일 답장 시 yona에 등록되지 않는 문제 (#8), From: {Kenu Heo <****@gmail.com>}, To: {****+HN/playground/issue_post/16@hellonature.net}}
java.lang.RuntimeException: There is no HTTP Context available from here.
	at play.mvc.Http$Context.current(Http.java:34) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.mvc.Controller.session(Controller.java:72) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at controllers.UserApp.getUserFromSession(UserApp.java:643) ~[yona.yona-1.9.0.jar:1.9.0]
	at controllers.UserApp.currentUser(UserApp.java:630) ~[yona.yona-1.9.0.jar:1.9.0]
	at models.NotificationEvent.getMandatoryReceivers(NotificationEvent.java:1009) ~[yona.yona-1.9.0.jar:1.9.0]
[info] mail - "Re: [playground] 이메일 답장 시 yona에 등록되지 않는 문제 (#8)" [Kenu Heo <kenu.heo@gmail.com>]
[error] mail.in - {Subject: Re: [playground] 이메일 답장 시 yona에 등록되지 않는 문제 (#8), From: {Kenu Heo <****@gmail.com>}, To: {****+HN/playground/issue_post/16@hellonature.net}} FAILED 4615ms
java.lang.RuntimeException: There is no HTTP Context available from here.
	at play.mvc.Http$Context.current(Http.java:34) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.mvc.Controller.session(Controller.java:72) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at controllers.UserApp.getUserFromSession(UserApp.java:643) ~[yona.yona-1.9.0.jar:1.9.0]
	at controllers.UserApp.currentUser(UserApp.java:630) ~[yona.yona-1.9.0.jar:1.9.0]
	at models.NotificationEvent.getMandatoryReceivers(NotificationEvent.java:1009) ~[yona.yona-1.9.0.jar:1.9.0]
[info] application - Start the Email Receiving Thread
```

@doortts 확인 부탁드립니다.
감사합니다. ^^;

**Comment by doortts** [comment]
@kenu 오류메시지 내용 확인했습니다.

**Comment by doortts** [comment]
@siro012 @kenu  이 부분을 수정한 v1.9.1 가 릴리즈 되었습니다.
