### ISSUE TITLE
[오류] 이슈등록시 오류발생

### ISSUE THREAD

**Issue by yongseokleecom** [yona-projects/yona#375]
요나에서 이슈등록시 오류가 발생합니다.
* 버전: 1.9.1 (H2)

![image](https://user-images.githubusercontent.com/12702163/38186277-1e7c4c0c-368d-11e8-9621-51d400b77840.png)

```
[error] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [3]
[error] application -

! @77f0cd268 - Internal server error, for (POST) [/testo/test/issues/latest] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Unique expecting 0 or 1 rows but got [3]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [3]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1278) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:908) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:189) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at models.UserProjectNotification.findOne(UserProjectNotification.java:94) ~[yona.yona-1.9.1.jar:1.9.1]
        at models.UserProjectNotification.isEnabledNotiType(UserProjectNotification.java:135) ~[yona.yona-1.9.1.jar:1.9.1]

```

**Comment by yongseokleecom** [comment]
@doortts 도움 감사합니다 !
1.9.1 H2 기준으로 해결했습니다. 다른 버전은 해결방법이 상이 할 수 있습니다.

## 현상
이슈 등록시 오류발생

## 원인
USER_PROJECT_NOTIFICATION 중복 키로 인한 문제

## 해결방법
1. 중복행 조회 
아래 쿼리를 실행했을때 조회가 되면 중복행이 존재하는 것으로 
2번 쿼리를 실행하여 중복행을 삭제합니다.
```sql
SELECT
  NOTIFICATION_TYPE,
  PROJECT_ID,
  USER_ID,
  COUNT(*)
FROM USER_PROJECT_NOTIFICATION
GROUP BY NOTIFICATION_TYPE, PROJECT_ID, USER_ID
HAVING COUNT(*) > 1;
```
2. 중복행 삭제 
```sql
DELETE FROM USER_PROJECT_NOTIFICATION
WHERE USER_PROJECT_NOTIFICATION.ID IN (
  SELECT P1.ID FROM USER_PROJECT_NOTIFICATION P1, USER_PROJECT_NOTIFICATION P2
  WHERE P1.ID > P2.ID
  AND P1.USER_ID = P2.USER_ID
  AND P1.PROJECT_ID = P2.PROJECT_ID
  AND P1.NOTIFICATION_TYPE = P2.NOTIFICATION_TYPE
);
```

## 재발방지
USER_PROJECT_NOTIFICATION 테이블이 유니크키가 있어야하는데, 
제가 운영하는 요나에서는 유니크키가 없어서 발생했습니다.
유니크키를 추가하여 동일 이슈가 발생하지 않게합니다.
```sql
ALTER TABLE USER_PROJECT_NOTIFICATION
  ADD CONSTRAINT UQ_USER_PROJECT_NOTIFICATION_1 UNIQUE (USER_ID, PROJECT_ID, NOTIFICATION_TYPE);
```
