### ISSUE TITLE
@6pmdhhdd9: Database 'default' is in an inconsistent state!

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#38]
DB에 테이블은 정상적으로 생성된것을 확인 하였습니다.

DB버전은 다음과 같습니다.
+-------------------------+---------------------------------+
| Variable_name           | Value                           |
+-------------------------+---------------------------------+
| innodb_version          | 5.6.28-76.1                     |
| protocol_version        | 10                              |
| slave_type_conversions  |                                 |
| version                 | 10.1.12-MariaDB-1~trusty        |
| version_comment         | mariadb.org binary distribution |
| version_compile_machine | x86_64                          |
| version_compile_os      | debian-linux-gnu                |
| version_malloc_library  | system jemalloc                 |
| version_ssl_library     | OpenSSL 1.0.1f 6 Jan 2014       |
| wsrep_patch_version     | wsrep_25.13                     |
+-------------------------+---------------------------------+

yona를 시작하면 다음과 같은 에러가 발생 합니다. 이게..뭐가 문제일까요?
VM에서 잘 되는거 확인하고 실서버에서 업그레이드 작업 하려고 하는데 발생하네요.

Oops, cannot start the server.
@6pmdhhdd9: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
이 에러는 말 그래도 DB 상태가 불일치 되는 상황이라는 설명인데요 버전 몇에서 몇으로 업그레이드인가요?

**Comment by pokev25** [comment]
1.0.1 신규 설치라고 보시면 됩니다. 0.8.2 쓰다가 

mariadb에 새로 관리자 생성 하려고 새버전 실행 시키면서 발생 하는거라서요.

혹시나 DB생성 과정에서 뭔가 문제가 생긴건지도 모르니 새로 DB생성 해서 테스트 해보겠습니다.

**Comment by pokev25** [comment]
지우고 다시 생성하니 잘 됩니다. !!
