### ISSUE TITLE
Active Directory LDAP 연결 성공하신 분 계신가요?

### ISSUE THREAD

**Issue by k-enzy** [yona-projects/yona#390]
안녕하세요.

active directory와 연결 설정 해봤는데 

invalid credentials 에러가 나네요.

혹시 성공하시분 계신가요?

에러로그는 아래와 같습니다.

=========================================
2018-05-16 15:39:59,407 - [INFO] - from application in play-akka.actor.default-dispatcher-6 
getProperUsernameGuessing: CN=userxxxxxxx,OU=companyxxxxxDC=domainxxxxxx,DC=com

2018-05-16 15:39:59,434 - [WARN] - from application in play-akka.actor.default-dispatcher-6 
login failed 
[LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1 ]

**Comment by doortts** [comment]
저희 Active Directory (LDAP) 쓰고 있습니다.

우선 관련 에러는 아래와 같다고 하고요
https://social.technet.microsoft.com/Forums/office/en-US/c98f3569-072a-4677-9b89-635ed2b8dffc/ldap-error-code-49-8009030c-ldaperr-dsid0c0903a9-comment-acceptsecuritycontext-error-data?forum=winserverDS

baseDN 과 distinguishedNamePostfix 설정을 확인해보셔야 하는데요

로그인 하실때 id로는 CN에 해당하는 id로 로그인하거나 아니면 full  email 주소를 쓰시고
PW는 LDAP 로그인에 사용하는 본인의 PW를 이용해서 로그인해보세요.

**Comment by k-enzy** [comment]
빠른답변 감사합니다. :)

일단 제가 설정하는쪽 active directory 의CN에 해당하는 value값이 한글이름으로 되어 있고 

baseDN 설정 등은 다른 시스템(gitlab, redmine)에서 사용한 설정이었습니다.

distinguishedNamePostfix에는 어떤 내용이 들어가야 하나요?
active directory의 distinguishedName항목에 CN만 빼고 입력 하였습니다.

full email 사용시에는 아래와 같은 로그 메세지를 보입니다.

==========================================

2018-05-16 16:53:07,649 - [INFO] - from application in play-akka.actor.default-dispatcher-11 
getProperUsernameGuessing: userxxxxxxx@domainxxxxxx.com

2018-05-16 16:53:07,662 - [INFO] - from application in play-akka.actor.default-dispatcher-11 
filter: (mail=userxxxxxxx@domainxxxxxx.com)

2018-05-16 16:53:07,664 - [DEBUG] - from application in play-akka.actor.default-dispatcher-11 
l: null

2018-05-16 16:53:07,666 - [ERROR] - from play in play-akka.actor.default-dispatcher-11 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2018-05-16 16:53:07,679 - [ERROR] - from application in play-akka.actor.default-dispatcher-11 


! @7818k8alb - Internal server error, for (POST) [/users/login] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at controllers.UserApp.authenticateWithLdap(UserApp.java:1160) ~[yona.yona-1.9.1.jar:1.9.1]
	at controllers.UserApp.loginByAjaxRequest(UserApp.java:302) ~[yona.yona-1.9.1.jar:1.9.1]
	at controllers.UserApp.login(UserApp.java:169) ~[yona.yona-1.9.1.jar:1.9.1]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$79$$anonfun$apply$79.apply(routes_routing.scala:2637) ~[yona.yona-1.9.1.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$79$$anonfun$apply$79.apply(routes_routing.scala:2637) ~[yona.yona-1.9.1.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at Global$2.call(Global.java:274) ~[yona.yona-1.9.1.jar:na]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted

==================================================

쓰다보니 active directory에 설정되어 있는 도메인과 메일주소의 도메인이 다르네요.

일단 내부 active directory의 설정이 일반적이지 않아서 몇가지 더 시도해 본 후 결과와 함께 이슈는 닫도록 하겠습니다.

감사합니다.

**Comment by doortts** [comment]
application.conf LDAP 설정에서 아래 내용이 기본 값일텐데요 
distinguishedNamePostfix 은 baseDN과 다르게 distinguishedName 에서 최종 CN 값을 제외한 나머지를 말합니다. 기본 LDAP 항목이름 에 속하는 이름은 아니지만 LDAP 설정의 간소화를 위해 만들어 놓았습니다.

```
    baseDN = "ou=scientists,dc=example,dc=com"
    # If your ldap service's distinguishedName is 'CN=username,OU=user,DC=abc,DC=com', postfix is 'OU=xxx,DC=abc,DC=com'
    distinguishedNamePostfix = "OU=user,DC=abc,DC=com"
    loginProperty = "sAMAccountName"
    displayNameProperty = "displayName"
    userNameProperty = "CN"
    emailProperty = "mail"
```
이메일이나 CN값, 두 가지 방법으로 로그인을 지원하기 위해 각각 설정하신 AD의 property 값과 일치시켜 주셨는지 추가로 확인해보셔요.

특히 loginProperty, displayNameProperty, userNameProperty, emailProperty 네 가지 항목의 property가 설정하신 부분과 일치하는지도 봐 보셔요.

**Comment by k-enzy** [comment]
답변 감사합니다.

반쪽은 성공한것 같습니다.

active diretory의 CN이 한글이름으로 설정 되어 있어서 
sAMAccountName 으로 로그인 하고 싶었는데 그건 성공 하지 못했습니다.

설정은 아래와 같이 했습니다.

loginProperty를 sAMAccountName 에서 CN으로 변경하였습니다.

===========================ldap {
    host = "boss1.vi-nyl.com"
    # default: ldap.port=389, ldaps.port=636
    port = 389
    # protocol: ldap or ldaps. If you want to use SSL/TLS, use 'ldaps'
    protocol = "ldap"
    baseDN = "OU=VINYL-USER,DC=vi-nyl,DC=com"
    # If your ldap service's distinguishedName is 'CN=username,OU=user,DC=abc,DC=com', postfix is 'OU=xxx,DC=abc,DC=com'
    distinguishedNamePostfix = "OU=작업완료,OU=VINYL-USER-eC,OU=VINYL-USER,DC=vi-nyl,DC=com"
    loginProperty = "CN"
    displayNameProperty = "displayName"
    userNameProperty = "CN"
    emailProperty = "mail"
    options {
      # If your LDAP configuration support email login
      useEmailBaseLogin = false
      fallbackToLocalLogin = false
      # If your LDAP configuration support English Name attribute
      englishNameAttributeName = "givenName"
    }
}

**Comment by doortts** [comment]
다행이네요. 그럼 이메일로 로그인을 하시는건가요? 아니면 어떻게 로그인 하는걸로 정하셨어요?

**Comment by k-enzy** [comment]
CN이 이름으로 되어있어서 이름으로  입력하고 로그인 하게 됩니다 ^^
