### ISSUE TITLE
yona 실행 불가

### ISSUE THREAD

**Issue by bethleekor** [yona-projects/yona#399]
1. mariadb 10.2 버전 / yona 1.9릴리즈
2. bin/yona 실행시 아래와 같은 오류 발생

database를 지우고 해도 계속 아래와 같은 에러가 나오는 데요.
어떻게 하면 정상적으로 서버를 구동할 수 있을까요?

```
Play server process ID is 17930
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'clob,
date                      timestamp,
num_of_comments           integer,
mi' at line 4
Query is:
create table issue (
id                        bigint not null,
title                     varchar(255),
body                      clob,
date                      timestamp,
num_of_comments           integer,
milestone_id              bigint,
author_id                 bigint,
author_login_id           varchar(255),
author_name               varchar(255),
state                     integer,
project_id                bigint,
assignee_id               bigint,
constraint ck_issue_state check (state in (0,1,2)),
constraint pk_issue primary key (id)) [ERROR:1064, SQLSTATE:42000]
Oops, cannot start the server.
@78ccpd4mi: Database 'default' is in an inconsistent state!
	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
	at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
	at scala.Option.map(Option.scala:145)
	at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)

```

**Comment by doortts** [comment]
안녕하세요? 우선 MariaDB 버전에 맞는 파일을 다운로드 하셨나 확인해주세요.
1.9부터 10.2 와 10.1 버전이 각각 따로 배포되고 있거든요.

**Comment by bethleekor** [comment]
넵 버전 때문이었네요. 도움주셔서 감사합니다.
