### ISSUE TITLE
메일서버 설정관련 문의드립니다.

### ISSUE THREAD

**Issue by kjs1227** [yona-projects/yona#404]
구글메일을 발송메일서버로 사용하지않아서 메일서버정보를 입력했는데 에러가 나네요.
설정이 뭐가 잘못된건지 문의드립니다.

application.conf 설정

# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gmail smtp
smtp.host = 222.231.45.120
smtp.port = 25
smtp.ssl = false
smtp.auth = false
smtp.starttls = true
smtp.user = "webmaster@canon-ci.co.kr"
# Be careful!!! Not to leak password
smtp.password = "password"
smtp.domain = ""
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

에러로그
2018-07-09 17:33:07,531 - [ERROR] - from play in play-akka.actor.default-dispatcher-8 
Cannot invoke the action, eventually got an error: org.apache.commons.mail.EmailException: Sending the email to the following server failed : 222.231.45.120:25

2018-07-09 17:33:07,540 - [ERROR] - from application in play-akka.actor.default-dispatcher-8 

! @78gbh7m1k - Internal server error, for (POST) [/sites/mail] ->

play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : 222.231.45.120:25]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : 222.231.45.120:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at controllers.SiteApp.sendMail(SiteApp.java:71) ~[yona.yona-1.9.1.jar:1.9.1]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$102$$anonfun$apply$102.apply(routes_routing.scala:2821) ~[yona.yona-1.9.1.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$102$$anonfun$apply$102.apply(routes_routing.scala:2821) ~[yona.yona-1.9.1.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at Global$2.call(Global.java:274) ~[yona.yona-1.9.1.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.9.1.jar:1.9.1]
	at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39) ~[yona.yona-1.9.1.jar:1.9.1]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted
Caused by: javax.mail.AuthenticationFailedException: No authentication mechansims supported by both server and client
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:760) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Transport.send0(Transport.java:194) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Transport.send(Transport.java:124) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	... 48 common frames omitted
설정부분을 잘못한건지 궁금하네요.

**Comment by kjs1227** [comment]
답변감사드립니다. smtp.starttls = false 변경하고 테스트해보았으나 같은 에러를 발행하네요.

**Comment by doortts** [comment]
password 부분은 다른 걸로 수정하신거죠?

**Comment by strcpyy** [comment]
~
smtp.host = 222.231.45.120
smtp.port = 25
smtp.ssl = false
smtp.auth = false
smtp.starttls = true
~

@kjs1227 위에 설정하신 항목을 보니 메일서버가 TLS 로 구성되어있을 때의 옵션으로 세팅하신것 같습니다만, 혹시 smtp.port = 25 번이 메일서버에서 TLS 로 설정되어 있는건가요? TLS 는 기본적으로 587 포트를 사용합니다. 
간단히 말씀드리자면,
SSL 사용 시 : smtp.ssl = true / smtp.startssl = false 로 설정
TLS 사용 시 : smtp.ssl = false / smtp.startssl = true 로 설정
위와 같이 smtp.ssl 과 smtp.starttls 옵션은 상호 배타적으로 적용되어야 합니다.

우선 사용하시는 메일서버가 SSL 을 사용하는지 TLS 를 사용하는지 확인 부탁드립니다.
만약 SSL 을 사용한다면 smtp.auth 항목과 smtp.starttls 항목은 주석으로 처리하시거나 지워주시고,
TLS 를 사용하신다면 포트 번호를 다시한번 확인해주세요 :)

**Comment by kjs1227** [comment]
답변 감사드립니다. 위에서 말씀하신데로 다 적용해봤는데 똑같은 에러를 발생하네요. 
기존자바단에서 MailUtil.java에 25번 포트를 사용하고 있고, 아이디/패스워드는 사용하지 않았습니다.
메일서버는 SSL/TLS설정이 안된걸로 파악되는데 어떻게 확인이 가능할까요? 염치불구하고 물어봅니다.

**Comment by strcpyy** [comment]
@kjs1227 님
ID, PW 를 사용하지 않으셨다는건 build.sbt 파일에 smtp.user 와 smtp.password 항목에 값을 설정 안하셨다는 말씀이신가요? 설정하신 항목들에 대한 정확한 정보를 다시 올려주실 수 있나요?

추가적으로 아래와 같이 한 번 설정을 다시 해보시겠어요?

```text
# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
=====================================================
smtp.host = 222.231.45.120 // 혹은 "222.231.45.120"
smtp.port = 25
smtp.auth = true
smtp.starttls = true
smtp.user = "admin@yourDomain.com"
smtp.password = "yourPassword"
smtp.domain = ""
smtp.mock = true
smtp.archive.size = 5
=====================================================
#end
```

**Comment by project-yona** [comment]
올려주신 설정에는 password 를 지정하신것처럼 보여지는데요 ="" 으로 해보세요

2018년 7월 11일 (수) 오후 4:55, kjs1227 <notifications@github.com>님이 작성:

**Comment by kjs1227** [comment]
smtp.mock = false으로 변경하고 테스트해보니 아래 에러로그가뜨네요.
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: 22.231.45.120, port: 25
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]
Caused by: java.net.SocketTimeoutException: connect timed out

**Comment by strcpyy** [comment]
@kjs1227 님,

```text
~
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: 22.231.45.120, port: 25
at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[javax.mail.mail-1.4.5.jar:1.4.5]
~
```

올려주신 에러로그를 보니 맨 첫 줄 *Caused by: javax.mail.MessagingException: Could not connect to SMTP host: 22.231.45.120, port: 25* 에서 *SMTP host: 22.231.45.120* 과 같은 메세지가 나오는데 smtp.host 항목에 IP 를 잘못 넣으신것 아닌가요? 처음 문의 주셨던 글에는 smtp.host = 222.231.45.120 이렇게 되어있어서 혹시나해서 여쭤봅니다..

**Comment by kjs1227** [comment]
@strcpyy 님 답변 감사드려요.
앗~그랬네요. 수정하고 다시 해보았는데 smtp.mock = false시 이런 에러가나네요.

Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : 222.231.45.120:25
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
Caused by: javax.mail.AuthenticationFailedException: No authentication mechansims supported by both server and client
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:760) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]

smtp.mock = true시에는 
[debug] application - mock email send:
From: webmaster@canon-ci.co.kr
To:   jsk1815@kico.co.kr
Date: Fri Jul 13 09:07:59 KST 2018
Subj: TEST
cont:
테스트메일발송
이렇게 로그에는 에러없고 메일이 발송되지않고있는 상황이네요.

**Comment by strcpyy** [comment]
@kjs1227 님,

```text
~
Caused by: javax.mail.AuthenticationFailedException: No authentication mechansims supported by both server and client
~
```

로그를 보니 위와 같이 authenrication 관련해서 에러가 출력되셨네요, 해당 에러의 원인은 여러가지가 될 수 있는데요 번거로우시겠지만, 우선 *application.conf* 파일의 **smtp.auth** 항목을 **false** 로 바꿔보시고 다시 한 번 확인해주실 수 있나요?

**Comment by doortts** [comment]
기본적으로 mock 설정은 테스트를 위한 가상환경이라 true 로 하면 실제 발송이 되지 않습니다.

그런데 궁금한점이 
```
smtp.auth = true
smtp.starttls = true
```
이런 부분은 기본 옵션에 포함되어 있지 않았을텐데 어디를 참조해서 추가하신건가요?

기본 설정은 
https://github.com/yona-projects/yona/blob/master/conf/application.conf.default#L179

이렇거든요.

**Comment by kjs1227** [comment]
@doortts 님.

https://github.com/yona-projects/yona/wiki/Yona-%EB%A9%94%EC%9D%BC%EC%84%9C%EB%B2%84-%EC%84%A4%EC%A0%95

TLS설정 참조해서 smtp.auth = true/ smtp.auth = true 추가했습니다.

**Comment by doortts** [comment]
@kjs1227 아! TLS를 설정하고 싶으셨던거군요?

그렇다면 기본 포트 25번으로 TLS 적용이 안되실것같아요.
메일 서버를 설정하신 내용들은 TLS인 부분과 아닌부분등이 혼용되어 있어서 잘 동작하지 않는 것 같습니다.
```
smtp.port = 25 
```
25번 포트는 non ssl/tls 기본 포트라 서버자체를 특별히 덮어쓰기로 설정해 놓지 않는 이상 tls 설정으로 동작하지 않을 것 같습니다.

TLS를 사용하시려면 메일서버의 TLS/SSL 설정 port를 먼저 확인해 보셔야 할 것 같습니다.

위 링크의 설정페이지에서 보시듯 gmail은 465, tls 는 587을 사용하고 있습니다.
