### ISSUE TITLE
메일 발송이 안됩니다.

### ISSUE THREAD

**Issue by torrhet** [yona-projects/yona#406]
# Mailbox Service
# ~~~~~~~~~~~~~~~
#
# Mailbox Service fetches and process mails from IMAP server. For example, if
# the service fetches an email to a project, it posts the email as an issue of
# the project.
#
# If you want to use this feature, your IMAP server has to be configured to
"conf/application.conf" 393L, 12669C                          188,14        47%
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gmail smtp
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = "xxxx.xxx@gmail.com"
# Be careful!!! Not to leak password
smtp.password = "xxxxxx"(특수문자 없음)
smtp.domain = gmail.com
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

메일 발송 메뉴에서 위 설정으로 아래와 같은 에러가 나네요.

> [info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
> [error] play - Cannot invoke the action, eventually got an error: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
> [error] application -
> 
> ! @78gnnjo62 - Internal server error, for (POST) [/sites/mail] ->
> 
> play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : smtp.gmail.com:465]]
>         at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
>         at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
>         at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
>         at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
>         at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
> Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
>         at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
>         at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
>         at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
>         at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
>         at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
> Caused by: javax.mail.AuthenticationFailedException: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv4
> 534-5.7.14 _izzD2XKFxqWPtdYxoxg0tOCpOshaxXidzAY_ph1wyo6bNiqk5_FSQojqIqb5vlfwfP-S9
> 534-5.7.14 Pt3lkmzmniNvy-QChPojXURwuaziGlWUjg4LEpE6EhEaYurDRX5TX-43C_OLaIoUY3c1s5
> 534-5.7.14 F_8hWpLUe0oDrufbA5DbRSKNQDPXO42BpUSkmJIlfAtFCYKEj3ZbXEyXzSJ5_5H03NM-qh
> 534-5.7.14 ThkrS6_leygXTmHeuP1hmo5t0IYSc> Please log in via your web browser and
> 534-5.7.14 then try again.
> 534-5.7.14  Learn more at
> 534 5.7.14  https://support.google.com/mail/answer/78754 j75-v6sm376449pfj.102 - gsmtp
> 
>         at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823) ~[javax.mail.mail-1.4.5.jar:1.4.5]
>         at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756) ~[javax.mail.mail-1.4.5.jar:1.4.5]
>         at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673) ~[javax.mail.mail-1.4.5.jar:1.4.5]
>         at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
>         at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
> [info] a./sites/mail - 14.63.100.31 - - [11/Jul/2018:00:58:38 +0000] "POST /sites/mail HTTP/1.1" 500 - "http://xxxx:9000/sites/mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" -
> [info] a./messages.js - 14.63.100.31 - admin [11/Jul/2018:00:58:38 +0000] "GET /messages.js HTTP/1.1" 200 - "http://xxxxt:9000/sites/mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 46ms
> [info] a./user/usermenuTabContentList - 14.63.100.31 - admin [11/Jul/2018:00:58:38 +0000] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "xxxx:9000/sites/mail" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 26ms

**Comment by torrhet** [comment]
구글 인증 시도 확인 문제였네요. 처리 됐습니다.
