### ISSUE TITLE
[질문] 메일서버 설정 (메일서버 익명 접속)

### ISSUE THREAD

**Issue by pyj2731** [yona-projects/yona#409]
안녕하세요. 

요나를 설치하고 메일서버를 연동하는 중입니다. 
메일서버는 사내에서 공통으로 사용하는 메일서버로 익명 접속으로 설정되어 있습니다. 

요나에서 smtp.auth 옵션을 false로 설정하면 메일서버에 익명 접속으로 되는지 알고 싶습니다. 
혹시 익명 접속을 위한 다른 옵션이 있다면 알고 싶습니다. 

아래는 설정한 옵션입니다. 

smtp.host = x.x.x.x 
smtp.port = 25
#smtp.ssl = false
smtp.auth = false
smtp.user = admin
# Be careful!!! Not to leak password
smtp.password = "비밀번호"
smtp.domain = "domain.com"
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

**Comment by doortts** [comment]
저희도 익명으로 사용가능한 발송 (SMTP)서버를 운영하고 있는데 설정이 아래와 같습니다.
아래 설정에서 실제 서버명과 도메인명은 my-company 와 my-company-domain 으로 대체하였습니다.

```
# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gamil smtp
smtp.host = backendsmtp.my-company.com
smtp.port = 25
smtp.ssl = false
smtp.user = yona
# Be careful!!! Not to leak password
#smtp.password =  ""
smtp.domain = my-company-domain.com
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

```

**Comment by pyj2731** [comment]
빠른 답변 감사합니다. 

알려주신 옵션으로 설정했으나 다음과 같은 에러가 발생합니다. 

요나 버전 : 1.10.0

<테스트 방법>
1. 설정 수정 
2. 관리자 계정으로 접속 
3. 사이트 관리 > 메일 발송 

<설정>
smtp.host = 서버 아이피
smtp.port = 25
smtp.ssl = false
smtp.user = yona
# Be careful!!! Not to leak password
#smtp.password = ""
smtp.domain = 회사 도메인
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

<에러>
play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : 10.1.2.70:25]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : 10.1.2.70:25
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
	at controllers.SiteApp.sendMail(SiteApp.java:71) ~[yona.yona-1.10.0.jar:1.10.0]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$106$$anonfun$apply$106.apply(routes_routing.scala:2881) ~[yona.yona-1.10.0.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$106$$anonfun$apply$106.apply(routes_routing.scala:2881) ~[yona.yona-1.10.0.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at Global$2.call(Global.java:274) ~[yona.yona-1.10.0.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.10.0.jar:1.10.0]
	at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39) ~[yona.yona-1.10.0.jar:1.10.0]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Transport.send0(Transport.java:194) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at javax.mail.Transport.send(Transport.java:124) ~[javax.mail.mail-1.4.5.jar:1.4.5]
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
	... 48 common frames omitted

**Comment by doortts** [comment]
```
smtp.user = yona
```
이 부분은 만드신 smtp 계정으로 지정하셔야 할 것 같아요.
그래서 오류가

```
Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful
```
발생하는듯 합니다.

혹시 아예 계정도 필요 없이 발송되는 환경인가요? (그게 가능하던가..)

**Comment by pyj2731** [comment]
요나 설치 서버에서 SMTP 서버로 텔넷 접속 후 테스트 시에는 
아무런 계정 정보를 입력하지 않고 성공 했습니다.

혹시 몰라서 smtp.user 를 'Administrator' 로 변경해서 시도 해봤으나 위와 같은 에러가 발생하네여.

**Comment by doortts** [comment]
```
smtp.auth = false
# smtp.user = admin
```
로 추가해서 해보시면 어떤가요?

**Comment by pyj2731** [comment]
말씀해주신데로 옵션을 변경 해보았으나 동일한 에러 로그가 발생합니다.

<수정 옵션>
smtp.host = 서버아이피
smtp.port = 25
smtp.ssl = false
smtp.auth = false
#smtp.user = admin
smtp.domain = 회사도메인
#smtp.password = ""
smtp.mock = false
smtp.archive.size = 5

**Comment by doortts** [comment]
뭔가 오묘하네요. 이쯤되면 SMTP 서버쪽 로그도 확인이 필요한 것 같습니다.

**Comment by dojunghun** [comment]
저희도 동일하게 익명접속하는 smtp 서버의 문제로 오류를 격고 있습니다.
거의 2주째 해결방법을 못찾고 있습니다.
저희 설정은 아래와 같으며 질문자와 동일한 오류 메세지가 출력됩니다.

smtp.host = x.x.x.x
smtp.port = 25
smtp.auth = false
smtp.ssl = false
smtp.starttls = false
smtp.user = "webmaster@xxx.xxx"
smtp.password = ""
smtp.domain = ""
smtp.mock = false
smtp.archive.size = 5

해결 방법 아시는 분 계시면 공유 부탁드리겠습니다.
감사합니다.

**Comment by doortts** [comment]
@dojunghun 
smtp.user 로 `webmaster@xxx.xxx`로 지정된 아이디가 smtp 유저로 존재하나요?
보통 유저는 @ 을 잘 붙이지는 않아서요.

**Comment by pyj2731** [comment]
사내 SMTP 서버 로그를 확인하려 했으나 .. 보안 문제로 거절 당했습니다...
SMTP 서버 담당자쪽에서는 다른데서는 잘 쓰고 있어 문제될 게 없다는 입장이라 .. 
혹시 다른 확인 방법은 없을지 .. 확인 부탁드립니다.

**Comment by doortts** [comment]
![image](https://user-images.githubusercontent.com/520523/43053419-81a19724-8e67-11e8-8097-8364d536302c.png)
이 부분은 어떤 뜻인가요? 테스트를 어디서 하셨어요? 사이트 관리의 메일 발송을 말씀하시는건가요?

**Comment by doortts** [comment]
아. 텔넷으로 직접 하셨다는 의미시군요! :(

**Comment by doortts** [comment]
이런경우라면 SMTP 메일 클라이언트를 하나 정하셔서 그걸로 SMTP 서버 연결테스트 해주시겠어요?https://www.thunderbird.net 썬더 버드 라던가 아니면 아웃룩으로요.

**Comment by pyj2731** [comment]
말씀해주신 썬더 버드 설치 후 SMTP 연동 테스트 진행 후 정상 동작 확인했습니다. 

썬더버드 버전 :  52.9.1

<썬더 버드 SMTP 설정>
상세 설명 : 없음
서버 이름 : SMTP서버 ip 입력
포트 : 25
보안 연결 : 없음
인증 방식 : 인증 없음

위와 같이 설정 했으며 메일 정상 전송 확인 했습니다.

**Comment by doortts** [comment]
확인 고맙습니다. 그렇다면 이제 endgame 들어가시죠. 

다른 옵션은 다 지우시고
```
smtp.host = x.x.x.x
smtp.port = 25
smtp.auth = false
smtp.user = "webmaster@xxx.xxx"
smtp.mock = false
smtp.archive.size = 5
```
이 설정 아니면

```
smtp.host = x.x.x.x
smtp.port = 25
smtp.user = "webmaster@xxx.xxx"
smtp.mock = false
smtp.archive.size = 5
```

아니면

```
smtp.host = x.x.x.x
smtp.port = 25
smtp.mock = false
smtp.archive.size = 5
```

이 설정만으로 테스트 해봐주시겠어요?

썬더버드 테스트 하실때 smtp.user 따로 안 넣으셨죠?

**Comment by pyj2731** [comment]
세가지 설정 모두 테스트 해봤습니다. 

결과는 모두 동일하게 같은 에러가 발생합니다. 

Caused by: javax.mail.AuthenticationFailedException: 535 5.7.3 Authentication unsuccessful

썬더 버드 테스트할때 smtp.user  값을 따로 입력하진 않았습니다.

**Comment by pyj2731** [comment]
썬더버드 설정화면은 다음과 같습니다. 

![image](https://user-images.githubusercontent.com/12161792/43249632-265014b8-90f6-11e8-96ce-d1abba0a7504.png)

<요나 재시작 시 에러>
업데이트 관련 ssl 에러가 나긴 합니다. 해당 에러랑 관련이 있을까여?

2018-07-26 13:35:43,949 - [WARN] - from application in application-akka.actor.default-dispatcher-5 
Failed to fetch the latest Yobi version to update
org.eclipse.jgit.api.errors.TransportException: https://github.com/yona-projects/yona: cannot open git-upload-pack
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:221) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at models.YobiUpdate.fetchVersionToUpdate(YobiUpdate.java:102) ~[yona.yona-1.10.0.jar:1.10.0]
	at models.YobiUpdate.refreshVersionToUpdate(YobiUpdate.java:82) ~[yona.yona-1.10.0.jar:1.10.0]
	at models.YobiUpdate$1.run(YobiUpdate.java:63) ~[yona.yona-1.10.0.jar:1.10.0]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/yona-projects/yona: cannot open git-upload-pack
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:527) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:290) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:198) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	... 11 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.Handshaker.processLoop(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.Handshaker.process_record(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:1.8.0_171]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:1.8.0_171]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_171]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_171]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:1.8.0_171]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[na:1.8.0_171]
	at org.eclipse.jgit.transport.http.JDKHttpConnection.getResponseCode(JDKHttpConnection.java:98) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.util.HttpSupport.response(HttpSupport.java:190) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:465) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
	... 13 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[na:1.8.0_171]
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[na:1.8.0_171]
	at sun.security.validator.Validator.validate(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[na:1.8.0_171]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[na:1.8.0_171]
	... 30 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[na:1.8.0_171]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[na:1.8.0_171]
	at java.security.cert.CertPathBuilder.build(Unknown Source) ~[na:1.8.0_171]
	... 36 common frames omitted

**Comment by pyj2731** [comment]
혹시 몰라 아래 와 같이 설정 후 테스트도 진행했는데 동일하게 에러가 났습니다.

<설정>
smtp.host = 10.1.2.70
smtp.port = 25
smtp.auth = false
smtp.user = yjpark3
smtp.mock = false
smtp.archive.size = 5

<이메일 발송 화면>
![image](https://user-images.githubusercontent.com/12161792/43250193-c2200ab4-90f7-11e8-8c26-315c543ca386.png)

위 이미지에 보내는 메일 주소를 보면 yjpark3 이 들어가고 @127.0.0.1 로 입력하지 않은 주소가 들어가 있습니다. 
혹시 SMTP 익명 설정의 경우에 SMTP 주소가 자동으로 127.0.0.1로 설정될수도 있나여?

**Comment by doortts** [comment]
127.0.0.1이 보이는 건 smtp.domain 을 설정하지 않으셔서 127.0.0.1 로 처리된 것으로 보입니다.
시작시에 업데이트 확인을 하지 못하는 오류는 아마 외부망과 단절시켜놓은 서버라 그런것이 아닌가 싶고요.

저희도 SMTP를 비인증에 pw를 사용하지 않는 환경이고 동일 설정으로 잘 사용하고 있기때문에 어느 부분에서 차이가 있는지 파악이 어렵네요.

위 메일발송 화면에서 본인에게 테스트 이메일을 발송해 보시겠어요?

smtp.user = yjpark3
smtp.domain = 회사메일 도메인 

으로 지정하신다음에요.

**Comment by pyj2731** [comment]
다음 설정으로 테스트 해봤지만 동일한 에러 입니다. 

<설정>
smtp.host = 10.1.2.70
smtp.port = 25
smtp.auth = false
smtp.user = yjpark3
smtp.domain = 회사 메일 도메인
smtp.mock = false
smtp.archive.size = 5

혹시 몰라 썬더 버드 SMTP 설정에서 사용자 정보를 제거하고 실행했으나 동일하게 메일이 잘 전송됩니다.
![image](https://user-images.githubusercontent.com/12161792/43251342-9b369f96-90fa-11e8-9118-a52cf15e7df7.png)

**Comment by doortts** [comment]
음 뭔가 막 속상하네요. 
SMTP 서버 쪽에서 오류 내용이 뭔지 알려주면 좋겠는데 말예요.

**Comment by pyj2731** [comment]
내일 다시 한번 SMTP 서버 로그 확인 요청해봐야 겠네여 .. 

썬더버드나 텔넷은 다 되는데 .. 요나만 안되니 저도 속상하네여.
