### ISSUE TITLE
글 수정시 '서버오류가 발생하여 서비스를 이용할 수 없습니다.' 라는 메시지가 노출됩니다.

### ISSUE THREAD

**Issue by SongPaul** [yona-projects/yona#412]
특정 글 수정시 

> 서버오류가 발생하여 서비스를 이용할수 없습니다.

라는 메시지가 노출되고 글이 수정되지 않아 로그를 확인해보니 아래와 같은 쿼리 에러가 납니다.
`Caused by: java.sql.SQLSyntaxErrorException: (conn:35338) Unknown column 'issue_comment_id' in 'where clause'
Query is: select t0.id c0 from n4user t0 where (issue_comment_id) in (?,?) , parameters [2050,2051]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:134) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:239) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeQuery(MariaDbClientPreparedStatement.java:178) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryFetchIds.findIds(CQueryFetchIds.java:166) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.query.CQueryEngine.findIds(CQueryEngine.java:56) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 63 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Unknown column 'issue_comment_id' in 'where clause'
Query is: select t0.id c0 from n4user t0 where (issue_comment_id) in (?,?) , parameters [2050,2051]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:172) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbClientPreparedStatement.executeInternal(MariaDbClientPreparedStatement.java:230) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	... 67 common frames omitted
`

n4user 테이블에는 'issue_comment_id' 컬럼이 없는데 혹시 언제 업데이트가 되면서 추가되었던 건가요. ?

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases 에서 b 버전 빌드를 다시 내려 받아서 실행해주시겠어요?

**Comment by SongPaul** [comment]
@doortts 오 잘되는 것 같습니다 감사합니다.
