### ISSUE TITLE
1.9 에서 1.10 업그레이드 후 댓글있는 이슈 수정시 오류발생

### ISSUE THREAD

**Issue by kimtrasche** [yona-projects/yona#413]
안녕하세요.
요나를 만들어주셔서 정말 감사합니다.
현재 까지 아주아주 잘 사용중이고, 얼마전 신규 버전이 릴리즈 되어,
기존  YONA 디렉터리에서 덮어씌우는 형식으로 업그레이드를 진행하였습니다.

그런데, 문제가 하나 있습니다.
1.10 버전에서 작성된 이슈에서 댓글이 달리게 되면, 이후에 이슈 본문 수정 시 오류가 발생합니다.

검토부탁드립니다.

> 사용환경 : 리눅스
> 사용버전 : yona-h2-v1.10.0-bin.zip
> 기존버전 : yona-h2-v1.9.1.bin.zip
> 업그레이드 방법 : 신규버전 전체를 압축을 풀고 yona 디렉터리에 overwrite

아래는 server.log 입니다.

``` sh
[info] mail.out - "[일일업무현황] ㅁㄴㅇㄻㄴㅇㄻㅇㄴㄹ (#46)" [Yona <yona.mail@gmail.com>, =?UTF-8?B?6rmA6rK97YOc?= <kyungtaekim@shinsegae.com>]
[info] a./2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform - 10.174.182.75 - 171928 [18/Jul/2018:10:29:55 +0900] "GET /2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform HTTP/1.1" 200 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 51ms
[info] a./.css - 10.174.182.75 - 171928 [18/Jul/2018:10:29:55 +0900] "GET /2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/labels.css HTTP/1.1" 304 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 3ms
[info] a./messages.js - 10.174.182.75 - 171928 [18/Jul/2018:10:29:55 +0900] "GET /messages.js HTTP/1.1" 200 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 7ms
[debug] play - Unable to parse part of media range header 'application/json, text/javascript, */*; q=0.01'
[info] a./-_-api/v1/owners/2%ED%8C%8C%ED%8A%B8/projects/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/assignableUsers?query=174100&type=loginId - 10.174.182.75 - 171928 [18/Jul/2018:10:29:56 +0900] "GET /-_-api/v1/owners/2%ED%8C%8C%ED%8A%B8/projects/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/assignableUsers?query=174100&type=loginId HTTP/1.1" 200 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 4ms
[info] a./user/usermenuTabContentList - 10.174.182.75 - 171928 [18/Jul/2018:10:29:56 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 12ms
[info] a./files?containerType=ISSUE_POST&containerId=322 - 10.174.182.75 - 171928 [18/Jul/2018:10:29:56 +0900] "GET /files?containerType=ISSUE_POST&containerId=322 HTTP/1.1" 200 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 3ms
[warn] application - PersistenceException: Query threw SQLException:Column "ISSUE_COMMENT_ID" not found; SQL statement:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)  [42122-176]
Bind values:[null]
Query was:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)


[error] play - Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: Query threw SQLException:Column "ISSUE_COMMENT_ID" not found; SQL statement:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)  [42122-176]
Bind values:[null]
Query was:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)


[error] application -

! @78imp9ekk - Internal server error, for (POST) [/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/edit] ->

play.api.Application$$anon$1: Execution exception[[PersistenceException: Query threw SQLException:Column "ISSUE_COMMENT_ID" not found; SQL statement:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)  [42122-176]
Bind values:[null]
Query was:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)

]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: Query threw SQLException:Column "ISSUE_COMMENT_ID" not found; SQL statement:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)  [42122-176]
Bind values:[null]
Query was:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)


        at com.avaje.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:834) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.query.CQueryEngine.findIds(CQueryEngine.java:79) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.query.DefaultOrmQueryEngine.findIds(DefaultOrmQueryEngine.java:41) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.OrmQueryRequest.findIds(OrmQueryRequest.java:237) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1366) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Column "ISSUE_COMMENT_ID" not found; SQL statement:
select t0.id c0 from n4user t0 where (issue_comment_id) in (?)  [42122-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[com.h2database.h2-1.3.176.jar:1.3.176]
        at org.h2.message.DbException.get(DbException.java:178) ~[com.h2database.h2-1.3.176.jar:1.3.176]
        at org.h2.message.DbException.get(DbException.java:154) ~[com.h2database.h2-1.3.176.jar:1.3.176]
        at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:148) ~[com.h2database.h2-1.3.176.jar:1.3.176]
        at org.h2.expression.ConditionIn.optimize(ConditionIn.java:81) ~[com.h2database.h2-1.3.176.jar:1.3.176]
[info] a./2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/edit - 10.174.182.75 - - [18/Jul/2018:10:30:00 +0900] "POST /2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/edit HTTP/1.1" 500 - "http://10.253.43.34:9000/2%ED%8C%8C%ED%8A%B8/%EC%9D%BC%EC%9D%BC%EC%97%85%EB%AC%B4%ED%98%84%ED%99%A9/issue/38/editform" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" -
```

**Comment by doortts** [comment]
초기 빌드에 오류가 섞여 들어가 있었습니다.
https://github.com/yona-projects/yona/issues/412#issuecomment-405435306
를 참고하셔서 b 버전을 내려 받아서 다시 실행하시면 될거에요.

**Comment by kimtrasche** [comment]
정말정말 감사합니다. 다시 설치하니까 해결되었습니다
