### ISSUE TITLE
1.9->1.11 업그레이드 후 로그아웃 상태 오류

### ISSUE THREAD

**Issue by kenu** [yona-projects/yona#471]
안녕하세요. 1.9.0 -> 1.11.0 의 application.conf 만 바꾸고 실행했습니다.

동작을 잘 하는데, 로그아웃 상태에서만 NullPointerException 이 발생합니다.
http://yona.okdevtest.net

```
[error] play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException
[error] application - 

! @7a11bkkpl - Internal server error, for (GET) [/user/usermenuTabContentList] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at models.Organization.findAllOrganizations(Organization.java:188) ~[yona.yona-1.11.0.jar:1.11.0]
	at views.html.index.myOrganizationList$.apply(myOrganizationList.template.scala:98) ~[yona.yona-1.11.0.jar:1.11.0]
	at views.html.common.usermenu_tab_content_list$.apply(usermenu_tab_content_list.template.scala:38) ~[yona.yona-1.11.0.jar:1.11.0]
	at views.html.common.usermenu_tab_content_list$.render(usermenu_tab_content_list.template.scala:50) ~[yona.yona-1.11.0.jar:1.11.0]
	at views.html.common.usermenu_tab_content_list.render(usermenu_tab_content_list.template.scala) ~[yona.yona-1.11.0.jar:1.11.0]
[info] a./user/usermenuTabContentList - 127.0.0.1 - - [17/Nov/2018:14:49:03 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 500 - "http://yona.okdevtest.net/projects" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" -
[debug] application - Path where we are coming from (/user/usermenuTabContentList) is different than the login URL (/)
```

<img width="560" alt="2018-11-17 2 49 13" src="https://user-images.githubusercontent.com/718691/48657728-c6f94480-ea78-11e8-8e3e-bad4027423eb.png">

항상 감사하게 잘 쓰고 있습니다. 👍

**Comment by kenu** [comment]
서버를 nohup 재시작하니 에러 발생이 멈췄습니다. 이슈는 닫아놓겠습니다.
