### ISSUE TITLE
실행시 sql 에러 (MariaDB 10.3)

### ISSUE THREAD

**Issue by gibson57** [yona-projects/yona#483]
서버사양 : centos7, mariadb 10.3, java jre 8

bin/yona 실행시 아래처럼 [ERROR:1064, SQLSTATE:42000] 에러가 뜨구요

> Play server process ID is 24898
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'clob,
date                      timestamp,
num_of_comments           integer,
mi' at line 4
Query is:
create table issue (
id                        bigint not null,
title                     varchar(255),
body                      clob,
date                      timestamp,
num_of_comments           integer,
milestone_id              bigint,
author_id                 bigint,
author_login_id           varchar(255),
author_name               varchar(255),
state                     integer,
project_id                bigint,
assignee_id               bigint,
constraint ck_issue_state check (state in (0,1,2)),
constraint pk_issue primary key (id)) [ERROR:1064, SQLSTATE:42000]
Oops, cannot start the server.
@7aa17h8kp: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:296)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:496)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

과거 이슈를 검색해보니 utf8mb4과 관련된 문제이고 innodb_file_format = barracuda  설정을 하면 해결이 된다고 하였는데

mariadb 10.3 버전부터는 더이상 이 설정 지원이 안됩니다.

https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-103/
> Remove deprecated variables innodb_file_format, innodb_file_format_check, innodb_file_format_max and innodb_large_prefix.

10.2로 설치해보고 싶으나 다운그레이드도 어찌해야할지 모르겠고 참 난감한 상황입니다.

도와주세요~!

**Comment by doortts** [comment]
MariaDB 10.3 버전이 어떻게 되시나요?

**Comment by gibson57** [comment]
> MariaDB 10.3 버전이 어떻게 되시나요?

MariaDB 10.3.11 Stable 버젼입니다~

**Comment by gibson57** [comment]
해결하였습니다. 

문제는 h2버젼으로 설치해서 그런거네요... 일반버젼으로 설치하니 sql 에러 없이 작동합니다.

혼란을 드려 죄송합니다~
