### ISSUE TITLE
yona git commit history, java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by zapieah** [yona-projects/yona#505]
yona git에서 commit history를 보면서 commit번호를 누르면 아래와 같이 java.lang.OutOfMemoryError: Java heap space 가 발생합니다.
JAVA_OPTS를 4기가 8기가 잡아줘도 동일하게 발생을 합니다.
해당 부분에 대한 해결책이 있을까요?

Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:207)
	at play.twirl.api.BufferedContent.buildString(Content.scala:42)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
[ERROR] [03/28/2019 15:30:54.559] [play-akka.actor.default-dispatcher-3] [ActorSystem(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:207)
	at play.twirl.api.BufferedContent.buildString(Content.scala:42)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.twirl.api.BufferedContent.buildString(Content.scala:38)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:39)
	at play.twirl.api.BufferedContent$$anonfun$buildString$1.apply(Content.scala:38)

[info] play - Shutdown application default Akka system.
[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332) ~[na:1.8.0_171]
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[na:1.8.0_171]
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[na:1.8.0_171]
	at java.lang.StringBuilder.append(StringBuilder.java:136) ~[na:1.8.0_171]
	at scala.collection.mutable.StringBuilder.append(StringBuilder.scala:207) ~[org.scala-lang.scala-library-2.10.4.jar:na]
[warn] application - Failed!! User uploaded temporary files clean-up action failed!
javax.persistence.PersistenceException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:143) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468) ~[com.h2database.h2-1.3.176.jar:1.3.176]
[warn] application - Error occurred while sending notification mails
javax.persistence.PersistenceException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:143) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468) ~[com.h2database.h2-1.3.176.jar:1.3.176]

**Comment by doortts** [comment]
- OS 환경이 어떻게 되세요?
- 윈도우라면 프로세스 매니저에서 리눅스라면 top 으로 실제 할당된 메모리가 얼마인지 확인 가능할까요?

**Comment by doortts** [comment]
- 추가로 소스코드 폴더의 전체 사이즈가 어떻게 될까요?

**Comment by zapieah** [comment]
다시 리붓하고하니 JAVA_OPT 4g로 세팅시 정상 동작하고 있네요.
문제는 leak이 발생하는 부분이 있는지... 가끔 이렇게 발생을 하네요.
leak부분은 다시 확인 해봐야할듯합니다.
OS 우분투이고 용량은 각 브랜치별 1.6G 2.5G 정도 됩니다.

**Comment by doortts** [comment]
혹시 가능하시다면 repo.yona.io 에 프로젝트 만드셔서 테스트 해 봐 주시겠어요?

**Comment by zapieah** [comment]
음 일단 제가더 테스트를 해봐야할듯합니다.
추가로 외부로 코드 업로드는 어려운 환경입니다.
감사합니다.

**Comment by doortts** [comment]
네 고맙습니다!
