### ISSUE TITLE
윈도우에서 my.cnf 경로를 알고 싶습니다.

### ISSUE THREAD

**Issue by kimothink** [yona-projects/yona#507]
현재 C:\Program Files\MariaDB 10.1 및 그 안에 etc폴더를 만들어 사용중인데 계속 max key length is 767 bytes 오류가 나옵니다.  윈도우에서는 어느 폴더에 저장하면 되나요?

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/wiki/MariaDB-%EC%84%A4%EC%B9%98-%28Windows%29 를 참고해보시겠어요?

**Comment by kimozex** [comment]
rror] play - (conn:13) Specified key was too long; max key length is 767 bytes
Query is : create table label (
id                        bigint auto_increment not null,
category                  varchar(255),
name                      varchar(255),
constraint uq_label_1 unique (category,name),
constraint pk_label primary key (id))
row_format=compressed, key_block_size=8 [ERROR:1071, SQLSTATE:42000]
Oops, cannot start the server.
@7bepm7em9: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by kimothink** [comment]
> https://github.com/yona-projects/yona/wiki/MariaDB-%EC%84%A4%EC%B9%98-%28Windows%29 를 참고해보시겠어요?

rror] play - (conn:13) Specified key was too long; max key length is 767 bytes
Query is : create table label (
id                        bigint auto_increment not null,
category                  varchar(255),
name                      varchar(255),
constraint uq_label_1 unique (category,name),
constraint pk_label primary key (id))
row_format=compressed, key_block_size=8 [ERROR:1071, SQLSTATE:42000]
Oops, cannot start the server.
@7bepm7em9: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by kimothink** [comment]
![image](https://user-images.githubusercontent.com/7092443/55766216-9c06a000-5aae-11e9-8f62-ab3b1bc54cc5.png)

![image](https://user-images.githubusercontent.com/7092443/55766228-a7f26200-5aae-11e9-9394-be4916db413a.png)

무슨 문제일까요?

**Comment by kimothink** [comment]
![image](https://user-images.githubusercontent.com/7092443/55766708-c78a8a00-5ab0-11e9-8ad7-f0a1494fa064.png)

**Comment by kimothink** [comment]
완료되었습니다. drop 하고 다시 한후 이상이 생겨 마리아디비를 삭제후 다시 했습니다. 감사합니다.
