### ISSUE TITLE
이메일 설정

### ISSUE THREAD

**Issue by cheekee** [yona-projects/yona#510]
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = myId@company.co.kr
smtp.password = "myPassword"
smtp.domain = ""
smtp.mock = false
smtp.archive.size = 5

알림을 이메일로 받기 위하여 설정한 내용입니다.
admin 메일발송해보면 "메일을 발송하였습니다" 라고 뜨지만, 실제 메일이 오진 않습니다.
위의 설정 이외에 또 설정해야할 것이 있나요.

로그에 특별히 오류가 나지 않아 레벨을 변경하여 확인해보니 아래와 같은 내용이었습니다.
2019-04-17 09:51:27,969 - [WARN] - from application in application-akka.actor.default-dispatcher-5 
Failed!! User uploaded temporary files clean-up action failed!
javax.persistence.PersistenceException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findList(DefaultExpressionList.java:173) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at models.Attachment$3.removeUserTemporaryFiles(Attachment.java:461) ~[yona.yona-1.12.0.jar:1.12.0]
	at models.Attachment$3.run(Attachment.java:450) ~[yona.yona-1.12.0.jar:1.12.0]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:687) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:640) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:807) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:810) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:143) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:427) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at com.jolbox.bonecp.ConnectionHandle.setAutoCommit(ConnectionHandle.java:1292) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPApi$$anon$1.onCheckOut(DB.scala:329) ~[com.typesafe.play.play-jdbc_2.10-2.3.10.jar:2.3.10]
	at com.jolbox.bonecp.AbstractConnectionStrategy.postConnection(AbstractConnectionStrategy.java:75) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.AbstractConnectionStrategy.getConnection(AbstractConnectionStrategy.java:92) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.getConnection(BoneCP.java:553) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:131) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.getConnection(EbeanPlugin.java:157) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:312) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 42 common frames omitted

2019-04-17 09:51:27,981 - [WARN] - from application in application-akka.actor.default-dispatcher-5 
Error occurred while sending notification mails
javax.persistence.PersistenceException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at models.NotificationMail$1.sendMail(NotificationMail.java:137) ~[yona.yona-1.12.0.jar:1.12.0]
	at models.NotificationMail$1.run(NotificationMail.java:113) ~[yona.yona-1.12.0.jar:1.12.0]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:687) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:640) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:807) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:810) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:178) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:154) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.message.DbException.get(DbException.java:143) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1468) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1443) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:427) ~[com.h2database.h2-1.3.176.jar:1.3.176]
	at com.jolbox.bonecp.ConnectionHandle.setAutoCommit(ConnectionHandle.java:1292) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPApi$$anon$1.onCheckOut(DB.scala:329) ~[com.typesafe.play.play-jdbc_2.10-2.3.10.jar:2.3.10]
	at com.jolbox.bonecp.AbstractConnectionStrategy.postConnection(AbstractConnectionStrategy.java:75) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.AbstractConnectionStrategy.getConnection(AbstractConnectionStrategy.java:92) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.getConnection(BoneCP.java:553) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:131) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.getConnection(EbeanPlugin.java:157) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:312) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 41 common frames omitted

**Comment by doortts** [comment]
user 에 양쪽으로 따옴표 붙여주시고
gmail을 smtp로 사용하실거라면 domain 은 gmail.com 로 지정해 주세요

제 생각엔 smtp.user 에 @ 표시 때문이 아닌가 싶습니다만.

**Comment by doortts** [comment]
예)
```
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = "myId@company.co.kr"
smtp.password = "myPassword"
smtp.domain = gmail.com
smtp.mock = false
smtp.archive.size = 5
```

**Comment by cheekee** [comment]
예전에도 설정해보았고, 방금도 복붙으로 설정해봤지만 똑같습니다.

오전에 이슈를 변경했더니
메일이 발송된 로그가 있긴한데 받지는 못했습니다. 로그 내용입니다. 도움이 될까요.

2019-04-17 10:37:44,086 - [DEBUG] - from application in application-akka.actor.default-dispatcher-3 
mock email send:
From: =?UTF-8?B?7IaQ7KKF66y0?= <yona.mail@gmail.com>
To:   Yona <yona.mail@gmail.com>
BCC:  =?UTF-8?B?6rmA7JuQ?= <user1@company.co.kr>, =?UTF-8?B?7Iah7ZWc6rec?= <user2@company.com>
Date: Wed Apr 17 10:37:44 KST 2019
Subj: Re: 이슈명
cont:
내용
...
--- Original issue from @user1  4월 5 at 1:20 오후 ---
...
<hr style="border:0; border-bottom:1px solid #ddd; margin:20px 0;">
<a href="http://127.0.0.1/hgsong/etriSimulator/issue/18#comment-33" target="_blank">Yona</a>에서 자세히 보거나 혹은 이 메일에 직접 회신하실 수도 있습니다.
...
</body></html>

2019-04-17 10:37:44,086 - [INFO] - from mail.out in application-akka.actor.default-dispatcher-3 
"Re: 이슈명" [=?UTF-8?B?6rmA7JuQ?= <user1@company.co.kr>, Yona <yona.mail@gmail.com>, =?UTF-8?B?7Iah7ZWc6rec?= <user2@company.com>]

2019-04-17 13:08:07,360 - [DEBUG] - from application in play-akka.actor.default-dispatcher-42 
The path we are coming from is the Login URL - delete jumpback

**Comment by doortts** [comment]
맨 마지막 로그에는 메일 발송이 mock = true 인 경우 생기는 로그인데요 
혹시 YONA_DATA 환경변수 설정이 잘 되었는지 확인한번 해주세요.

**Comment by cheekee** [comment]
H2 내장형으로 사용 중인데 YONA_DATA 등록해야 하나요.

현재 C:\yona-h2-v1.12.0-bin\yona-1.12.0 만 존재하여
C:\yona-h2-v1.12.0-bin\yona-data 폴더를 만들고
그 안에 conf 폴더를 이동 후 YONA_DATA 설정 > 재시작해보니 오류가 발생합니다.

처음부터 설치를 잘못한걸까요.ㅜ

**Comment by doortts** [comment]
내장형을 사용하시더라도 YONA_DATA  지정은 꼭 하셔야 하는 필수 요건이에요.

- 혹시라도 운영중에 폴더를 이동시켜서는 안되고
- 중단시킨다음 이동해야 합니다

[Windows의 경우](https://github.com/yona-projects/yona/blob/master/docs/ko/yona-run-options.md#windows%EC%9D%98-%EA%B2%BD%EC%9A%B0) 부분을 참고해 주세요
