### ISSUE TITLE
yobi -> yona 업그레이드 후 CPU 사용량이 너무 많습니다.

### ISSUE THREAD

**Issue by Jinuh** [yona-projects/yona#521]
현재 CentOS6, Oracle jdk 1.8 202, MariaDB 10.3.14 설치하여 Yona 구성하였으며, 파일 한개 라인 하나만 수정해도 git pull 진행 시 CPU 사용량이 390%이상 까지 올라갑니다.
pull 진행할 파일이 없어도 30%까지도 사용하구요.
CPU는 클라우드 환경의 2.8Ghz 4코어 입니다.
제가 체크해볼만 한 사항이 있을까요?

**Comment by Jinuh** [comment]
로그를 확인해보니 아래와 같은 에러가 떨어지기도 하는데요..
2019-05-15 11:17:12,900 - [ERROR] - from application in Thread-119
uploadPack failed
org.eclipse.jgit.transport.UploadPackInternalServerErrorException: null
org.eclipse.jgit.transport.UploadPackInternalServerErrorException: null
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1406) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.UploadPack.service(UploadPack.java:774) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.UploadPack.upload(UploadPack.java:667) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at playRepository.RepositoryService$3.run(RepositoryService.java:308) ~[yona.yona-1.12.0.jar:1.12.0]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at org.eclipse.jgit.internal.storage.file.PackIndexV2.<init>(PackIndexV2.java:98) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.PackIndex.read(PackIndex.java:139) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.PackIndex.open(PackIndex.java:98) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.PackFile.idx(PackFile.java:171) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.PackFile.get(PackFile.java:262) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedObject(ObjectDirectory.java:420) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openPackedFromSelfOrAlternate(ObjectDirectory.java:389) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:381) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:154) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.markTreeUninteresting(ObjectWalk.java:705) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.markTreeUninteresting(ObjectWalk.java:730) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.markTreeUninteresting(ObjectWalk.java:730) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.markTreeUninteresting(ObjectWalk.java:730) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.markTreeUninteresting(ObjectWalk.java:730) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.revwalk.ObjectWalk.next(ObjectWalk.java:300) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.pack.PackWriter.findObjectsToPack(PackWriter.java:1775) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.internal.storage.pack.PackWriter.preparePack(PackWriter.java:799) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1509) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.UploadPack.sendPack(UploadPack.java:1390) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        ... 3 common frames omitted

**Comment by doortts** [comment]
에러 자체는 메모리 부족에러인데요 이건 JVM 설정대비 소스파일의 크기가 클 경우 발생하는 에러일 가능성이 큽니다. JVM 메모리 세팅도 한 번 확인해봐야 할것 같습니다.

[자바 환경 변수 설정](https://github.com/yona-projects/yona/wiki/%EC%9E%90%EB%B0%94-%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EC%84%A4%EC%A0%95)

**Comment by Jinuh** [comment]
@doortts 님께서 도움주신덕분에 원인을 찾았습니다.
conf/application.conf 파일내 아래 설정때문에 너무 많은 쓰레드가 생성되어 발생한 증상으로 확인되었습니다.
해당 설정이 어떤설정인지 조금 자세한 설명이 있으면 좋을거같습니다.
이미 설명이 있는데 제가 확인하지 못한거라면 죄송합니다!
play {
  akka {
    event-handlers = ["akka.event.Logging$DefaultLogger", "akka.event.slf4j.Slf4jEventHandler"]
    loglevel = WARNING
    actor {
      default-dispatcher = {
        fork-join-executor {
          parallelism-min = 400
          parallelism-max = 400
        }
      }
    }
  }
}

# customize akka thread pool size
akka {
  event-handlers = ["akka.event.Logging$DefaultLogger", "akka.event.slf4j.Slf4j
  loglevel = WARNING
  actor {
    default-dispatcher = {
      fork-join-executor {
        # Min number of threads to cap factor-based parallelism number to
        parallelism-min = 8

        # The parallelism factor is used to determine thread pool size using th
        # following formula: ceil(available processors * factor). Resulting siz
        # is then bounded by the parallelism-min and parallelism-max values.
        parallelism-factor = 3.0

        # Max number of threads to cap factor-based parallelism number to
        parallelism-max = 64
      }
    }
  }
}
