### ISSUE TITLE
코드 저장소에 push -f 이후에 코드 페이지에서 해당 히스토리에 접근하면 에러가 발생합니다.

### ISSUE THREAD

**Issue by zinsani** [yona-projects/yona#526]
안녕하세요? 요새 요나에 푹 빠져 있네요. 정말 감사합니다.
제목과 같은 문제로 이슈를 발행하게 되었습니다.

로그는 하기와 같습니다.

```
2019-06-01T14:22:24.624944300Z [error] play - Cannot invoke the action, eventually got an error: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 71dd9be219ad4add47803b5b58bb73c748c861ff
2019-06-01T14:22:24.628032200Z [error] application -
2019-06-01T14:22:24.628074100Z
2019-06-01T14:22:24.628079100Z ! @7c3p8iodg - Internal server error, for (GET) [/jsp/workflow-inbox-parser-docker/commit/1a79ae3bd94db2a075b90cbc13931022db937b7e?branch=master] ->
2019-06-01T14:22:24.628082900Z
2019-06-01T14:22:24.628086200Z play.api.Application$$anon$1: Execution exception[[MissingObjectException: Missing unknown 71dd9be219ad4add47803b5b58bb73c748c861ff]]
2019-06-01T14:22:24.628089900Z  at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2019-06-01T14:22:24.628103500Z  at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2019-06-01T14:22:24.628106900Z  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2019-06-01T14:22:24.628110000Z  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
2019-06-01T14:22:24.628113100Z  at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
2019-06-01T14:22:24.628116000Z Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown 71dd9be219ad4add47803b5b58bb73c748c861ff
2019-06-01T14:22:24.628119000Z  at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:158) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
2019-06-01T14:22:24.628122100Z  at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:173) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
2019-06-01T14:22:24.628125100Z  at org.eclipse.jgit.lib.ObjectDatabase.open(ObjectDatabase.java:144) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
2019-06-01T14:22:24.628128100Z  at org.eclipse.jgit.lib.Repository.open(Repository.java:295) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
2019-06-01T14:22:24.628131100Z  at playRepository.GitRepository.getFileDiffs(GitRepository.java:1664) ~[yona.yona-1.12.0.jar:1.12.0]2019-06-01T14:22:24.630047800Z [info] a./jsp/workflow-inbox-parser-docker/commit/1a79ae3bd94db2a075b90cbc13931022db937b7e?branch=master - 172.18.0.1 - - [01/Jun/2019:23:22:24 +0900] "GET /jsp/workflow-inbox-parser-docker/commit/1a79ae3bd94db2a075b90cbc13931022db937b7e?branch=master HTTP/1.1" 500 - "http://192.168.100.165:9000/jsp/workflow-inbox-parser-docker/commits/master/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" -
2019-06-01T14:22:24.664443700Z [info] a./messages.js - 172.18.0.1 - jsp [01/Jun/2019:23:22:24 +0900] "GET /messages.js HTTP/1.1" 200 - "http://192.168.100.165:9000/jsp/workflow-inbox-parser-docker/commit/1a79ae3bd94db2a075b90cbc13931022db937b7e?branch=master" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" 4ms
2019-06-01T14:22:24.833737600Z [info] a./user/usermenuTabContentList - 172.18.0.1 - jsp [01/Jun/2019:23:22:24 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "http://192.168.100.165:9000/jsp/workflow-inbox-parser-docker/commit/1a79ae3bd94db2a075b90cbc13931022db937b7e?branch=master" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36" 103ms
```

**Comment by doortts** [comment]
안녕하세요
에러 자체는 아주 명확합니다. 히스토리상 특정 오브젝트가 있어야 하는데요
```
Missing unknown 71dd9be219ad4add47803b5b58bb73c748c861ff
```
로컬 해당 저장소 폴더에서 

```
git show 71dd9be219ad4add47803b5b58bb73c748c861ff
```
해보신다음
```
fatal: bad object 71dd9be219ad4add47803b5b58bb73c748c861ff
```
이런 에러가 뜨면 파일상에 문제가 생긴겁니다.

이럴때 시도해 볼 수 있는 방법으로는

```
git fsck
```
명령어 결과를 확인해보세요

**Comment by zinsani** [comment]
@doortts  답변 감사합니다.

말씀해주신대로 확인해보니 git submodule 의 hash 를 찾다가 에러가 나는 것이었습니다.
아직 submodule 지원이 안되는 것으로 알고 있어서 현재로서는 어쩔 수 없어 보입니다.

감사합니다. 이슈를 닫겠습니다.
