### ISSUE TITLE
사이트 관리메뉴 문제점

### ISSUE THREAD

**Issue by bver3343** [yona-projects/yona#534]
소스코드에서 빌드하여 사용하는 중에 발생한 문제입니다. 
도움얻고자 글 작성합니다.
증상 : 초기 어드민 계정생성 이후, 추가로 계정 1개를 더 생성.
이때 어드민 계정으로 사이트 관리 메뉴의 사용자 탭을 클릭하면 아래와 같은 에러와 함께 접속이 끊어짐.
다른 모든 사용(프로젝트 생성, 이슈작성, 이슈할당 등등)은 정상.

현재 사용 버전은 JDK 1.8/MariaDB 10.2/yona는 git 최신 버전 입니다.

에러메세지
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider
 com.sun.phobos.script.javascript.RhinoScriptEngineFactory could not be instanti
ated
Uncaught error from thread [play-akka.actor.default-dispatcher-13] shutting down
 JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.ExceptionInInitializerError
        at utils.JodaDateUtil.momentFromNow(JodaDateUtil.java:74)
        at utils.JodaDateUtil.socialDate(JodaDateUtil.java:109)
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:140)
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:119)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)

        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at views.html.site.userList$.apply(userList.template.scala:119)
        at views.html.site.userList$.render(userList.template.scala:253)
        at views.html.site.userList.render(userList.template.scala)
        at controllers.SiteApp.userList(SiteApp.java:108)
[ERROR] [07/05/2019 15:45:50.920] [play-akka.actor.default-dispatcher-13] [Actor
System(play)] Uncaught error from thread [play-akka.actor.default-dispatcher-13]
 shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$120$$anonfun$apply$120.
apply(routes_routing.scala:3105)
java.lang.ExceptionInInitializerError
        at utils.JodaDateUtil.momentFromNow(JodaDateUtil.java:74)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$120$$anonfun$apply$120.
apply(routes_routing.scala:3105)
        at utils.JodaDateUtil.socialDate(JodaDateUtil.java:109)
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scal
a:264)
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:140)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.invocation(Router.scala:255)
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:119)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244)
        at Global$2.call(Global.java:274)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)

        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(
Future.scala:24)
        at scala.collection.AbstractTraversable.map(Traversable.scala:105)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.sca
la:24)
        at views.html.site.userList$.apply(userList.template.scala:119)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.sca
la:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:
46)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:3
2)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at views.html.site.userList$.render(userList.template.scala:253)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
        at views.html.site.userList.render(userList.template.scala)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.apply(Router.scala:252)
        at controllers.SiteApp.userList(SiteApp.java:108)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:130)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$120$$anonfun$apply$120.
apply(routes_routing.scala:3105)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:130)
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$120$$anonfun$apply$120.
apply(routes_routing.scala:3105)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scal
a:264)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.sc
ala:129)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.invocation(Router.scala:255)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.sc
ala:128)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
        at scala.Option.map(Option.scala:145)
        at Global$2.call(Global.java:274)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
        at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:39)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:
483)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:
483)
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(
Future.scala:24)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.sca
la:24)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.
apply(Iteratee.scala:496)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.sca
la:40)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.
apply(Iteratee.scala:496)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(
Future.scala:24)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:
46)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.sca
la:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:3
2)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.Future$.apply(Future.scala:485)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
        at utils.MomentUtil.buildEngine(MomentUtil.java:52)
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon
$15$$anon$1.apply(Router.scala:252)
        at utils.MomentUtil.<clinit>(MomentUtil.java:37)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:130)
        ... 57 more
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$
5.apply(Action.scala:130)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.sc
ala:129)
Caused by: java.lang.NullPointerException
        at utils.MomentUtil.buildEngine(MomentUtil.java:50)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.sc
ala:128)
        ... 58 more
        at scala.Option.map(Option.scala:145)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:
483)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:
483)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.sc
ala:519)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.
apply(Iteratee.scala:496)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.
apply(Iteratee.scala:496)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(
Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.sca
la:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(Abst
ractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool
.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:19
79)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThre
ad.java:107)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at utils.MomentUtil.buildEngine(MomentUtil.java:52)
        at utils.MomentUtil.<clinit>(MomentUtil.java:37)
        ... 57 more
Caused by: java.lang.NullPointerException
        at utils.MomentUtil.buildEngine(MomentUtil.java:50)
        ... 58 more

[error] a.a.ActorSystemImpl - Uncaught error from thread [play-akka.actor.defaul
t-dispatcher-13] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabl
ed
java.lang.ExceptionInInitializerError: null
        at utils.JodaDateUtil.momentFromNow(JodaDateUtil.java:74) ~[classes/:na]

        at utils.JodaDateUtil.socialDate(JodaDateUtil.java:109) ~[classes/:na]
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:140) ~[classes/:na]
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:119) ~[classes/:na]
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike
.scala:244) ~[scala-library.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at utils.MomentUtil.buildEngine(MomentUtil.java:52) ~[classes/:na]
        at utils.MomentUtil.<clinit>(MomentUtil.java:37) ~[classes/:na]
        at utils.JodaDateUtil.momentFromNow(JodaDateUtil.java:74) ~[classes/:na]

        at utils.JodaDateUtil.socialDate(JodaDateUtil.java:109) ~[classes/:na]
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:140) ~[classes/:na]
Caused by: java.lang.NullPointerException: null
        at utils.MomentUtil.buildEngine(MomentUtil.java:50) ~[classes/:na]
        at utils.MomentUtil.<clinit>(MomentUtil.java:37) ~[classes/:na]
        at utils.JodaDateUtil.momentFromNow(JodaDateUtil.java:74) ~[classes/:na]

        at utils.JodaDateUtil.socialDate(JodaDateUtil.java:109) ~[classes/:na]
        at views.html.site.userList$$anonfun$apply$1.apply(userList.template.sca
la:140) ~[classes/:na]

**Comment by doortts** [comment]
소스빌드라고 하셨는데 소스의 마지막 커밋 아이디와 메시지가 뭘로 표시되시나요?

**Comment by bver3343** [comment]
message: Extract to message file
Latest commit 533153d  on 26 Mar 입니다.

혼자서 사용했을 때는 문제가 없었습니다만
아래와같이 설정하여 다른 컴퓨터에서 접속가능하게 한 뒤
![image](https://user-images.githubusercontent.com/52561248/60775074-a2152700-a158-11e9-8a65-d868f682d322.png)

다른 컴퓨터에서 혹은 제 컴퓨터에서 회원가입을 통해 새 유저를 생성하면 이슈와같은 현상이 생깁니다.

제가 설정을 잘못한 것일까요?

**Comment by bver3343** [comment]
혹시나 해서 배포판으로 만들어 실행하였더니 외부접속 및 계정생성, 관리메뉴 확인 잘 됩니다.

뭐가 원인인지 잘 모르겠네요. ㅎㅎ;;

**Comment by doortts** [comment]
소스로부터 직접 배포판을 만들었을경우 말이신거죠?

**Comment by bver3343** [comment]
네 그렇습니다!

**Comment by doortts** [comment]
신기하네요. 음. RhinoScriptEngineFactory 를 안쓰는데 그 부분에서 에러가 나는것도 그렇구요. 음..
