### ISSUE TITLE
Play FrameWork maven 라이브러리 다운로드 offline하는 방법

### ISSUE THREAD

**Issue by CarpediemBDev** [yona-projects/yona#555]
Play FrameWork maven 라이브러리 다운로드 offline하는 방법
이미 개발 pc에 다운 받아져있고 그것을 서버에 라이브러리들을 올렸음에도
activator run 명령어를 실행하면 maven 사이트와 연동하여 통신하고 있습니다.

offline으로 lib들을 읽어볼 방법ㅂ은 없나요?

**Comment by doortts** [comment]
#554 와 이어지는 내용인듯한데요 만약 이런 경우라면
pc에 다운 받으셔서 그곳에서 activator run 먼저 하신다음
빌드 끝나신다음 

project 폴더와 target 폴더도 함께 묶어서 옮겨보시겠어요?

**Comment by CarpediemBDev** [comment]
yona - project  하위에 있는 폴더 말인가요?
일단 저의경우는 윈도우7 C:\act\activator\yona\ 경로로 만들었습니다.
그리고 act 폴더를 tar으로 압축하여 서버에 옮겨진  상태입니다.

**Comment by CarpediemBDev** [comment]
결국 방화벽을 뚫어서 maven에서 호출한 url에 접속 가능하게 하였습니다.
임시적으로 뚫은거라.. 이후에는 maven을 안바라봤으면 좋겠지만...

아 그리고 혹시 yona가 정상적으로 가동되고 ip:9000으로 호출을하면 아래와 같은 오류가 나타납니다.
window 7일때에는 이상없이 작동되었던건데 centOS로 그대로 옮기니 발생하네요..
달라진점은 Oracle JDK를 OpenJdk로 변경한건데 영향이 있을까요? 둘다 8버전입니다.


Configuration error: Configuration error[Cannot register class [models.CommitComment] in Ebean server]
Oops, cannot start the server.
        at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94)
        at play.api.Configuration.reportError(Configuration.scala:743)
        at play.Configuration.reportError(Configuration.java:310)
        at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:81)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    models/CodeComment.setAuthor(Lmodels/User;)V @2: invokevirtual
  Reason:
    Type 'models/User' (current frame, stack[1]) is not assignable to 'models/CodeComment'
  Current Frame:
    bci: @2
    flags: { }
    locals: { 'models/CodeComment', 'models/User' }
    stack: { 'models/CodeComment', 'models/User' }
  Bytecode:
    0x0000000: 2a2b b600 4db6 0051 2a2b b400 56b6 005a
    0x0000010: 2a2b b400 5db6 0060 b1

**Comment by CarpediemBDev** [comment]
혹시 jdk 문제라면 오픈jdk를 뭘로 깔아야될까요?
그리고 http://repo1.maven.org 호출해서 라이브러리 받아오는 것은 처음에 정상적으로 받아오면 그다음부터는 통신을 안하게 되나요?
일단 방화벽을 허용해서 받아오도록했는데 그다음에는 offline으로 이미 받아진 라이브러들을 바라보게 하고 싶습니다.
--

**Comment by CarpediemBDev** [comment]
위의 오류는 처리했습니다.
yona/target을 전부다 지우고 다시 재 빌드하니 다른에러가 나오네요
play.api.db.evolutions.InconsistentDatabase: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196) ~[play-jdbc_2.10-2.3.10.jar:2.3.10]
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367) ~[play-jdbc_2.10-2.3.10.jar:2.3.10]
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332) ~[play-jdbc_2.10-2.3.10.jar:2.3.10]
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330) ~[play-jdbc_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]

**Comment by doortts** [comment]
```
Database 'default' is in an inconsistent state! 
```
이 에러는 이미 데이터 베이스가 생성되어 있는 상태에서 다시 생성 스크립트가 생성된 경우에 흔히 발생하는 에러입니다.

DB 를 지우시고 재 생성 해서 진행해 보시겠어요?

**Comment by CarpediemBDev** [comment]
네 감사합니다. 
혹시 서버에서 yum으로 mariadb를 설치했는데 5.56버전이 받아지더라구요 10.2버전으로 설치가 안되어도 문제가 발생할 수 있죠?

**Comment by project-yona** [comment]
네 5.대면 10.0 이전 혹은 호환버전일거라 현 Yona 와 연동시키려면 개발팀의 작업이 필요할것같습니다



2019년 8월 28일 (수) 오후 4:06, Carpediem <notifications@github.com>님이 작성:

**Comment by CarpediemBDev** [comment]
네 감사합니다.
그리고 별도 이슈사항으로 올릴것인데
playframework 명령어 activator를 사용하면 maven url에서 jar를 다운받아 오던데

pc에 다운 받으셔서 그곳에서 activator run 먼저 한 다음
빌드 끝나신다음 서버로 Yona 소스파일을 올렸습니다.
그런데 서버는 인터넷이 막혀있는데 maven url 호출 안하고 local에 설치된 lib를 읽게 하려면 어떻게 해야하나요? .ivy 파일을 읽긴하던데 이게 root/.ivy파일에 다 집어넣어줘도 maven url을 무조건 호출하네요

**Comment by CarpediemBDev** [comment]
감사합니다. 오류나는 부분은  해결되었습니다. maven 라이브러리 offline으로하는 방법은 다른 이슈에 올려주신대로 해보겠습니다. 잘되었음 좋겠네요
