### ISSUE TITLE
슬랙 웹훅이 동작하지 않습니다.

### ISSUE THREAD

**Issue by iowtis** [yona-projects/yona#623]
버전은 yona-1.12 사용하고 있습니다.

이슈 등록시 웹훅을 받아볼수 있도록 설정을 하였습니다.

이슈 등록마다 웹훅이 왔었는데, 어느 순간부터 웹훅이 동작하지 않는다는 것을 알게 되었습니다.
(해당 웹훅 url로 curl 테스트를 하면 동작을 잘 하네요..)

어느 부분에서 오류가 난지 확인하고 싶은데 어떤 부분을 봐야할까요?

**Comment by hongwonjun** [comment]
혹시 로그를 확인할 수는 없을까요?

**Comment by iowtis** [comment]
웹훅관련 로그남는곳이 application.log가 맞을까요?

**Comment by hongwonjun** [comment]
@doortts 님 로그는 어디를 찾아보면 될까요?

**Comment by hongwonjun** [comment]
@iowtis 
혹시 로그 외에 웹훅이 제대로 작동하는지 확인할 수 있을까요?

간단한 python 코드는 아래 repo 를 사용하셔도 됩니다.
https://github.com/hongwonjun/legendary-succotash

**Comment by iowtis** [comment]
@hongwonjun 
웹훅 curl test를 했을때 동작은 잘 됬습니다.
test한 curl 내용입니다.
```
webhook="https://hooks.slack.com/services/~~~~~~"

payload="payload={
"text": "detect : test"
}"

curl --data-urlencode "${payload}" "${webhook}"
```

해당 스크립트를 수행하면 아래와 같이 웹훅을 받아볼수 있었습니다.
![image](https://user-images.githubusercontent.com/39899020/77133270-db52b480-6aa5-11ea-926b-6af7719b3d4d.png)


curl은 동작을 하는데 yona site에서 웹훅 기능이 갑자기 동작하지 않아,
application을 재시작 해보았지만 현상은 같은 상황입니다.

**Comment by hongwonjun** [comment]
@iowtis 
진행해주신 부분은 slack 이 webhook 을 제대로 받는지를 확인하신거 같은데,
혹시 slack 이 아니라 다른 곳에서 Yona 의 webhook 을 확인할 수는 없을까요?

혹은 yona 의 webhook 설정이 어떻게 되어 있는지 확인할 수 있을까요?

**Comment by iowtis** [comment]
@hongwonjun 
아 위에 해당 curl test는 yona가 올라가있는 시스템에서 slack으로 curl test를 진행하였습니다.

yona의 webhook 설정은 따로 지정한것 없이 해당 url을 보고 따라했습니다.
```
https://repo.yona.io/yona-projects/yona-help/post/6
```
6개월 이상 사용이 잘 되었는데, 갑자기 동작하지 않는 부분이라 어느 부분을 봐야할지 모르겠네요..

![image](https://user-images.githubusercontent.com/39899020/77140290-7fdff100-6abc-11ea-92d6-19ded3a8dffa.png)

**Comment by hongwonjun** [comment]
@iowtis 
네, 혹시 slack 이 아니라 다른 곳에서 Yona 의 webhook 을 확인할 수는 없을까요?

**Comment by iowtis** [comment]
이슈 등록시, yona 서버 --> hooks.slack.com으로 핸드쉐이크 실패 에러 로그가 나오고 있네요.
혹시 알고 계신 해결방법 있을까요?

```
2020-03-20 16:36:32,277 - [DEBUG] - from com.ning.http.client.providers.netty.NettyConnectListener in New I/O worker #9 
Trying to recover a dead cached channel [id: 0x99828c2e, /[yona 서버 ip]:45664 => hooks.slack.com/13.225.132.98:443] with a retry value of true 

2020-03-20 16:36:32,277 - [DEBUG] - from com.ning.http.client.providers.netty.NettyConnectListener in New I/O worker #9 
Failed to recover from exception: javax.net.ssl.SSLException: Received fatal alert: handshake_failure with channel [id: 0x99828c2e, /[yona 서버 ip]:45664 => hooks.slack.com/13.225.132.98:443]

2020-03-20 16:36:32,278 - [DEBUG] - from com.ning.http.client.providers.netty.NettyAsyncHttpProvider in New I/O worker #9 
Unexpected I/O exception on channel [id: 0x99828c2e, /[yona 서버 ip]:45664 => hooks.slack.com/13.225.132.98:443]
javax.net.ssl.SSLException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1647) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1615) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1781) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1070) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:896) ~[na:1.8.0_201]
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:766) ~[na:1.8.0_201]
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[na:1.8.0_201]
	at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1284) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:918) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

2020-03-20 16:36:32,278 - [DEBUG] - from com.ning.http.client.providers.netty.NettyAsyncHttpProvider in New I/O worker #9 
Channel Closed: [id: 0x99828c2e, /[yona 서버 ip]:45664 :> hooks.slack.com/13.225.132.98:443] with attachment NettyResponseFuture{currentRetry=1,
	isDone=false,
	isCancelled=true,
	asyncHandler=play.libs.ws.ning.NingWSRequest$1@1ea72555,
	requestTimeoutInMs=120000,
	nettyRequest=DefaultHttpRequest(chunked: false)
POST /services/xxxx/xxxx/xxxx HTTP/1.1
Host: hooks.slack.com
Authorization: token 
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Accept: */*
User-Agent: Yobi-Hookshot
Content-Length: 104,
	content=null,
	uri=https://hooks.slack.com/services/xxxx/xxxx/xxxx,
	keepAlive=true,
	httpResponse=null,
	exEx=java.util.concurrent.ExecutionException: java.net.ConnectException: Received fatal alert: handshake_failure to https://hooks.slack.com/services/xxxx/xxxx/xxxx,
	redirectCount=0,
	timeoutsHolder=null,
	inAuth=false,
	statusReceived=false,
	touch=29980030844}

2020-03-20 16:36:32,278 - [DEBUG] - from com.ning.http.client.providers.netty.NettyAsyncHttpProvider in New I/O worker #9 
Closing Channel [id: 0x99828c2e, /[yona 서버 ip]:45664 :> hooks.slack.com/13.225.132.98:443] 

2020-03-20 16:36:32,279 - [DEBUG] - from com.ning.http.client.providers.netty.NettyAsyncHttpProvider in New I/O worker #8 
Channel Closed: [id: 0xc163e0f5, /[yona 서버 ip]:45662 :> hooks.slack.com/13.225.132.98:443] with attachment NettyResponseFuture{currentRetry=1,
	isDone=false,
	isCancelled=true,
	asyncHandler=play.libs.ws.ning.NingWSRequest$1@508918d9,
	requestTimeoutInMs=120000,
	nettyRequest=DefaultHttpRequest(chunked: false)
POST /services/xxxx/xxxx/xxxx HTTP/1.1
Host: hooks.slack.com
Authorization: token 
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Accept: */*
User-Agent: Yobi-Hookshot
Content-Length: 104,
	content=null,
	uri=https://hooks.slack.com/services/xxxx/xxxx/xxxx,
	keepAlive=true,
	httpResponse=null,
	exEx=java.util.concurrent.ExecutionException: java.net.ConnectException: Received fatal alert: handshake_failure to https://hooks.slack.com/services/xxxx/xxxx/xxxx,
	redirectCount=0,
	timeoutsHolder=null,
	inAuth=false,
	statusReceived=false,
	touch=29980030843}

2020-03-20 16:36:32,279 - [DEBUG] - from com.ning.http.client.providers.netty.NettyAsyncHttpProvider in New I/O worker #8 
Closing Channel [id: 0xc163e0f5, /[yona 서버 ip]:45662 :> hooks.slack.com/13.225.132.98:443] 
```

**Comment by iowtis** [comment]
@hongwonjun 
웹훅이 안나가는 현상 해결 되었습니다.

yona의 bug는 아니었고, 
어디선가 네트워크가 차단되어 10일 정도 웹훅이 나가지 않았습니다.

도움주셔서 감사합니다!

**Comment by hongwonjun** [comment]
와... 알려주셔서 정말 감사드립니다.
다행이네요.
이슈는 닫도록 하겠습니다.

**Comment by doortts** [comment]
@hongwonjun @iowtis 다행이네요 수고많으셨어요!
