### ISSUE TITLE
단 한번도 새프로젝트를 생성해본적이 없네요..;;;

### ISSUE THREAD

**Issue by coffeemiller** [yona-projects/yona#629]
### 도와주십시오.

![image](https://user-images.githubusercontent.com/43500068/77569082-fc376180-6f0c-11ea-99e2-472b119eba51.png)

#### 혹시, 해결하신 분 계신가요??

```
[error] play - Cannot invoke the action, eventually got an error: java.lang.NullPointerException: The id is null
[error] application -

! @7f99algl8 - Internal server error, for (POST) [/projects] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: The id is null]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: The id is null
        at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1078) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.find(DefaultServer.java:1069) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at play.db.ebean.Model$Finder.byId(Model.java:265) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at models.ProjectUser.<init>(ProjectUser.java:54) ~[yona.yona-1.12.0.jar:1.12.0]
        at models.ProjectUser.create(ProjectUser.java:59) `~[yona.yona-1.12.0.jar:1.12.0]
```
---------------------------------------------------------------------------------------

**Comment by doortts** [comment]
사용하시는 OS와 DB, Java, Yona 버전이 어떻게 되시나요?
그리고 어떤 상황에서 위와 같은 에러가 발생하나요?

**Comment by coffeemiller** [comment]
사양은 다음과 같습니다.
------------------------------------------------------
Win10 Pro
java 1.8
yona 1.13.0  or 1.12.0
mariadb 10.4
------------------------------------------------------

1. 압축풀고 요나폴더 + 데이터 폴더를 만들고
2. 요나 첫실행 후, conf 폴더 데이터로 복사하고
3. conf에 있는 비밀번호 부분 넣었고
4. db에 사용자명/비번 넣고
5. 환경변수 설정하고
6. 요나 실행해서 첫 관리자 등록한 후
7. 요나 재실행
8. 로그인 후
9. 새프로젝트를 만들면....... 오류입니다.

제가 빼놓은게 있는지요?
오류 메시지에 id가 뭘 의미하는지 모르겠지만....
더 설정해야할게 있는 것인지 궁금합니다.

**Comment by injiyoung** [comment]
docker로 해보세요 한방에 됩니다.
https://github.com/pokev25/docker-yona/issues/7

**Comment by doortts** [comment]
특별히 발생할 상황이 아닌것 같습니다. 아마 DB 세팅 후 관리자 생성 시 뭔가 중단이나 간섭이 들어간 상황인것 같아보여요. 
DB 통째로 지우고 다시 설치해 보시겠어요?
