### ISSUE TITLE
MySQL에서 설치 시 에러 인 경우

### ISSUE THREAD

**Issue by ColosseumKr** [yona-projects/yona#636]
안녕하세요

yona설치 후에, application.conf 파일 수정하고

컨피그레이션 에러 나는걸 mysql connector j를 설치해서 잡았습니다.

그러고 나니 다음과 같은 오류가 발생 합니다.

운영체제는 : Amazon linux2 이구요
DB는 : Aurora Mysql 5.6.10a입니다.

[root@ip-172-31-45-162 yona-1.13.0]# bin/yona 
Play server process ID is 16248
[info] play - database [default] connected at jdbc:mysql://db-colosseum-cluster.cluster-cnlzrndairv2.ap-northeast-2.rds.amazonaws.com:3306/yona
[error] play - (conn:38124) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONSTRAINT IF EXISTS ck_attachment_container_type' at line 1
Query is : ALTER TABLE attachment DROP CONSTRAINT IF EXISTS ck_attachment_container_type [ERROR:1064, SQLSTATE:42000]
Oops, cannot start the server.
@7fcne8g5o: Database 'default' is in an inconsistent state!
	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
	at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
	at scala.Option.map(Option.scala:145)
	at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)

github를 통해서 검색한 해결 방법에는 mysql이 아닌 mariadb를 업데이트 하는 방법만 나와 있던데

mariadb로 수정을 하지 않고 mysql내에서 해결 할 수 있는 방법은 없는건가요??

**Comment by doortts** [comment]
DB 차이에 의해 발생하는 문제가 맞습니다. 특정 버전 이후로 MySQL과 MaridDB가 서로 다른 길을 걷기 시작해서 발생하는 문제인데요 우회방법을 찾아보고 이야기 드릴게요.

**Comment by doortts** [comment]
버전은 어떻게 되세요?

**Comment by ColosseumKr** [comment]
DB는 Mysql 5.6.10a입니다.

**Comment by doortts** [comment]
커스텀 빌드를 하나 만들어서 제공해 드리려고 하는데요 Yona는 1.13 버전으로 제공해드릴게요.

**Comment by ColosseumKr** [comment]
넵 감사합니다

**Comment by doortts** [comment]
https://drive.google.com/file/d/18-x2GxUlaV83kw716XQW97U3SkVHlHCF/view?usp=sharing

문제로 생각되는 부분을 제거한 커스텀 빌드를 만들었습니다. 기존 설치중이던 DB 를 drop 하고 다시 시도해 봐 주시겠어요?

**Comment by ColosseumKr** [comment]
올려주신 파일로 새롭게 돌려봤는데 
Error: Could not find or load main class play.core.server.NettyServer 가 발생합니다.

이 경우는 https://github.com/yona-projects/yona/issues/31#issue-145622032 에서와 같이 자바 버전이 안 맞는건가요??

현재 리눅스에 설치되어 있는 java 버전은 1.8.0.242 입니다.

**Comment by doortts** [comment]
다시 확인해보고 이야기 드릴게요

**Comment by doortts** [comment]
다시 확인해 보았는데요 커스텀 빌드파일 자체에 문제는 찾지 못했습니다.
java -version 
결과 값을 그대로 붙여주실 수 있을까요?

**Comment by ColosseumKr** [comment]
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

이러합니다

**Comment by doortts** [comment]
pokev 님의 Docker는 openjdk 8 에서 실행되고 https://github.com/pokev25/docker-yona/blob/master/Dockerfile 
저는 openjdk 13에서 테스트 해 봤었는데 해당 에러가 발생하지는 않았습니다.
추가적으로 확인하기가 조금 어려운 상황입니다. 

링크의 빌드는 위에 이슈로 적어주신 constraints 문법을 MySQL 에 맞게 수정해서 따로 빌드를 한 파일입니다.
