### ISSUE TITLE
TLS 이메일 설정

### ISSUE THREAD

**Issue by infostore** [yona-projects/yona#642]
버전 : 1.13
환경 : Docker

smtp.host = smtp.gmail.com
smtp.port = 587
smtp.auth = true
smtp.startssl = true
smtp.user = "example@gmail.com"
smtp.password = "example"
smtp.domain = "gmail.com"
smtp.mock = false
smtp.archive.size = 5

알림을 받기 위해 위와같이 설정했습니다.
하지만, 메일이 전송되지 않고 아래와 같은 에러가 발생하고 있습니다.

[warn] application - Failed to send a notification: models.NotificationMail$EventEmail@26ea9dd9
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:587
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
        at org.apache.commons.mail.Email.send(Email.java:1437)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54)
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68)
        at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8)
        at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15)
        at models.NotificationMail.sendMail(NotificationMail.java:563)
        at models.NotificationMail.sendNotification(NotificationMail.java:419)
        at models.NotificationMail.access$100(NotificationMail.java:58)
        at models.NotificationMail$1.sendMail(NotificationMail.java:150)
        at models.NotificationMail$1.run(NotificationMail.java:113)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.mail.MessagingException: Exception reading response;
  nested exception is:
        java.net.SocketTimeoutException: Read timed out
        at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2210)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1950)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
        ... 18 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:110)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
        at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2188)
        ... 26 more

**Comment by doortts** [comment]
port 를 465로 변경해서 테스트해봐주시겠어요?

**Comment by infostore** [comment]
465로 변경하니까 되네요.
