### ISSUE TITLE
MariaDB 10.4 관련 yona설치시 오류

### ISSUE THREAD

**Issue by topdevhyun** [yona-projects/yona#650]
OS : centos 7.8
DB : 10.4.13-MariaDB
JDK : 1.8

설치버전 : yona-v1.13.0  or  yona-v1.12.0    (같은에러 증상)

* MariaDB 문제 이슈가 있어 아래 메뉴얼 대로 참고하여 설정하였으나 에러가 발생합니다.
https://github.com/yona-projects/yona/issues/452

에러 발생시점은 bin/yona  2번째 실행시 아래 에러 메세지가 출력됩니다.

테이블이 모두 생성되고 db와 관련된 셋팅중에 에러가 나는것 같은데 원인을 모르겠네요..

[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
Oops, cannot start the server.
java.sql.SQLNonTransientConnectionException: (conn:19) Connection is close
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:132)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.prepare(MariaDbServerPreparedStatement.java:154)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.<init>(MariaDbServerPreparedStatement.java:96)
        at org.mariadb.jdbc.MariaDbConnection.internalPrepareStatement(MariaDbConnection.java:423)
        at org.mariadb.jdbc.MariaDbConnection.prepareStatement(MariaDbConnection.java:262)
        at com.jolbox.bonecp.ConnectionHandle.prepareStatement(ConnectionHandle.java:1024)
        at play.api.db.evolutions.Evolutions$.prepare(Evolutions.scala:128)
        at play.api.db.evolutions.Evolutions$.updateLastProblem$1(Evolutions.scala:247)
        at play.api.db.evolutions.Evolutions$.applyScript(Evolutions.scala:289)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:496)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Connection is close
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.cmdPrologue(AbstractQueryProtocol.java:1275)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.prepare(AbstractQueryProtocol.java:308)
        at org.mariadb.jdbc.MariaDbServerPreparedStatement.prepare(MariaDbServerPreparedStatement.java:143)
        ... 28 more

**Comment by doortts** [comment]
에러 자체는 DB에 접속을 하지 못하는 것처럼 보입니다. MariaDB 10.3 으로 설치시에도 동일한 문제가 발생하는지 테스트 해 봐주시겠어요?

**Comment by doortts** [comment]
아 그런데 두 번째 실행시라고 하셨으니까 DB 버전을 변경하기 전에 DB 를 먼저 drop 해서 지우시고 다시 한 번 해보시고 그래도 동일하면 버전을 내려봐주세요. 

```
drop database yona;
```

**Comment by topdevhyun** [comment]
drop database yona 도 삭제하면서 여러번 시도해도 같은 문제네요..

MariaDB 버전 문제인것 같아서 버전을 낮추면 될것 같긴 한데.. 아무래도 다른  서비스에서도 쓰고 있는 상태라서 DB 버전을 내리기가 힘드네요..  10.4 버전에서 해결할 방법이 없을까요?  

참고로 bin/yona  3번째 실행시는 에러 메세지는 다음과 같습니다.
$bin/yona 
Play server process ID is 2700
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - 
Oops, cannot start the server.
@7g4k8okp6: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
마지막에 보내주신 에러는 databse 생성중에 문제가 생겼는데 DB를 지우지 않고 다시 실행할 때 발생하는 에러입니다.

> Database 'default' is in an inconsistent state!

그리고 10.4는 한 번 테스트를 진행해 볼게요. 빠르면 내일까지, 잘 안되면 주말정도까지 소요될 것으로 예상합니다. :)

**Comment by topdevhyun** [comment]
감사합니다~

**Comment by doortts** [comment]
예상보다 시간이 더 오래걸렸습니다. 다양한 테스트와 옵션 변경, 라이브러리 변경등을 시도해 보았습니다.
조금 더 조사 시간이 걸릴 것으로 예상합니다.
Maria DB 10.4 는 우선 현재는 지원하지 않는 것으로 표기해 놓아야 할 것 같습니다.

**Comment by topdevhyun** [comment]
네~  Maria DB 10.3 버전으로 재설치해서 진행하니 잘되네요~
