### ISSUE TITLE
마리아DB 10.2 yona 1.12,0 설치 시 오류 

### ISSUE THREAD

**Issue by parkjungwoon06210819** [yona-projects/yona#651]
OS : win10 
DB 10.2 MariaiDB
jdk 1.8 
yona 1.12,0 

마리아 디비 설치 이후 디비 관련 설정 해주고, yona 설치 이후 실행을 시키면 
아래와 같이 오류가 나오는데요 원인을 모르겠네요 Aplication파일에서 마리아 디비 관련
설정도 해주었습니다.  

Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:130)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:91)
        at org.mariadb.jdbc.Driver.connect(Driver.java:109)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120)
        at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240)
        ... 22 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'yona'@'localhost' (using password: YES)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:566)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:507)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:392)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:811)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:469)
        at org.mariadb.jdbc.Driver.connect(Driver.java:104)
        ... 28 more

**Comment by minishanell** [comment]
저도 설치하다 이 오류를 겪었는데요...
해당 데이터베이스가 계정과 연동이 되어있지 않은 문제더라구요...

혹시 해당 계정이 그 데이터베이스에 전체 권한이 부여된 상태가 맞으신가요?
