### ISSUE TITLE
웹 브라우저 Data Form에 비밀번호가 평문으로 노출됩니다.

### ISSUE THREAD

**Issue by yoosejin** [yona-projects/yona#665]
안녕하세요.

사내에 이용중인 yona에 Active Directory 계정을 사용하여 접속하도록 테스트 진행중에 비밀번호가 평문으로 담기는 걸 확인하고 의도하신 내용인지 확인 드릴겸 이슈 생성 드립니다.

자세한 내용은 아래 이미지에서 확인 부탁드립니다.
![yona](https://user-images.githubusercontent.com/33189378/93424782-ab208d00-f8f3-11ea-9885-9c527fecc480.PNG)

--------------------------------

그리고 이건 설정 과정에서 궁금한 사항인데,
Active Directory 설정에서 아래와 같은 오류 메시지가 발생하고 있습니다.

방화벽은 해제되어 있고 yona 서버에서 telnet을 사용하여 연결되는 것도 확인하였습니다.
gitlab 서버는 동일 설정으로 문제없이 사용중이나 yona와 연결하려 할때는 time out이 자꾸 발생하는데 yona에서 수정 반영해볼 설정이 있을까요?

**로그 시작**
[error] application - Cannot connect to ldap server
javax.naming.CommunicationException: ldap.XXX.XXX:636 [Root exception is java.net.SocketTimeoutException: connect timed out]
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:226)
	at com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1609)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2749)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at utils.LdapService.authenticate(LdapService.java:54)
	at controllers.UserApp.authenticateWithLdap(UserApp.java:1159)
	at controllers.UserApp.loginByFormRequest(UserApp.java:221)
	at controllers.UserApp.login(UserApp.java:171)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$97$$anonfun$apply$97.apply(routes_routing.scala:2942)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$97$$anonfun$apply$97.apply(routes_routing.scala:2942)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at Global$2.call(Global.java:274)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:485)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:360)
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:213)

**Comment by doortts** [comment]
## 암호 노출 문제

보내는 PC의 브라우저의 입력폼의 password 는 따로 암호화를 하고 있지 않습니다. 자칫 보안에 취약한 것처럼 느껴질 수 있지만 사실 폼 내용 자체를 js로 임의 암호화보다 https 통신을 하는 것이 효율적이고 안전하다고 판단하고 있습니다.

## LDAP 문제

- 현상 자체는 application.conf 파일내의 LDAP 설정이 잘못 기재 되었을때 발생할 수 있는 문제입니다

**Comment by yoosejin** [comment]
답변 감사드립니다. 

ldap 설정 관련해서 추가 문의사항이 있습니다.
지금 ldap.test.te 라는 최상위 디렉터리(domainDNS)가 있고, 하위에 Users라는 organizationnalUnit (유저 디렉터리)가 있습니다.

따라서 application.conf에 아래와 같이 설정하였는데도 처음 올렸던 로그가 발생하고 있습니다.
확인된 사항은 아래와 같습니다.
1. 방화벽 (해제 후 telnet으로 연결 확인)
2. ldap을 사용중인 기타 서비스에서 동일한 뎁스의 유저로 로그인 되는 것 확인. (gitlab, jira)

loginproperty를 CN으로 해보거나(CN이 유저ID입니다.), 이메일 로그인 옵션을 켜봐도 동일한 로그만 발생하고 있습니다.

로그인 할 계정의 distinguishedName는 CN=sejin,OU=Users,DC=ldap,DC=test,DC=te 입니다.

------------------------------------------------------------------------------------------
application.use.ldap.login.supoort = true
ldap {
    host = "ldap.test.te"
    # default: ldap.port=389, ldaps.port=636
    port = 636
    # protocol: ldap or ldaps. If you want to use SSL/TLS, use 'ldaps'
    protocol = "ldaps"
    **baseDN = "DC=ldap,DC=test,DC=te"**
    # If your ldap service's distinguishedName is 'CN=username,OU=user,DC=abc,DC=com', postfix is 'OU=xxx,DC=abc,DC=com'
    **distinguishedNamePostfix = "OU=Users,DC=ldap,DC=test,DC=te"**
    # loginProperty = "CN"
    loginProperty = "sAMAccountName"
    displayNameProperty = "displayName"
    userNameProperty = "CN"
    emailProperty = "mail"
    options {
      # If your LDAP configuration support email login
      useEmailBaseLogin = false
      fallbackToLocalLogin = false
      # If your LDAP configuration support English Name attribute
      englishNameAttributeName = "CN"
    }
}
