### ISSUE TITLE
이메일 설정 관련

### ISSUE THREAD

**Issue by twkimscl** [yona-projects/yona#667]
안녕하세요 @doortts 님 현재 요나 1.14버전 사용 중인데 

application.conf 설정에서 설정 후 메일이 전달되지 않아서 관련 문의 드립니다.

회사 메일 사용 중이고 SSL 사용 중입니다.

    # Mailer
    # ~~~~~~
    # You have to configure SMTP to send mails.
    # Example settings, it assume that you use gmail smtp
    smtp.host = smtp.회사.com
    smtp.port = 465
    smtp.ssl = true
    #smtp.user = yourGmailId
    smtp.user = 제메일 (ex yona@gmail.com일 때 yona 기입)
    # Be careful!!!
    smtp.password = 제패스워드 (""도 해보고 없이도 해봄)
    smtp.domain = 회사도메인 (ex yona@gmail.com일 때 gmail.com기입)
    #true to use mock mailer for testing, false for using real mail server
    smtp.mock = false
    # optional, size of mail archive for tests, default: 5
    smtp.archive.size = 5

위와 같이 설정하고 yona 재실행하면 메일이 전송되지 않습니다.

연결이 실패했다하고 log에는 id나 password를 다시 확인해보라는 메세지가 나왔는데 id나 password는 여러차례 확인 해봤지만 문제없었습니다.

뭐가 문젠지 조언 좀 부탁드립니다.

하단은 로그입니다. (제 구글 계정으로 테스트해봐도 동일한 에러 발생합니다)

[warn] application - Failed to send a notification: models.NotificationMail$EventEmail@3839a839
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtps.hiworks.com:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
        at org.apache.commons.mail.Email.send(Email.java:1437)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60)
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54)
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68)
        at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8)
        at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15)
        at models.NotificationMail.sendMail(NotificationMail.java:563)
        at models.NotificationMail.sendNotification(NotificationMail.java:419)
        at models.NotificationMail.access$100(NotificationMail.java:58)
        at models.NotificationMail$1.sendMail(NotificationMail.java:150)
        at models.NotificationMail$1.run(NotificationMail.java:113)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.mail.AuthenticationFailedException: 535 [AUTH] Access denied. Please check your username, password and POP3/SMTP settings.(#5.7.0)
        at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:823)
        at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:756)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:673)
        at javax.mail.Service.connect(Service.java:317)
        at javax.mail.Service.connect(Service.java:176)
        at javax.mail.Service.connect(Service.java:125)
        at javax.mail.Transport.send0(Transport.java:194)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
        ... 18 more

**Comment by twkimscl** [comment]
위와 관련해서 한번 봐주실 수 있을까요?
