### ISSUE TITLE
DB 관련 Exception 질문.

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#677]
지금 아래와 같은 Exception이 발생되고 있습니다.

`javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from recent_project where id=? and user_id=? and owner=? and project_id=? and project_name=?] bind[null]
        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:95)
        at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:54)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86)
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:48)
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:99)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:456)
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:592)
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:396)
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1867)
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1857)
        at com.avaje.ebean.Ebean.delete(Ebean.java:596)
        at play.db.ebean.Model.delete(Model.java:171)
        at models.RecentProject.deletePrevious(RecentProject.java:85)
        at models.RecentProject.addVisitHistory(RecentProject.java:68)
        at models.RecentProject.access$000(RecentProject.java:16)
        at models.RecentProject$1.apply(RecentProject.java:58)
        at models.RecentProject$1.apply(RecentProject.java:56)
        at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)`

이 Exception이 발생되는 원인이 될만한 추가적인 정보를 획득할 방법을 알 수 있으면 좋겠습니다.
사실 저 Exception이 지나치게 많이 발생되기도 합니다.
(제 짐작에서는 아마도 Jenkins의 1분마다 쿼리하는 것 때문인지도...)

문제 지점만이라도 찾으면 DB라든가, 저장소라든가 수리를 해야 할 것 같은데요.

**Comment by doortts** [comment]
사용하시는 Yona 의 버전이 어떻게 되세요?
무언가 굉장히 짧은 시간내에 지속적으로 페이지/프로젝트 접근이 일어나는 상황처럼 보입니다.

**Comment by neohind** [comment]
프로젝트 정리를 하느라 답변이 늦었네요;;;; 

현재 Yona 버전은 1.14 이며
Ubuntu 18 LTS 버전 Server 형태로 설치되어 있습니다.
MariaDB는 10.3.27 입니다.

네, Build 서버(Jenkins) 에서 5분마다 한번씩 Commit 상태를 주기적으로 조회하고 있어 자주 접근이 발생합니다. (프로젝트가 여러개다 보니, 5분이라는 주기가 미묘하게 겹치면 동시 접근이 좀 잦습니다.) 
이게 주효한 문제일까요?

아, 그리고 사실 지원 대상에서 벗어나는 항목 중 하나가 저 에러가 발생하는 부분이 아마도 SVN 쪽이지 않을까 조심스럽게 짐작합니다. 혹시 파악하는데 필요한 자료가 어떤것들이 있는지 알려주시면 더 Diggig을 해보도록 하겠습니다.

**Comment by doortts** [comment]
우선 에러자체는 특정 유저의 최근 방문 프로젝트 이력을 업데이트 하는 로직인데요 
만약 한 유저가 굉장히 빠른 시간내에 다른 프로젝트를 접근하는 상황이 펼쳐진다면 optimistic lock 예외가 발생할 가능성이 있습니다.
위에 설명하신 조건하에서라면 스케쥴러 계정이 접근으로 보이기때문에 특별히 신경 안쓰셔도 괜찮을 것 같습니다.

용어 참고: https://effectivesquid.tistory.com/entry/Optimistic-Lock%EA%B3%BC-Pessimistic-Lock

**Comment by neohind** [comment]
제가 이 부분에 대해서 신경쓴 이유가 많은 메모리를 사용하는 원인 중 아닐까 해서요.
위의 Exception 만 보이고, 특이한 이유 없이 DoS 상태에 빠져 있어서요.
그 이후 로그는 없는 것 같구요.
일단 그 때마다 서비스를 재시작시키기는 하는데요.

해당 상황의 로그 파일을 찾을 수 있으면 같이 첨부해보겠는데, 
지금 찾기가 좀 어려워서요;;;;;

일단, 제일 큰 원인은 Jenkins 측에서 스케쥴로 잡힌 빌드 타이밍을 쿼리하기 위한 설정일 가능성이 제일 클 것 같네요.
그것 부터 제거해보도록 하겠습니다.

감사합니다.

**Comment by doortts** [comment]
네 그런데 `DoS 상태`란 어떤 상황일까요?

**Comment by neohind** [comment]
아.. 이미 짐작은 아시겠지만, Denial of Service의 약자입니다.
그냥 서비스 거부 상태로 포트는 열려 있는데, 아무런 동작을 하지 않아서요.
원인 파악이 잘 안되서 결국 그냥 재시작 밖에는 특별히 해결 방법이 없어서요.

일단, Jenkins에서 스케쥴별로 빌드하는 방식을 모두 제거해보려고 합니다.
