### ISSUE TITLE
메일발송시 SSLHandshakeException이 납니다.

### ISSUE THREAD

**Issue by DevJScolon** [yona-projects/yona#695]
openjdk 1.8.0_292로 yona 1.14.0을 Ubuntu 20.04.2에서 사용중입니다.

아래와 같이 smtp설정후 메일발송시 SSLHandshakeException이 나는데 어떻게 하면 정상작동할까요?

------------------------------------------application.conf------------------------------------------------------
smtp.host=smtp.gmail.com
smtp.port=465
smtp.ssl=true
smtp.user="아이디@gmail.com"
smtp.password="비밀번호"
smtp.domain="gmail.com"
smtp.mock=false
smtp.archive.size=5

-------------------------------------------application.log--------------------------------------------------------
play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : smtp.gmail.com:465]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15) ~[info.schleichardt.play-2-mailplugin_2.10-0.9.1.jar:0.9.1]
        at controllers.SiteApp.sendMail(SiteApp.java:99) ~[yona.yona-1.14.0.jar:1.14.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$122$$anonfun$apply$122.apply(routes_routing.scala:3156) ~[yona.yona-1.14.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$122$$anonfun$apply$122.apply(routes_routing.scala:3156) ~[yona.yona-1.14.0.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at Global$2.call(Global.java:274) ~[yona.yona-1.14.0.jar:na]
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.14.0.jar:1.14.0]
        at utils.SiteManagerAuthAction.call(SiteManagerAuthAction.java:38) ~[yona.yona-1.14.0.jar:1.14.0]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:317) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:176) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Service.connect(Service.java:125) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Transport.send0(Transport.java:194) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at javax.mail.Transport.send(Transport.java:124) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        ... 48 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171) ~[na:1.8.0_292]
        at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98) ~[na:1.8.0_292]
        at sun.security.ssl.TransportContext.kickstart(TransportContext.java:220) ~[na:1.8.0_292]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:428) ~[na:1.8.0_292]
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:548) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:352) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:207) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1938) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        ... 55 common frames omitted

**Comment by doortts** [comment]
연동하시려는 구글 계정 설정에서 약한 보안으로 연결을 허용해야 할겁니다.

https://thefunky-monkey.com/page-364/google-smtp/
의 1단계를 참고해주세요.

나머지는 제대로 하신 것 같아요.

**Comment by DevJScolon** [comment]
답변 감사합니다.

하지만...가이드를 보고 이미 구글 '보안 수준이 낮은 앱의 액세스'의 '보안 수준이 낮은 앱 허용: 사용'을 설정해놓은 상태였습니다.

혹시 확인해야할 다른 부분 알고 계시면 부탁 드리겠습니다. 감사합니다.

**Comment by hongwonjun** [comment]
아마도 openjdk 에서 구글 서버의 인증서 문제가 발생하는 것 같습니다.

같은 이슈가 발생하였었고,
oracle jdk 8u221 로 자바를 변경하여서 해결했습니다.

**Comment by DevJScolon** [comment]
오라클jdk로 변경하여도 같은 에러를 마주하여...gmail을 포기하고 회사 메일 서버로 변경하여 해결하였습니다.

도움주신 두분 감사드립니다.
