### ISSUE TITLE
yona 시작 시 Database 'default' is in an inconsistent state! 에러가 발생합니다.

### ISSUE THREAD

**Issue by pay-dan-dy** [yona-projects/yona#704]
* MariaDB 버전: mysql  Ver 15.1 Distrib 10.6.3-MariaDB, for Linux (x86_64) using readline 5.1
* 해당 에러를 해소할 방법이 있을까요?

Play server process ID is 19320
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - 
Oops, cannot start the server.
@7kaopeh4e: Database 'default' is in an inconsistent state!
	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
	at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
	at scala.Option.map(Option.scala:145)
	at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.Play$.start(Play.scala:90)
	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
	at scala.Option.map(Option.scala:145)
	at play.core.server.NettyServer$.main(NettyServer.scala:284)
	at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
설치시점에 발생한 에러인가요?

**Comment by pay-dan-dy** [comment]
설치 후 yona를 실행하는 시점에서 발생한 에러입니다.
아래와 같이 실행 시도하니 DB 접속 과정에서 실패했습니다. 

sudo /usr/local/yona/bin/yona&

**Comment by doortts** [comment]
DB를 지우고 다시 설치를 시도하시면 대부분의 경우 문제가 해결됩니다. 아닐 경우에는 Maria DB 버전 문제일 가능성이 높습니다.
