### ISSUE TITLE
Exception caught in Netty

### ISSUE THREAD

**Issue by jwj9408** [yona-projects/yona#706]
yona version : 1.14.0
maria db version : 10.3.30
os : centos 7 

약 10시간 운영후 서버가 정지됩니다.
특정 작업중 정지되는것이 아니라 사용하지 않고 있다가 갑자기 정지되는 상태입니다.
이후 새로 서버가 켜지지도 않으며 ssh접속또한 막혀버려서 서버자체를 강제종료 후 켜야하는 상황입니다.

log를 열어보면 아래와 같은 오류가 찍혀있는상황인데요.
해결방법이 있을까요?

conf은 DB계정 이외 application.update.check.use = false로만 수정한 상황이며 
서버는 아래와 같은 restart.sh파일로 실행중입니다.
```
#!/bin/bash

PORT=27015
YONA_DATA=/home/jang/yona/yona-data;export YONA_DATA

kill `ps -ef | grep java | grep com.typesafe.play | awk '{print $2}'`
JAVA_OPTS="-Xmx8192m -Xms8192m -Dyona.data=$YONA_DATA -DapplyEvolutions.default=true -Dhttp.port=$PORT  -Dfile.encoding=UTF-8" nohup bin/yona </dev/null >/dev/null 2>&1 &

```

application.log
```
2021-07-27 12:20:01,623 - [ERROR] - from play.nettyException in New I/O worker #65 
Exception caught in Netty
java.lang.IllegalArgumentException: invalid version format: =FN￘3ﾔￒﾏﾬﾹﾆￎW￪￉ﾲ<￑ￕﾐ￴￼ﾄ[ￎ)￪  ﾊﾊ￀+￀/￀,￀0ￌﾩￌﾨ￀￀ ﾜ ﾝ / 5 ﾓZZ     ￿
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:102) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]
```

```
2021-07-27 12:20:01,668 - [ERROR] - from play.nettyException in New I/O worker #66 
Exception caught in Netty
java.lang.IllegalArgumentException: empty text
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:97) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [io.netty.netty-3.9.9.Final.jar:na]
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [io.netty.netty-3.9.9.Final.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_281]
```

**Comment by doortts** [comment]
- 10시간은 일정하게 10시간인가요?
- 사용하는 Java 의 버전은 어떻게 되나요?

**Comment by jwj9408** [comment]
- 시간은 최소 6시간~ 최대 24시간 사이에서 무작위로 발생합니다.
- java 1.8.0_281 입니다.

**Comment by jwj9408** [comment]
> * 10시간은 일정하게 10시간인가요?
> * 사용하는 Java 의 버전은 어떻게 되나요?

**Comment by jwj9408** [comment]
> * 10시간은 일정하게 10시간인가요?
> * 사용하는 Java 의 버전은 어떻게 되나요?

**Comment by doortts** [comment]
우선 버전체크 과련 위의 예외들은 문제되는 부분은 아닙니다.

> 이후 새로 서버가 켜지지도 않으며 ssh접속또한 막혀버려서 서버자체를 강제종료 후 켜야하는 상황

서버가 켜지지도 않는다는건 어떤 의미인가요? 무언가 가상환경으로 실행하고 계신가요?
메모리는 어느정도 할당해서 실행하셨나요?

**Comment by jwj9408** [comment]
- 서버 정지이후 centos 서버에 ssh접속을 하여도 타임아웃이 걸리며 접속이 되지않는 현상과,
직접 서버에 키보드 모니터를 연결하여 본문에 작성해둔 restart.sh를 이용하여 재시작, 혹은 RUNNING_PID를 제거후 시작을 하여도 홈페이지에 열리지 않아 접속할수가 없었습니다.

- 메모리는 "-Xmx8192m -Xms8192m" 를 통하여 8기가로 실행하였습니다.

아래 로그는 서버 재시작후 남아있는 로그이며 ERROR는 없고 WARN만 존재합니다.
```
2021-07-27 15:49:39,309 - [WARN] - from application in application-akka.actor.default-dispatcher-2 
Failed!! User uploaded temporary files clean-up action failed!
javax.persistence.PersistenceException: java.sql.SQLTransientException: (conn:143) Connection was killed
Query is : set autocommit=0
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findList(DefaultExpressionList.java:173) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at models.Attachment$3.removeUserTemporaryFiles(Attachment.java:461) ~[yona.yona-1.14.0.jar:1.14.0]
	at models.Attachment$3.run(Attachment.java:450) ~[yona.yona-1.14.0.jar:1.14.0]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:687) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:640) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:807) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:810) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.sql.SQLTransientException: (conn:143) Connection was killed
Query is : set autocommit=0
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:140) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:258) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:387) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:581) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at com.jolbox.bonecp.ConnectionHandle.setAutoCommit(ConnectionHandle.java:1292) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.wrap(EbeanPlugin.java:144) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.getConnection(EbeanPlugin.java:157) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:312) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 42 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Connection was killed
Query is : set autocommit=0
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:137) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:249) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	... 48 common frames omitted

2021-07-27 15:49:39,311 - [WARN] - from application in application-akka.actor.default-dispatcher-2 
Error occurred while sending notification mails
javax.persistence.PersistenceException: java.sql.SQLTransientException: (conn:140) Connection was killed
Query is : set autocommit=0
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:338) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.createQueryTransaction(DefaultServer.java:2067) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.OrmQueryRequest.initTransIfRequired(OrmQueryRequest.java:176) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1501) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:890) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at models.NotificationMail$1.sendMail(NotificationMail.java:137) ~[yona.yona-1.14.0.jar:1.14.0]
	at models.NotificationMail$1.run(NotificationMail.java:113) ~[yona.yona-1.14.0.jar:1.14.0]
	at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.collection.Iterator$class.foreach(Iterator.scala:727) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:687) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:616) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:640) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:807) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:810) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:803) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:637) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.sql.SQLTransientException: (conn:140) Connection was killed
Query is : set autocommit=0
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:140) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:258) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeUpdate(MariaDbStatement.java:387) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbConnection.setAutoCommit(MariaDbConnection.java:581) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at com.jolbox.bonecp.ConnectionHandle.setAutoCommit(ConnectionHandle.java:1292) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.wrap(EbeanPlugin.java:144) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at play.db.ebean.EbeanPlugin$WrappingDatasource.getConnection(EbeanPlugin.java:157) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
	at com.avaje.ebeaninternal.server.transaction.TransactionManager.createQueryTransaction(TransactionManager.java:312) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 41 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Connection was killed
Query is : set autocommit=0
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1114) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:137) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:249) ~[org.mariadb.jdbc.mariadb-java-client-1.5.5.jar:na]
	... 47 common frames omitted


```

**Comment by doortts** [comment]
@jwj9408 어떻게 해결되었나요?

**Comment by jwj9408** [comment]
@doortts centos 서버자체가 멈추면서 생기는 현상이었습니다. 
알수없는 이유로 서버자체가 멈출때 요나에서 에러를 출력하는것으로 보이며 프로젝트상에는 문제가 없어보여 이슈를 닫았습니다.

감사합니다.

**Comment by doortts** [comment]
네. 알려주셔서 감사합니다!:)
