### ISSUE TITLE
서버 구축 중 최초 실행이 되지 않습니다. (sql 구문에러)

### ISSUE THREAD

**Issue by tomorrow9913** [yona-projects/yona#722]
환경 구성 후 관리자 권한으로 yona.bat파일을 실행하였습니다.

sql 구문 에러가 발생합니다.

OS windows10
yona version 1.15.0
mariaDB version 
```
MariaDB [(none)]> status
--------------
mysql  Ver 15.1 Distrib 10.1.20-MariaDB, for Win64 (AMD64)

Connection id:          54
Current database:
Current user:           root@localhost
SSL:                    Not in use
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.1.20-MariaDB mariadb.org binary distribution
Protocol version:       10
```
java version
```
java --version
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

bin의 yona.batch 실행결과는 아래와 같습니다.

```
C:\yona\yona-1.15.0> .\bin\yona.bat
Play server process ID is 3312
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - (conn:22) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CONSTRAINT IF EXISTS ck_attachment_container_type' at line 1
Query is : ALTER TABLE attachment DROP CONSTRAINT IF EXISTS ck_attachment_container_type [ERROR:1064, SQLSTATE:42000]
Oops, cannot start the server.
@7l66li0hk: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:284)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

시도해본 방법 
#365 방법 2

**Comment by tomorrow9913** [comment]
#365 방법 1로 해결 마리아디비 10.2업데이트
