### ISSUE TITLE
1.15 git push remote rejected 에러

### ISSUE THREAD

**Issue by moonggae** [yona-projects/yona#725]
git push 할 때에 remote rejected 에러가 발생합니다.

client
PS C:\project> git push origin master
Enumerating objects: 424, done.
Counting objects: 100% (424/424), done.
Delta compression using up to 8 threads
Compressing objects: 100% (417/417), done.
Writing objects: 100% (424/424), 11.30 MiB | 4.32 MiB/s, done.
Total 424 (delta 104), reused 0 (delta 0), pack-reused 0
error: remote unpack failed: error 그런 파일이나 디렉터리가 없습니다
To http://url:9000/group/project
 ! [remote rejected] master -> master (n/a (unpacker error))
error: failed to push some refs to 'http://url:9000/group/project'

logs/root.log
2021-09-28 17:26:43,271 - [INFO] - from access./group/project/info/refs?service=git-receive-pack in play-akka.actor.default-dispatcher-4
10.20.30.142 - myaccount [28/Sep/2021:17:26:43 +0900] "GET /group/project/info/refs?service=git-receive-pack HTTP/1.1" 200 - - "git/2.29.2.windows.2" 157ms

2021-09-28 17:26:44,408 - [INFO] - from access./group/project/git-receive-pack in play-akka.actor.default-dispatcher-4
10.20.30.142 - myaccount [28/Sep/2021:17:26:44 +0900] "POST /group/project/git-receive-pack HTTP/1.1" 200 - - "git/2.29.2.windows.2" 165ms

2021-09-28 17:26:46,810 - [INFO] - from access./group/project/git-receive-pack in play-akka.actor.default-dispatcher-8
10.20.30.142 - myaccount [28/Sep/2021:17:26:46 +0900] "POST /group/project/git-receive-pack HTTP/1.1" 200 - - "git/2.29.2.windows.2" 74ms

2021-09-28 17:26:47,391 - [ERROR] - from application in Thread-9
receivePack failed
org.eclipse.jgit.errors.UnpackException: Exception while parsing pack stream
        at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:307) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.ReceivePack.receive(ReceivePack.java:206) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at playRepository.RepositoryService$2.run(RepositoryService.java:290) ~[yona.yona-1.15.0.jar:1.15.0]
Caused by: java.io.IOException: 그런 파일이나 디렉터리가 없습니다
        at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_292]
        at java.io.File.createTempFile(File.java:2063) ~[na:1.8.0_292]
        at org.eclipse.jgit.internal.storage.file.ObjectDirectoryPackParser.parse(ObjectDirectoryPackParser.java:190) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.BaseReceivePack.receivePack(BaseReceivePack.java:1308) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.BaseReceivePack.receivePackAndCheckConnectivity(BaseReceivePack.java:1045) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        at org.eclipse.jgit.transport.ReceivePack.service(ReceivePack.java:250) ~[org.eclipse.jgit.org.eclipse.jgit-4.5.0.201609210915-r.jar:4.5.0.201609210915-r]
        ... 2 common frames omitted

**Comment by doortts** [comment]
> Caused by: java.io.IOException: 그런 파일이나 디렉터리가 없습니다

에러의 경우, repo 폴더가 없거나 접근 권한이 없을 경우에 발생합니다.
혹시 디렉터리를 이동하진 않으셨나요?
