### ISSUE TITLE
프로젝트 삭제 오류

### ISSUE THREAD

**Issue by pokev25** [yona-projects/yona#73]
프로젝트 삭제시 오류가 발생하며 삭제 되지 않습니다.

```
play.api.Application$$anon$1: Execution exception[[PersistenceException: ERROR executing DML bindLog[] error[Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))]]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:97) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:48) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:99) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:456) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:592) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:396) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1867) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1857) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebean.Ebean.delete(Ebean.java:596) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at play.db.ebean.Model.delete(Model.java:171) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at models.Project.delete(Project.java:674) ~[yona.yona-1.0.2.jar:1.0.2]
	at controllers.ProjectApp.deleteProject(ProjectApp.java:342) ~[yona.yona-1.0.2.jar:1.0.2]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$103$$anonfun$apply$103.apply(routes_routing.scala:2450) ~[yona.yona-1.0.2.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$103$$anonfun$apply$103.apply(routes_routing.scala:2450) ~[yona.yona-1.0.2.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at Global$1.call(Global.java:190) ~[yona.yona-1.0.2.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.0.2.jar:1.0.2]
	at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yona.yona-1.0.2.jar:1.0.2]
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:85) ~[yona.yona-1.0.2.jar:1.0.2]
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:21) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebean.Ebean.execute(Ebean.java:1264) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted
Caused by: java.sql.BatchUpdateException: Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:374) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:347) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205) ~[com.jolbox.bonecp-0.8.0.RELEASE.jar:na]
	at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:55) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:53) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
	... 60 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:119) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeQueryEpilog(MariaDbServerPreparedStatement.java:336) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:291) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:369) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	... 65 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:479) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:592) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:279) ~[org.mariadb.jdbc.mariadb-java-client-1.3.6.jar:na]
	... 66 common frames omitted

2016-07-14 07:25:39,706 - [ERROR] - from play in play-akka.actor.default-dispatcher-76 
Cannot invoke the action, eventually got an error: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[Cannot delete or update a parent row: a foreign key constraint fails (`yona`.`project_visitation`, CONSTRAINT `fk_project_visitation_project_31` FOREIGN KEY (`project_id`) REFERENCES `project` (`id`))]
```

**Comment by doortts** [comment]
@pokev25 사용하시는 yona 버전이 어떻게 되세요? 문제 원인은 프로젝트 방문기록을 저장해 놓는 로직에서 FK 제약조건으로 인해 삭제가 안되는 것 같습니다. 저도 살펴보겠습니다.

**Comment by pokev25** [comment]
1.02 사용중입니다.

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/releases/tag/v1.0.3 에서 해결합니다
