### ISSUE TITLE
docker 환경에서 yona 서비스 재시작 시 테이블 생성하려는 문제가 있습니다.

### ISSUE THREAD

**Issue by lingo2020** [yona-projects/yona#739]
안녕하세요.

nayasis님이 만드신 docker-compose 구성을 사용해서 문제없이 잘 사용하고 있었습니다.

yona버전이 1.5버전이 있어 덮어쓰기 해서, db 마이그레이션 작업까지 정상적으로 나오는 것을
확인했습니다.

그런데 이번에 서버 재시작 작업을 해야해서, docker를 재시작 해봤는데 yona가 정상적으로
실행이 되지 않았습니다. 에러를 확인해 보니 아래와 같이 테이블을 생성하려다가 오류가 난 것 같습니다.

```
[error] play - (conn:12) Table 'assignee' already exists
yona  | Query is : create table assignee (
yona  | id                        bigint auto_increment not null,
yona  | user_id                   bigint,
yona  | project_id                bigint,
yona  | constraint pk_assignee primary key (id)) [ERROR:1050, SQLSTATE:42S01]
yona  | Oops, cannot start the server.
yona  | @7m6ienak7: Database 'default' is in an inconsistent state!
yona  | 	at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
yona  | 	at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
yona  | 	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
yona  | 	at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
yona  | 	at scala.Option.map(Option.scala:145)
yona  | 	at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
yona  | 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
yona  | 	at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
yona  | 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
yona  | 	at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
yona  | 	at scala.collection.immutable.List.foreach(List.scala:318)
yona  | 	at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
yona  | 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
yona  | 	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
yona  | 	at scala.collection.immutable.List.foreach(List.scala:318)
yona  | 	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
yona  | 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
yona  | 	at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
yona  | 	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
yona  | 	at play.api.Play$.start(Play.scala:90)
yona  | 	at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
yona  | 	at play.core.server.NettyServer$.createServer(NettyServer.scala:253)
yona  | 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:289)
yona  | 	at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:284)
yona  | 	at scala.Option.map(Option.scala:145)
yona  | 	at play.core.server.NettyServer$.main(NettyServer.scala:284)
yona  | 	at play.core.server.NettyServer.main(NettyServer.scala)
```

mariadb에 기존 테이블이 모두 있는데, 서비스 시작 시 테이블 생성하려고 하네요.
어떤 부분을 확인해서 바꿔줘야 기존 테이블을 사용할까요?

답변 부탁 드립니다. 감사합니다.

**Comment by lingo2020** [comment]
이전 버전을 db 마이그레이션 했는데, play_evolutions 테이블은 생성을 했는데 데이터를 추가하지 않으니
테이블을 생성하려고 하네요. 해당 데이터를 입력하니 테이블을 생성하려고 하지 않네요.
참고하세요.

**Comment by doortts** [comment]
@lingo2020 공유감사합니다!
