### ISSUE TITLE
이메일 발송관련

### ISSUE THREAD

**Issue by neohind** [yona-projects/yona#746]
안녕하세요,

프로젝트 이관 중에 확인 메일이 안와서 이상하다 싶어서 확인하니까,
현재 메일에서 계속 오류가 발생합니다.

먼저 제쪽 환경은 아래와 같습니다.
[OS]
Ubuntu - 16.04.7 LTS (Xenial Xerus)

[Java]
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

[Yona]
1.15.0

[application.conf / SMTP]
smtp.host = smtp.gmail.com
smtp.port = 587
smtp.ssl = true
smtp.user = "---@gmail.com"
smtp.password = "----------"
smtp.domain = gmail.com
smtp.mock = false
smtp.archive.size = 5

현재 오류 로그내용은 아래와 같습니다.

play.api.Application$$anon$1: Execution exception[[**EmailException: Sending the email to the following server failed : smtp.gmail.com:465**]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        ....
Caused by: org.apache.commons.mail.EmailException: **Sending the email to the following server failed : smtp.gmail.com:465**
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        at org.apache.commons.mail.Email.send(Email.java:1437) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
       ....
Caused by: javax.mail.MessagingException: **Could not connect to SMTP host: smtp.gmail.com, port: 465**
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642) ~[javax.mail.mail-1.4.5.jar:1.4.5]
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400) ~[org.apache.commons.commons-email-1.3.3.jar:1.3.3]
        ... 48 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: **No appropriate protocol (protocol is disabled or cipher suites are inappropriate)**
        at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171) ~[na:1.8.0_292]
        at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98) ~[na:1.8.0_292]
        ... 55 common frames omitted

위의 문제가 생겨서, 다른 gmail 계정으로 바꿔보기도 했으며,
이상하게 465 포트로만 연결이 실패하는 것 같아서, 587로 변경도 해봤습니다.
(위의 설정이 변경 후)
그리고 접속 이력을 확인해본 결과 서버와의 연결조차 되지 않았습니다.

그래서 이번에는 smtp.gmail.com 이 연결이 안되는줄 알았는데,
ping 하니 정상적으로 서버와 연결되었으며,
`telnet smtp.gmail.com 465 `
해봤는데, 이 역시 연결이 되었습니다.

구글로 No appropriate protocol (protocol is disabled or cipher suites are inappropriate) 문제를 보긴했는데,
Java 1.8 이상이면 동작하는데는 문제가 없을 것이라는 답변만....

혹시 이 문제와 관련되어 제가 더 확인해봐야 될 부분이 있을까요?

**Comment by doortts** [comment]
우선 gmail SMTP 를 이용하려면 해당 계정 설정에서 less secure app access 옵션을 선택하셔야 합니다.
https://kb.synology.com/en-global/SRM/tutorial/How_to_use_Gmail_SMTP_server_to_send_emails_for_SRM

참고로 repo.yona.io 는 465 port 를 
user 에서는 @gmail.com 을 제외한 나머지 부분을 id로 사용하고 있습니다.

**Comment by jaew00ng74** [comment]
저도 동일 문제를 격고 있는데, less secure app access 옵션을 선택도 해준 상태 입니다.  에러 log는 동일합니다. 

[error] play - Cannot invoke the action, eventually got an error: org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com.:465
[error] application -

! @7mmhm91le - Internal server error, for (POST) [/sites/mail] ->

play.api.Application$$anon$1: Execution exception[[EmailException: Sending the email to the following server failed : smtp.gmail.com.:465]]


# Mailer
# ~~~~~~
# You have to configure SMTP to send mails.
# Example settings, it assume that you use gmail smtp
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.auth = true
smtp.user = "****yonaserver****"
# Be careful!!! Not to leak password
smtp.password = "******************"
smtp.domain = gmail.com
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

**Comment by jaew00ng74** [comment]
혹시 MariaDB  버전이 10.7.3 인데 연관이 있을까요?

**Comment by doortts** [comment]
> 혹시 MariaDB 버전이 10.7.3 인데 연관이 있을까요?

이메일 발송과는 연관은 없을것 같습니다.

**Comment by jaew00ng74** [comment]
일단 구글 보안 수준이 낮은 앱의 액세스 사용으로 설정된 상태입니다. 
587 port로 설정하면 
Caused by: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 **Must issue a STARTTLS command first**. p10-20020a056a000b4a00b004e12fd48035sm1332356pfo.96 - gsmtp
log 출력되면서 smtp.gmail.com:587 로 메일을 보내지 못한다고 하고 

465 port로 설정하면 
Caused by: javax.net.ssl.SSLHandshakeException: **No appropriate protocol (protocol is disabled or cipher suites are inappropriate)**

JDK 버전은 1.8 이상이고요. 
$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~18.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

yona 버전은 
현재 버전은 1.15.0 입니다
현재 최신 버전을 사용중입니다

**Comment by neohind** [comment]
SMTP 관련 인증서 저장소의 문제인가 싶기도하고, openssl 문제인가 싶기도 하고, 짐작이 가질 않아서...

일단 현재 우분투 서버인지라, Workaround로 현재는 smtp 서버를 설치해서 
해당 smtp 서버에서 gmail과 연결하고,
yona는 local에 설치된 smtp를 부르는 방식으로 변경해서 일단을 돌리고 있습니다.
물론 방화벽으로 로컬에 한정되서 send 되게는 했지만, 역시 좀 불안 불안합니다.

postfix로 설치한 뒤, smtp만 처리했습니다.

**Comment by jaew00ng74** [comment]
일단 메일 보내기 성공했습니다. 
/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security
파일안에 TLSv1.1, TSSv1, SSLv3을 지워서 

예시>
jdk.tls.disabledAlgorithms=RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves

지원하는 SocketProtocols 을 
Enabled protocols:
TLSv1.2
TLSv1.1
TLSv1
SSLv3
모두 풀었습니다. 

protocols 확인 용 앱 코드 
참고: https://stackoverflow.com/questions/28236091/how-to-enable-ssl-3-in-java

gmail 은 2차 인증 사용에 예외 앱을 email 앱 기타로 설정했습니다. 
앱 비빌번호를 사용하고요. 

예시>
smtp.host = smtp.gmail.com
smtp.port = 465
smtp.ssl = true
smtp.user = "username"
# Be careful!!! Not to leak password
smtp.password = "apppassword"
smtp.domain = gmail.com
#true to use mock mailer for testing, false for using real mail server
smtp.mock = false
# optional, size of mail archive for tests, default: 5
smtp.archive.size = 5

**Comment by msseodev** [comment]
오 감사합니다. 
같은 문제 있었는데 위 방법으로 되네요

**Comment by neohind** [comment]
앞서 제가 언급한 문제에서 조금 벗어났지만... 
요즘 google에서 슬슬 SMTP 인증 방식을 막기 시작해서, 현재는 naver.com 의 SMTP로 갈아타는 중입니다.
아래 처럼 변경했습니다.
```
smtp.startssl = true
smtp.host = smtp.naver.com
smtp.port = 587
smtp.auth = true
smtp.password = "?????????"
smtp.domain = naver.com
smtp.user = "??????@naver.com"
```

문제는 아래와 같은 오류를 마구 뱉습니다.

```
2024-03-06 13:26:51,466 - [WARN] - from application in play-akka.actor.default-dispatcher-974 
Failed to send a notification: org.apache.commons.mail.HtmlEmail@1720365d
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.naver.com:465
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
	at org.apache.commons.mail.Email.send(Email.java:1437)
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:60)
	at info.schleichardt.play2.mailplugin.MailPlugin$$anonfun$6.apply(MailPlugin.scala:54)
	at info.schleichardt.play2.mailplugin.MailPlugin.send(MailPlugin.scala:68)
	at info.schleichardt.play2.mailplugin.api.Mailer$.send(Mailer.scala:8)
	at info.schleichardt.play2.mailplugin.Mailer.send(Mailer.java:15)
	at controllers.ProjectApp.sendTransferRequestMail(ProjectApp.java:775)
	at controllers.ProjectApp.transferProject(ProjectApp.java:634)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$191$$anonfun$apply$191.apply(routes_routing.scala:3708)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$191$$anonfun$apply$191.apply(routes_routing.scala:3708)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at Global$2.call(Global.java:274)
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57)
	at actions.IsAllowedAction.call(IsAllowedAction.java:68)
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:93)
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:21)
	at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18)
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715)
	at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709)
	at com.avaje.ebean.Ebean.execute(Ebean.java:1264)
	at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:485)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.naver.com, port: 465;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1972)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:642)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
	... 56 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:171)
	at sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at sun.security.ssl.TransportContext.kickstart(TransportContext.java:227)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:548)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:352)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:207)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1938)
	... 63 more
```

그래서 sendmail / postfix의 중계기를 중간에 둘까도 고민해보고, 다양한 설정을 변경해보기도 하고,
다른 SMTP 를 뒤적거리면서 한참을 고민했습니다.
그러다가, @jaew00ng74  답변글을 보다가, 링크에 걸린 내용 중 "JRE_HOME/lib/security/java.security" 에 있는 설정 중, SSLv3 및 TLSv1 등등을 삭제해보는게 어떨까... 라는 내용이 보이더군요.

그래서 find | grep java.security 파일을 찾았고, 해당 파일을 열어 jdk.tls 로 검색하니 아래와 같은 내용이 나오더군요.
`jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, \
    DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL, \
    include jdk.disabled.namedCurves`
그래서 SSLv3 및 TLSv1, TLSv1.1 을 삭제하고 메일 전송을 하니, 이제 에러가 안나는 것 같습니다. 

여튼 application.log 내의 에러메시지 중에 'javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)' 가 보이면 일단 저와 같은 방법으로 처리하시면 될 것 같습니다.
