### ISSUE TITLE
sidebar 관련 조회하면서 오류가 나는것 같은데... 확인 부탁드립니다.

### ISSUE THREAD

**Issue by levelupsoft** [yona-projects/yona#755]
[error] play - Cannot invoke the action, eventually got an error: java.lang.IllegalArgumentException: Comparison method violates its general contract!
[error] application - 

! @7nmhl5aaf - Internal server error, for (GET) [/yobi/user/sidebar?path=/yobi/user/sidebar&hash=] ->

play.api.Application$$anon$1: Execution exception[[IllegalArgumentException: Comparison method violates its general contract!]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(Unknown Source) ~[na:na]
	at java.base/java.util.TimSort.mergeAt(Unknown Source) ~[na:na]
	at java.base/java.util.TimSort.mergeForceCollapse(Unknown Source) ~[na:na]
	at java.base/java.util.TimSort.sort(Unknown Source) ~[na:na]
	at java.base/java.util.Arrays.sort(Unknown Source) ~[na:na]

이 오류가 나면서 화면이 무한 반복 refresh가 됩니다.

**Comment by doortts** [comment]
브라우저에서 캐쉬를 지워보시고
https://{설정하신URL}/logout
로 접근해서 로그아웃을 시도해보시겠어요?
