### ISSUE TITLE
yona-1.14.0 사용중 프로젝트 삭제 시 오류발생

### ISSUE THREAD

**Issue by scltech1234** [yona-projects/yona#760]
프로젝트를 삭제하는 중에 오류가 발생했습니다

라는 메시지와 함께 프로젝트 삭제가 되지 않습니다.

특정 프로젝트에서만 이런 현상이 일어나는 것으로 보입니다

어떤 문제인지 알 수 있을까요?

**Comment by scltech1234** [comment]
특이 현상으로 특정 프로젝트에서만 이런 현상이 일어나는 것으로 보입니다

**Comment by doortts** [comment]
서버 에러 메시지가 있어야 확실히 알 수 있을것 같습니다.  
사용하시는 OS 와 Java 버전, DB 버전도 함께 알려주세요.

**Comment by scltech1234** [comment]
사용 
os는 우분투 16.04
자바는 javac 9-internal
db의 경우 확인 터미널에서 확인되지 않는것 같습니다.
확인 방법을 알 수 있을까요.

**Comment by doortts** [comment]
yona 가 설치된 디렉터리 하위 logs 디렉터리에 root.log 나 application.log 에 로그가 남아 있을것 같습니다.

**Comment by scltech1234** [comment]
답변이 늦어져서 죄송합니다.

디렉토리 내부의 로그를 뒤져 보았지만 db의 버전을 확인해 보려 했으나 찾지 못했습니다.
다른 방법이 없을까요?

**Comment by doortts** [comment]
프로젝트 삭제시점에 로그에 남게되는 에러가 확인가능할까요?

**Comment by scltech1234** [comment]
! @7p1j4kbof - Internal server error, for (DELETE) [/admin/MINDFORGE/delete] ->

play.api.Application$$anon$1: Execution exception[[OptimisticLockException: Data has changed. updated [0] rows sql[delete from issue_comment where id=? and created_date=? and author_id=? and author_login_id=? and author_name=? and project_id=? and issue_id=? and parent_comment_id=?] bind[null]]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: javax.persistence.OptimisticLockException: Data has changed. updated [0] rows sql[delete from issue_comment where id=? and created_date=? and author_id=? and author_login_id=? and author_name=? and project_id=? and issue_id=? and parent_comment_id=?] bind[null]
        at com.avaje.ebeaninternal.server.persist.dml.DmlHandler.checkRowCount(DmlHandler.java:95) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DeleteHandler.execute(DeleteHandler.java:54) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:86) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.delete(DmlBeanPersister.java:48) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeDeleteBean(DefaultPersistExecute.java:99) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:456) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:478) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:592) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.persist.DefaultPersister.delete(DefaultPersister.java:396) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1867) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.delete(DefaultServer.java:1857) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebean.Ebean.delete(Ebean.java:596) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at play.db.ebean.Model.delete(Model.java:171) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at models.Comment.delete(Comment.java:97) ~[yona.yona-1.14.0.jar:1.14.0]
        at models.AbstractPosting.delete(AbstractPosting.java:225) ~[yona.yona-1.14.0.jar:1.14.0]
        at models.Project.delete(Project.java:728) ~[yona.yona-1.14.0.jar:1.14.0]
        at controllers.ProjectApp.deleteProject(ProjectApp.java:346) ~[yona.yona-1.14.0.jar:1.14.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$177$$anonfun$apply$177.apply(routes_routing.scala:3596) ~[yona.yona-1.14.0.jar:na]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$177$$anonfun$apply$177.apply(routes_routing.scala:3596) ~[yona.yona-1.14.0.jar:na]
        at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at Global$2.call(Global.java:274) ~[yona.yona-1.14.0.jar:na]
        at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.14.0.jar:1.14.0]
        at actions.IsAllowedAction.call(IsAllowedAction.java:68) ~[yona.yona-1.14.0.jar:1.14.0]
        at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:93) ~[yona.yona-1.14.0.jar:1.14.0]
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:21) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebean.Ebean.execute(Ebean.java:1264) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at play.db.ebean.TransactionalAction.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
        at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
        ... 6 common frames omitted

2022-09-14 11:12:35,852 - [INFO] - from access./admin/MINDFORGE/delete in play-akka.actor.default-dispatcher-7881
192.168.1.52 - - [14/Sep/2022:11:12:35 +0900] "DELETE /admin/MINDFORGE/delete HTTP/1.1" 500 - "http://192.168.1.50:9000/admin/MINDFORGE/deleteform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" -

2022-09-14 11:12:39,822 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7884
210.99.111.32 - yoonkyujin [14/Sep/2022:11:12:39 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:12:46,823 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7881
210.99.111.32 - yoonkyujin [14/Sep/2022:11:12:46 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:12:54,823 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7884
210.99.111.32 - yoonkyujin [14/Sep/2022:11:12:54 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:13:03,818 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7881
210.99.111.32 - yoonkyujin [14/Sep/2022:11:13:03 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 1ms

2022-09-14 11:13:04,569 - [INFO] - from access./-_-api/v1/owners/tweed/projects/ASTEL/issues/4/detectChange in play-akka.actor.default-dispatcher-7884
192.168.1.52 - tweed [14/Sep/2022:11:13:04 +0900] "POST /-_-api/v1/owners/tweed/projects/ASTEL/issues/4/detectChange HTTP/1.1" 200 - "http://192.168.1.50:9000/tweed/ASTEL/issue/4" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" 1ms

2022-09-14 11:13:14,817 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7881
210.99.111.32 - yoonkyujin [14/Sep/2022:11:13:14 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 1ms

2022-09-14 11:13:21,490 - [INFO] - from access./admin/MINDFORGE/deleteform in play-akka.actor.default-dispatcher-7884
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /admin/MINDFORGE/deleteform HTTP/1.1" 200 - "http://192.168.1.50:9000/sites/userList" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 5ms

2022-09-14 11:13:21,519 - [INFO] - from access./messages.js in play-akka.actor.default-dispatcher-7891
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /messages.js HTTP/1.1" 200 - "http://192.168.1.50:9000/admin/MINDFORGE/deleteform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:13:21,547 - [INFO] - from access./user/sidebar?path=/admin/MINDFORGE/deleteform&hash= in play-akka.actor.default-dispatcher-7892
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /user/sidebar?path=/admin/MINDFORGE/deleteform&hash= HTTP/1.1" 200 - "http://192.168.1.50:9000/admin/MINDFORGE/deleteform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 8ms

2022-09-14 11:13:21,578 - [INFO] - from access./messages.js in play-akka.actor.default-dispatcher-7891
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /messages.js HTTP/1.1" 200 - "http://192.168.1.50:9000/user/sidebar?path=/admin/MINDFORGE/deleteform&hash=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:13:21,615 - [INFO] - from access./admin/MINDFORGE/deleteform in play-akka.actor.default-dispatcher-7891
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /admin/MINDFORGE/deleteform HTTP/1.1" 200 - "http://192.168.1.50:9000/user/sidebar?path=/admin/MINDFORGE/deleteform&hash=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 5ms

2022-09-14 11:13:21,659 - [INFO] - from access./messages.js in play-akka.actor.default-dispatcher-7881
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /messages.js HTTP/1.1" 200 - "http://192.168.1.50:9000/admin/MINDFORGE/deleteform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 2ms

2022-09-14 11:13:21,661 - [INFO] - from access./-_-api/v1/owners/jm/projects/FS%EC%86%94%EB%A3%A8%EC%85%98/issues/43/detectChange in play-akka.actor.default-dispatcher-7891
121.133.232.153 - yj7840 [14/Sep/2022:11:13:21 +0900] "POST /-_-api/v1/owners/jm/projects/FS%EC%86%94%EB%A3%A8%EC%85%98/issues/43/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/FS%EC%86%94%EB%A3%A8%EC%85%98/issue/43" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36" 2ms

2022-09-14 11:13:21,880 - [INFO] - from access./user/usermenuTabContentList in play-akka.actor.default-dispatcher-7884
192.168.1.52 - admin [14/Sep/2022:11:13:21 +0900] "GET /user/usermenuTabContentList HTTP/1.1" 200 - "http://192.168.1.50:9000/admin/MINDFORGE/deleteform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 143ms

2022-09-14 11:13:27,819 - [INFO] - from access./-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange in play-akka.actor.default-dispatcher-7891
210.99.111.32 - yoonkyujin [14/Sep/2022:11:13:27 +0900] "POST /-_-api/v1/owners/jm/projects/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issues/14/detectChange HTTP/1.1" 200 - "http://112.169.213.195:9000/jm/%ED%8C%8C%EC%9D%B8%ED%8A%B8%EB%A6%AC/issue/14" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33" 1ms

**Comment by scltech1234** [comment]
이 로그가 맞을까요

**Comment by doortts** [comment]
우선 해당 프로젝트 멤버들을 다 제거한 다음 프로젝트를 삭제해 보시겠어요?

**Comment by scltech1234** [comment]
저도 가장 먼저 맴버들을 비우고 삭제 시도 했습니다만 같은 현상이 지속되고 있습니다.

**Comment by doortts** [comment]
조금 부끄러운데, Yona 서버를 재시작 후 삭제 시도 해보시겠어요?

**Comment by scltech1234** [comment]
부끄러우실 이유는 없습니다.
도와주시는 것만으로도 감사하죠.

서버를 완벽히 reboot 후에 시도할때도 삭제에 실패하고 있습니다.

이런 경우가 처음인건가요?
