### ISSUE TITLE
README 오류

### ISSUE THREAD

**Issue by hadesyi** [yona-projects/yona#79]
OS: windows 2008 R2 64bit
db : mysql
버전 : yona-1.0.2
admin 관리자에서는 readme 등록이 잘됩니다.
하지만 user에서는 오류가 발생합니다.
오류 내용은 아래와 같습니다.

2016-08-10 02:59:57,169 - [INFO] - from application in play-akka.actor.default-dispatcher-22 
No tree or no README file found at E:\yona-1.0.2\bin\repo\git\planning\iccsWs.git

2016-08-10 02:59:57,185 - [ERROR] - from application in play-akka.actor.default-dispatcher-22 
Missing unknown 0000000000000000000000000000000000000000

2016-08-10 02:59:57,247 - [ERROR] - from play in play-akka.actor.default-dispatcher-22 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2016-08-10 02:59:57,247 - [ERROR] - from application in play-akka.actor.default-dispatcher-22 

! @7131cch8c - Internal server error, for (GET) [/planning/iccsWs/post/1] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
    at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
    at utils.Markdown.renderWithHighlight(Markdown.java:134) ~[yona.yona-1.0.2.jar:1.0.2]
    at utils.Markdown.render(Markdown.java:212) ~[yona.yona-1.0.2.jar:1.0.2]
    at utils.Markdown.render(Markdown.java:217) ~[yona.yona-1.0.2.jar:1.0.2]
    at views.html.board.view$.apply(view.template.scala:128) ~[yona.yona-1.0.2.jar:1.0.2]
    at views.html.board.view$.render(view.template.scala:233) ~[yona.yona-1.0.2.jar:1.0.2]
    at views.html.board.view.render(view.template.scala) ~[yona.yona-1.0.2.jar:1.0.2]
    at controllers.BoardApp.post(BoardApp.java:264) ~[yona.yona-1.0.2.jar:1.0.2]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(routes_routing.scala:2290) ~[yona.yona-1.0.2.jar:na]
    at Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(routes_routing.scala:2290) ~[yona.yona-1.0.2.jar:na]
    at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at Global$1.call(Global.java:190) ~[yona.yona-1.0.2.jar:na]
    at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.0.2.jar:1.0.2]
    at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yona.yona-1.0.2.jar:1.0.2]
    at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:85) ~[yona.yona-1.0.2.jar:1.0.2]
    at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
    at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
    at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
    ... 6 common frames omitted

**Comment by doortts** [comment]
안녕하세요? planning 이라는 프로젝트에서 README를 온라인에서 에디팅할 때 말씀이신거죠?

**Comment by hadesyi** [comment]
네 맞습니다.

**Comment by doortts** [comment]
@hadesyi admin 계정으로는 online readme 수정이 가능한데 다른 계정으로는 안된다는 말씀이시죠? 다른 계정이 프로젝트 owner 인가요? 아니면 멤버인가요?

**Comment by hadesyi** [comment]
user 계정이 owner 관리자 권한 입니다.

**Comment by doortts** [comment]
왠지 권한문제 같은데 음 잘 모르겠네요..;; admin으로만 README 가 수정이 된다라..
혹시 해당 유저로 README.md 파일을 git push 로 넣는 건 가능하세요?

**Comment by hadesyi** [comment]
![image](https://cloud.githubusercontent.com/assets/84391/17610771/652234fc-607c-11e6-8244-156f123148ae.png)
user 계정(프로젝트 관리자 권한)으로 readme.md 를 작성 하면 에러가 납니다.

그리고 git push로는 잘들어 갑니다. 깃으로 들어간 md 파일을 수정하면 수정이 안되네요.
로그 남깁니다.

access.log
2xx.xxx.xxx - sklee [12/Aug/2016:11:05:31 +0900] "GET /messages.js HTTP/1.1" 200 - "http://xxx/post/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 15ms
 - sklee [12/Aug/2016:11:05:37 +0900] "GET /post/1/editform HTTP/1.1" 200 - "http://planning/iccsWs/post/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 93ms
xxx - sklee [12/Aug/2016:11:05:38 +0900] "GET /messages.js HTTP/1.1" 200 - "http://xxx/post/1/editform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 0ms
xxx - sklee [12/Aug/2016:11:05:38 +0900] "GET /files?containerType=BOARD_POST&containerId=24 HTTP/1.1" 200 - "http://xxx/post/1/editform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 0ms
- sklee [12/Aug/2016:11:05:43 +0900] "POST /planning/iccsWs/post/1/edit HTTP/1.1" 303 - "http://post/1/editform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 1123ms
- sklee [12/Aug/2016:11:05:43 +0900] "GET /planning/iccsWs/post/1 HTTP/1.1" 200 - "http:///post/1/editform" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 187ms
- sklee [12/Aug/2016:11:05:43 +0900] "GET /planning/iccsWs/issue/labels.css HTTP/1.1" 304 - "http://post/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 31ms
218.234.170.169 - sklee [12/Aug/2016:11:05:43 +0900] "GET /messages.js HTTP/1.1" 200 - "http:///planning/iccsWs/post/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36" 16ms

application.log

2016-08-12 10:58:39,359 - [DEBUG] - from play in play-akka.actor.default-dispatcher-76 
Unable to parse part of media range header '*/*'

2016-08-12 10:58:43,742 - [DEBUG] - from play in play-akka.actor.default-dispatcher-73 
Unable to parse part of media range header '*/*'

2016-08-12 10:58:49,140 - [DEBUG] - from play in play-akka.actor.default-dispatcher-82 
Unable to parse part of media range header '*/*'

2016-08-12 11:01:26,107 - [INFO] - from application in play-akka.actor.default-dispatcher-82 
No tree or no README file found at E:\yona-1.0.0\bin\repo\git\planning\iccsWs.git

2016-08-12 11:01:26,123 - [ERROR] - from application in play-akka.actor.default-dispatcher-82 
Missing unknown 0000000000000000000000000000000000000000

2016-08-12 11:01:26,185 - [ERROR] - from play in play-akka.actor.default-dispatcher-82 
Cannot invoke the action, eventually got an error: java.lang.NullPointerException

2016-08-12 11:01:26,185 - [ERROR] - from application in play-akka.actor.default-dispatcher-82 


! @713iblnj8 - Internal server error, for (GET) [/planning/iccsWs/post/1] ->

play.api.Application$$anon$1: Execution exception[[NullPointerException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.4.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.10-2.3.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.NullPointerException: null
	at utils.Markdown.renderWithHighlight(Markdown.java:134) ~[yona.yona-1.0.2.jar:1.0.2]
	at utils.Markdown.render(Markdown.java:212) ~[yona.yona-1.0.2.jar:1.0.2]
	at utils.Markdown.render(Markdown.java:217) ~[yona.yona-1.0.2.jar:1.0.2]
	at views.html.board.view$.apply(view.template.scala:128) ~[yona.yona-1.0.2.jar:1.0.2]
	at views.html.board.view$.render(view.template.scala:233) ~[yona.yona-1.0.2.jar:1.0.2]
	at views.html.board.view.render(view.template.scala) ~[yona.yona-1.0.2.jar:1.0.2]
	at controllers.BoardApp.post(BoardApp.java:264) ~[yona.yona-1.0.2.jar:1.0.2]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(routes_routing.scala:2290) ~[yona.yona-1.0.2.jar:na]
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$83$$anonfun$apply$83.apply(routes_routing.scala:2290) ~[yona.yona-1.0.2.jar:na]
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at Global$1.call(Global.java:190) ~[yona.yona-1.0.2.jar:na]
	at actions.AnonymousCheckAction.call(AnonymousCheckAction.java:57) ~[yona.yona-1.0.2.jar:1.0.2]
	at actions.IsAllowedAction.call(IsAllowedAction.java:69) ~[yona.yona-1.0.2.jar:1.0.2]
	at actions.AbstractProjectCheckAction.call(AbstractProjectCheckAction.java:85) ~[yona.yona-1.0.2.jar:1.0.2]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$.apply(Future.scala:31) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.Future$.apply(Future.scala:485) ~[org.scala-lang.scala-library-2.10.4.jar:na]
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.4.jar:na]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121) ~[com.typesafe.play.play_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496) ~[com.typesafe.play.play-iteratees_2.10-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [org.scala-lang.scala-library-2.10.4.jar:na]
	... 6 common frames omitted

2016-08-12 11:05:11,731 - [DEBUG] - from play in play-akka.actor.default-dispatcher-73 
Unable to parse part of media range header '*/*'
