### ISSUE TITLE
이슈 생성 시 "서버 오류가 발생하여 서비스를 이용할 수 없습니다" 에러

### ISSUE THREAD

**Issue by universe9999** [yona-projects/yona#799]
처음 설치 후 (10.3.39-MariaDB, yona 최신버전, 윈도우,자바8)
프로젝트 생성 시 오류가 나고, 새로고침 후 프로젝트 리스트에는 생성됩니다. 
들어가서 이슈 생성 시 "서버 오류가 발생하여 서비스를 이용할 수 없습니다"라고 뜨고, 
이슈 리스트에 들어가면 같은 에러가 발생합니다.

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class utils.Markdown]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) ~[org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could not initialize class utils.Markdown
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:25) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at play.db.ebean.TransactionalAction$1.call(TransactionalAction.java:18) ~[com.typesafe.play.play-java-ebean_2.10-2.3.10.jar:2.3.10]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:715) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebeaninternal.server.core.DefaultServer.execute(DefaultServer.java:709) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
        at com.avaje.ebean.Ebean.execute(Ebean.java:1264) ~[org.avaje.ebeanorm.avaje-ebeanorm-3.3.4.jar:na]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class utils.Markdown
        at views.html.issue.view$.apply(view.template.scala:217) ~[yona.yona-1.16.0.jar:1.16.0]
        at views.html.issue.view$.render(view.template.scala:698) ~[yona.yona-1.16.0.jar:1.16.0]
        at views.html.issue.view.render(view.template.scala) ~[yona.yona-1.16.0.jar:1.16.0]
        at controllers.IssueApp.issue(IssueApp.java:295) ~[yona.yona-1.16.0.jar:1.16.0]
        at Routes$$anonfun$routes$1$$anonfun$applyOrElse$211$$anonfun$apply$211.apply(routes_routing.scala:3868) ~[yona.yona-1.16.0.jar:na]

utils.Markdown클래스라고 나오는데 
어떻게 해결해야 할까요?

**Comment by doortts** [comment]
자바8 버전이 어떻게 되세요?

**Comment by universe9999** [comment]
> 자바8 버전이 어떻게 되세요?

자바 제어판에서는 jre 1.8.0_202라고 나오고, 
cmd - java version에서는 "15.0.2"라고 나오네요.

+환경변수 설정은 15로 해놨습니다.

**Comment by doortts** [comment]
cmd 기준으로 동작할거라서 java 버전이 너무 높아서인것 같습니다.

**Comment by universe9999** [comment]
> cmd 기준으로 동작할거라서 java 버전이 너무 높아서인것 같습니다.

버전 낮추니 바로 되네요. 감사합니다.
