### ISSUE TITLE
Yona Windows 10 설치시 에러 문의 드립니다.

### ISSUE THREAD

**Issue by rtboss** [yona-projects/yona#80]
Windows 10에서 MariaDB로 설치시 아래 에러가 발생 합니다.
도움 부탁드립니다.

### 설치 조건 입니다.
* Yona :  yona-v1.0.2
* MariaDB : mariadb-10.1.11-winx64
* OS : Windows 10 Pro

### 에러 코드
```
. . .
alter table recent_project add constraint fk_recent_project_project_2 foreign key (project_id) references project (id) on delete CASCADE on update CASCADE;

[warn] play - Run with -DapplyEvolutions.default=true if you want to run them automatically (be careful)
Oops, cannot start the server.
@713e9p22j: Database 'default' needs evolution!
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:508)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
```

**Comment by YoonhoSoft** [comment]
저도 동일한 오류가 발생합니다.

•Yona : yona-v1.0.2-bin
•MariaDB : mariadb-10.1.11-winx64
•JDK : jdk-8u102-windows-x64
•OS : Windows Server 2012 R2

그냥 리눅스 쓰면 되는데, 굳이~~~ 원도우 쓰겠다고 해서 여러 사람 피곤하게 하는 듯한 죄송한 마음은 들지만 그래도 굳이^^ 해결해 보고 싶네요.

추가로, MariaDB의 yona 계정에 대한 비밀번호를 "yonadan"를 사용하면 정상 작동하는데, 비밀번호를 다른 것으로 사용하면 db 접속이 안되는 오류가 있습니다.
이슈 #14 와 비슷한 증상입니다.

**Comment by doortts** [comment]
@rtboss https://github.com/yona-projects/yona#windows의-경우 부분을 참고해 주시겠어요?

![image](https://cloud.githubusercontent.com/assets/520523/17590425/bbeefbac-6014-11e6-8986-3050538ed1e8.png)

windows 경우에는 설정파일을 비롯하여 위 링크에서 권장한대로 직접 다 옵션으로 지정해서 실행하시는걸 추천드려요. 그래야 db password도 application.conf에 지정된 패스워드로 정상 인식되는것 같더라구요.

@YoonhoSoft 님도 참고해주세요.

**Comment by rtboss** [comment]
@doortts 링크 내용으로 실행하니 정상 동작합니다.
감사합니다.

Yona 폴드를 "C:\yona-1.0.2"로 변경하고 Command 창에서 아래와 같이 실행했습니다.
```
SET JAVA_OPTS=-Dyona.home=C:\yona-1.0.2 -Dconfig.file=C:\yona-1.0.2\conf\application.conf -Dlogger.file=C:\yona-1.0.2\conf\application-logger.xml

bin/yona.bat
```

@YoonhoSoft 님 한번 확인해 보세요.
저도 MariaDB의 yona 계정 비밀번호 문제가 있어, 일단  "yonadan"으로 적용 했습니다.

**Comment by rtboss** [comment]
MariaDB의 yona 계정 비밀번호 문제도 해결 되었습니다.

**Comment by YoonhoSoft** [comment]
말씀 하신 "SET JAVA_OPTS" 방법으로 해결했습니다.

원도우에선 그 방법이 "할 수 있다."는 옵션이 아니라 필수가 되야할 것 같습니다^^

로그인 페이지 보이니 감동이네요. 감사합니다.

**Comment by doortts** [comment]
@rtboss @YoonhoSoft 고생하셨어요. 고맙습니다.

로그인 페이지에 감동을 드렸다니 눈물이 나네요..;;; (미안해요..)
