### ISSUE TITLE
실행 오류 centos 6 환경

### ISSUE THREAD

**Issue by godsman** [yona-projects/yona#89]
bin/yona 를 실행하면 아래와 같이 오류가 발생합니다.
CentOS 7 가상머신에서 잘 실행되는 것을 확인한 후 CentOS 6 리얼머신에 설치했습니다.
리얼머신에서는 아래와 같이 오류가 발생합니다.

이슈 #3 과 같은 내용입니다.
처음 실행시 
- 발생하는 것이고요.(yona 1.0.4) 
- 설정은 잘 되어 있습니다.
- CentOS 6에 jdk1.8.102

를 설치했습니다.

설정---------------------
MariaDB [(none)]> show variables like 'innodb_lar%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| innodb_large_prefix | ON    |
+---------------------+-------+
1 row in set (0.00 sec)

MariaDB [(none)]> show variables like 'innodb_file%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | ON        |
| innodb_file_format_max   | Barracuda |
| innodb_file_per_table    | ON        |
+--------------------------+-----------+
4 rows in set (0.00 sec)

오류 ---------------------
# /etc/init.d/mysql start

Starting MySQL.161018 14:51:40 mysqld_safe Logging to '/var/lib/mysql/svnhost.err'.
 SUCCESS! 
# bin/yona

Play server process ID is 28283
[info] play - database [default] connected at jdbc:mysql://127.0.0.1:3306/yona
[error] play - 
Oops, cannot start the server.
@71mclijje: Database 'default' is in an inconsistent state!
        at play.api.db.evolutions.Evolutions$.checkEvolutionsState(Evolutions.scala:196)
        at play.api.db.evolutions.Evolutions$.databaseEvolutions(Evolutions.scala:367)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:332)
        at play.api.db.evolutions.Evolutions$$anonfun$evolutionScript$2.apply(Evolutions.scala:330)
        at scala.Option.map(Option.scala:145)
        at play.api.db.evolutions.Evolutions$.evolutionScript(Evolutions.scala:330)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply$mcV$sp(Evolutions.scala:486)
        at play.api.db.evolutions.EvolutionsPlugin.withLock(Evolutions.scala:531)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:485)
        at play.api.db.evolutions.EvolutionsPlugin$$anonfun$onStart$1.apply(Evolutions.scala:483)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.db.evolutions.EvolutionsPlugin.onStart(Evolutions.scala:483)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.api.Play$$anonfun$start$1.apply(Play.scala:91)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.Play$.start(Play.scala:90)
        at play.core.StaticApplication.<init>(ApplicationProvider.scala:55)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:244)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)

**Comment by doortts** [comment]
https://github.com/yona-projects/yona/blob/next/restart.sh 를 참고해서 한 번 실행해봐 주시겠어요?

> Database 'default' is in an inconsistent state!

이 경우는 다음 두 가지 경우가 가장 흔한데요, 

- 설치중간에 띄웠다가 아차! 하고 다시 다른 설정하고 다시 실행하는 식으로 설치 순서가 섞인경우
- 한 번 설치했다고 다시 설치하려는 경우

우선 위 shell 에서 명령 실행 부분 참고해서 실행해봐 주시고 만약 여전히 DB 불일치 상태( inconsistent state) 오류가 발생한다면 DB 삭제하고 다시 설치해봐주세요.
